/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { getConfig, updateConfig, getStatus, testAPIKeys, listLogs, unbanUser, deleteFlaggedHash, clearFlaggedHashes, riskControlAPI } from '@/features/admin-risk-control/data/datasources/adminRiskControlDatasource'
export type { ModerationMode, KeywordBlockingMode, ContentModerationModelFilterType, ContentModerationModelFilter, ContentModerationConfig, ContentModerationAPIKeyStatusValue, ContentModerationAPIKeyStatus, TestContentModerationAPIKeysPayload, TestContentModerationAPIKeysResponse, ContentModerationTestAuditResult, UpdateContentModerationConfig, ContentModerationRuntimeStatus, ContentModerationAPIKeyLoad, ContentModerationLog, ListContentModerationLogsParams, ContentModerationLogsResponse, ContentModerationUnbanUserResponse, DeleteFlaggedHashResponse, ClearFlaggedHashesResponse } from '@/features/admin-risk-control/data/datasources/adminRiskControlDatasource'
export { default } from '@/features/admin-risk-control/data/datasources/adminRiskControlDatasource'
