/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { isTotp2FARequired, setAuthToken, setRefreshToken, setTokenExpiresAt, getAuthToken, getRefreshToken, getTokenExpiresAt, clearAuthToken, login, login2FA, register, getCurrentUser, logout, isOAuthLoginCompletion, getOAuthCompletionKind, getPendingOAuthBindLoginKind, isPendingOAuthCreateAccountRequired, hasPendingOAuthSuggestedProfile, persistOAuthTokenContext, prepareOAuthBindAccessTokenCookie, refreshToken, revokeAllSessions, isAuthenticated, getPublicSettings, getLocalCaptcha, isWeChatWebOAuthEnabled, hasExplicitWeChatOAuthCapabilities, resolveWeChatOAuthStart, resolveWeChatOAuthStartStrict, sendVerifyCode, sendPendingOAuthVerifyCode, validatePromoCode, validateInvitationCode, forgotPassword, resetPassword, completeLinuxDoOAuthRegistration, completeOIDCOAuthRegistration, completeWeChatOAuthRegistration, createPendingLinuxDoOAuthAccount, createPendingOIDCOAuthAccount, createPendingWeChatOAuthAccount, createPendingDingTalkOAuthAccount, completePendingOAuthBindLogin, exchangePendingOAuthCompletion, authAPI, clearCredentialKeyPrefetch, createCredentialEnvelope, prefetchCredentialKey } from '@/features/auth/data/datasources/authDatasource'
export type { LoginResponse, LocalCaptchaChallenge, RefreshTokenResponse, OAuthTokenResponse, PendingOAuthBindLoginResponse, PendingOAuthExchangeResponse, PendingOAuthCreateAccountResponse, PendingOAuthSendVerifyCodeResponse, OAuthCompletionKind, OAuthAdoptionDecision, WeChatOAuthMode, WeChatOAuthUnavailableReason, ResolvedWeChatOAuthStart, WeChatOAuthPublicSettings, ValidatePromoCodeResponse, ValidateInvitationCodeResponse, ForgotPasswordRequest, ForgotPasswordResponse, ResetPasswordRequest, ResetPasswordResponse } from '@/features/auth/data/datasources/authDatasource'
export { default } from '@/features/auth/data/datasources/authDatasource'
