/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { paymentAPI } from '@/features/billing/data/datasources/paymentDatasource'
export type { PublicOrderVerifyResult } from '@/features/billing/data/datasources/paymentDatasource'
export { redeem, getHistory, redeemAPI } from '@/features/billing/data/datasources/redeemDatasource'
export type { RedeemHistoryItem } from '@/features/billing/data/datasources/redeemDatasource'
export { default } from '@/features/billing/data/datasources/redeemDatasource'
export * as payment from '@/features/billing/data/datasources/paymentDatasource'
