/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { list, getAll, getAllWithCount, getById, create, update, deleteProxy, toggleStatus, testProxy, checkProxyQuality, getStats, getProxyAccounts, batchCreate, batchDelete, exportData, importData, proxiesAPI } from '@/features/admin-proxies/data/datasources/adminProxiesDatasource'
export { default } from '@/features/admin-proxies/data/datasources/adminProxiesDatasource'
