/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 */
export * from '@/features/admin-proxies/data/datasources/adminProxiesDatasource'
export { default } from '@/features/admin-proxies/data/datasources/adminProxiesDatasource'
