/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { getAvailable, userChannelsAPI } from '@/features/channels-user/data/datasources/channelsUserDatasource'
export type { UserAvailableGroup, UserPricingInterval, UserSupportedModelPricing, UserSupportedModel, UserChannelPlatformSection, UserAvailableChannel } from '@/features/channels-user/data/datasources/channelsUserDatasource'
export { default } from '@/features/channels-user/data/datasources/channelsUserDatasource'
