/**
 * AdminChannelsQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminChannelsQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminChannelsRepository } from '@/features/admin-channels/domain/repositories/adminChannelsRepository'
import { adminChannelsRepository as default_adminChannels_repo } from '@/features/admin-channels/data/repositories/adminChannelsRepositoryImpl'

export function createAdminChannelsQueryStore(adminChannelsRepo: AdminChannelsRepository = default_adminChannels_repo) {
  return defineStore('adminChannels/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, getById: false, getModelDefaultPricing: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, getById: null as unknown, getModelDefaultPricing: null as unknown })

  const list: AdminChannelsRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (adminChannelsRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as AdminChannelsRepository['list']

  const getById: AdminChannelsRepository['getById'] = ((...args: unknown[]) => {
    loading.getById = true
    errors.getById = null
    return Promise.resolve()
      .then(() => (adminChannelsRepo.getById as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getById = error; throw error })
      .finally(() => { loading.getById = false })
  }) as AdminChannelsRepository['getById']

  const getModelDefaultPricing: AdminChannelsRepository['getModelDefaultPricing'] = ((...args: unknown[]) => {
    loading.getModelDefaultPricing = true
    errors.getModelDefaultPricing = null
    return Promise.resolve()
      .then(() => (adminChannelsRepo.getModelDefaultPricing as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getModelDefaultPricing = error; throw error })
      .finally(() => { loading.getModelDefaultPricing = false })
  }) as AdminChannelsRepository['getModelDefaultPricing']

    return { loading, errors, list, getById, getModelDefaultPricing }
  })
}

export const useAdminChannelsQueryStore = createAdminChannelsQueryStore()
