/**
 * AdminChannelsActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminChannelsActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminChannelsRepository } from '@/features/admin-channels/domain/repositories/adminChannelsRepository'
import { adminChannelsRepository as default_adminChannels_repo } from '@/features/admin-channels/data/repositories/adminChannelsRepositoryImpl'

export function createAdminChannelsActionStore(adminChannelsRepo: AdminChannelsRepository = default_adminChannels_repo) {
  return defineStore('adminChannels/action', () => {
    const loading = reactive<Record<string, boolean>>({ create: false, update: false, remove: false, syncPricingModels: false })
    const errors = reactive<Record<string, unknown>>({ create: null as unknown, update: null as unknown, remove: null as unknown, syncPricingModels: null as unknown })

  const create: AdminChannelsRepository['create'] = ((...args: unknown[]) => {
    loading.create = true
    errors.create = null
    return Promise.resolve()
      .then(() => (adminChannelsRepo.create as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.create = error; throw error })
      .finally(() => { loading.create = false })
  }) as AdminChannelsRepository['create']

  const update: AdminChannelsRepository['update'] = ((...args: unknown[]) => {
    loading.update = true
    errors.update = null
    return Promise.resolve()
      .then(() => (adminChannelsRepo.update as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.update = error; throw error })
      .finally(() => { loading.update = false })
  }) as AdminChannelsRepository['update']

  const remove: AdminChannelsRepository['remove'] = ((...args: unknown[]) => {
    loading.remove = true
    errors.remove = null
    return Promise.resolve()
      .then(() => (adminChannelsRepo.remove as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.remove = error; throw error })
      .finally(() => { loading.remove = false })
  }) as AdminChannelsRepository['remove']

  const syncPricingModels: AdminChannelsRepository['syncPricingModels'] = ((...args: unknown[]) => {
    loading.syncPricingModels = true
    errors.syncPricingModels = null
    return Promise.resolve()
      .then(() => (adminChannelsRepo.syncPricingModels as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.syncPricingModels = error; throw error })
      .finally(() => { loading.syncPricingModels = false })
  }) as AdminChannelsRepository['syncPricingModels']

    return { loading, errors, create, update, remove, syncPricingModels }
  })
}

export const useAdminChannelsActionStore = createAdminChannelsActionStore()
