/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useBilling — thin orchestrator composable for Billing.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useBillingQueryStore } from '@/features/billing/presentation/stores/billingQueryStore'
import { useBillingActionStore } from '@/features/billing/presentation/stores/billingActionStore'

export function useBilling() {
  const q_billingQueryStore = useBillingQueryStore()
  const a_billingActionStore = useBillingActionStore()
  return {
    ...q_billingQueryStore,
    ...a_billingActionStore,
  }
}
