/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAuth — thin orchestrator composable for Auth.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAuthQueryStore } from '@/features/auth/presentation/stores/authQueryStore'
import { useAuthActionStore } from '@/features/auth/presentation/stores/authActionStore'

export function useAuth() {
  const q_authQueryStore = useAuthQueryStore()
  const a_authActionStore = useAuthActionStore()
  return {
    ...q_authQueryStore,
    ...a_authActionStore,
  }
}
