import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const batchImageRoutes: RouteRecordRaw[] = [
  {
    path: '/batch-image',
    name: 'BatchImageGuide',
    alias: '/docs/batch-image',
    component: () => import('@/features/batch-image/presentation/pages/BatchImageGuidePage.vue'),
    meta: { requiresAuth: true, requiresAdmin: false, title: 'Batch Image Guide', titleKey: 'batchImageGuide.title', descriptionKey: 'batchImageGuide.description' },
  },
]
