/**
 * SubscriptionsQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createSubscriptionsQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { SubscriptionsRepository } from '@/features/subscriptions/domain/repositories/subscriptionsRepository'
import { subscriptionsRepository as default_subscriptions_repo } from '@/features/subscriptions/data/repositories/subscriptionsRepositoryImpl'

export function createSubscriptionsQueryStore(subscriptionsRepo: SubscriptionsRepository = default_subscriptions_repo) {
  return defineStore('subscriptions/query', () => {
    const loading = reactive<Record<string, boolean>>({ getMySubscriptions: false, getActiveSubscriptions: false, getSubscriptionsProgress: false, getSubscriptionSummary: false, getSubscriptionProgress: false })
    const errors = reactive<Record<string, unknown>>({ getMySubscriptions: null as unknown, getActiveSubscriptions: null as unknown, getSubscriptionsProgress: null as unknown, getSubscriptionSummary: null as unknown, getSubscriptionProgress: null as unknown })

  const getMySubscriptions: SubscriptionsRepository['getMySubscriptions'] = ((...args: unknown[]) => {
    loading.getMySubscriptions = true
    errors.getMySubscriptions = null
    return Promise.resolve()
      .then(() => (subscriptionsRepo.getMySubscriptions as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getMySubscriptions = error; throw error })
      .finally(() => { loading.getMySubscriptions = false })
  }) as SubscriptionsRepository['getMySubscriptions']

  const getActiveSubscriptions: SubscriptionsRepository['getActiveSubscriptions'] = ((...args: unknown[]) => {
    loading.getActiveSubscriptions = true
    errors.getActiveSubscriptions = null
    return Promise.resolve()
      .then(() => (subscriptionsRepo.getActiveSubscriptions as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getActiveSubscriptions = error; throw error })
      .finally(() => { loading.getActiveSubscriptions = false })
  }) as SubscriptionsRepository['getActiveSubscriptions']

  const getSubscriptionsProgress: SubscriptionsRepository['getSubscriptionsProgress'] = ((...args: unknown[]) => {
    loading.getSubscriptionsProgress = true
    errors.getSubscriptionsProgress = null
    return Promise.resolve()
      .then(() => (subscriptionsRepo.getSubscriptionsProgress as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getSubscriptionsProgress = error; throw error })
      .finally(() => { loading.getSubscriptionsProgress = false })
  }) as SubscriptionsRepository['getSubscriptionsProgress']

  const getSubscriptionSummary: SubscriptionsRepository['getSubscriptionSummary'] = ((...args: unknown[]) => {
    loading.getSubscriptionSummary = true
    errors.getSubscriptionSummary = null
    return Promise.resolve()
      .then(() => (subscriptionsRepo.getSubscriptionSummary as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getSubscriptionSummary = error; throw error })
      .finally(() => { loading.getSubscriptionSummary = false })
  }) as SubscriptionsRepository['getSubscriptionSummary']

  const getSubscriptionProgress: SubscriptionsRepository['getSubscriptionProgress'] = ((...args: unknown[]) => {
    loading.getSubscriptionProgress = true
    errors.getSubscriptionProgress = null
    return Promise.resolve()
      .then(() => (subscriptionsRepo.getSubscriptionProgress as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getSubscriptionProgress = error; throw error })
      .finally(() => { loading.getSubscriptionProgress = false })
  }) as SubscriptionsRepository['getSubscriptionProgress']

    return { loading, errors, getMySubscriptions, getActiveSubscriptions, getSubscriptionsProgress, getSubscriptionSummary, getSubscriptionProgress }
  })
}

export const useSubscriptionsQueryStore = createSubscriptionsQueryStore()
