/**
 * AdminClusterQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminClusterQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminClusterRepository } from '@/features/admin-cluster/domain/repositories/adminClusterRepository'
import { adminClusterRepository as default_adminCluster_repo } from '@/features/admin-cluster/data/repositories/adminClusterRepositoryImpl'

export function createAdminClusterQueryStore(adminClusterRepo: AdminClusterRepository = default_adminCluster_repo) {
  return defineStore('adminCluster/query', () => {
    const loading = reactive<Record<string, boolean>>({ getClusterStatus: false })
    const errors = reactive<Record<string, unknown>>({ getClusterStatus: null as unknown })

  const getClusterStatus: AdminClusterRepository['getClusterStatus'] = ((...args: unknown[]) => {
    loading.getClusterStatus = true
    errors.getClusterStatus = null
    return Promise.resolve()
      .then(() => (adminClusterRepo.getClusterStatus as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getClusterStatus = error; throw error })
      .finally(() => { loading.getClusterStatus = false })
  }) as AdminClusterRepository['getClusterStatus']

    return { loading, errors, getClusterStatus }
  })
}

export const useAdminClusterQueryStore = createAdminClusterQueryStore()
