/**
 * AnnouncementsActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAnnouncementsActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminAnnouncementsRepository } from '@/features/announcements/domain/repositories/adminAnnouncementsRepository'
import type { AnnouncementsRepository } from '@/features/announcements/domain/repositories/announcementsRepository'
import { adminAnnouncementsRepository as default_adminAnnouncements_repo } from '@/features/announcements/data/repositories/adminAnnouncementsRepositoryImpl'
import { announcementsRepository as default_announcements_repo } from '@/features/announcements/data/repositories/announcementsRepositoryImpl'

export function createAnnouncementsActionStore(adminAnnouncementsRepo: AdminAnnouncementsRepository = default_adminAnnouncements_repo, announcementsRepo: AnnouncementsRepository = default_announcements_repo) {
  return defineStore('announcements/action', () => {
    const loading = reactive<Record<string, boolean>>({ create: false, update: false, deleteAnnouncement: false, markRead: false })
    const errors = reactive<Record<string, unknown>>({ create: null as unknown, update: null as unknown, deleteAnnouncement: null as unknown, markRead: null as unknown })

  const create: AdminAnnouncementsRepository['create'] = ((...args: unknown[]) => {
    loading.create = true
    errors.create = null
    return Promise.resolve()
      .then(() => (adminAnnouncementsRepo.create as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.create = error; throw error })
      .finally(() => { loading.create = false })
  }) as AdminAnnouncementsRepository['create']

  const update: AdminAnnouncementsRepository['update'] = ((...args: unknown[]) => {
    loading.update = true
    errors.update = null
    return Promise.resolve()
      .then(() => (adminAnnouncementsRepo.update as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.update = error; throw error })
      .finally(() => { loading.update = false })
  }) as AdminAnnouncementsRepository['update']

  const deleteAnnouncement: AdminAnnouncementsRepository['deleteAnnouncement'] = ((...args: unknown[]) => {
    loading.deleteAnnouncement = true
    errors.deleteAnnouncement = null
    return Promise.resolve()
      .then(() => (adminAnnouncementsRepo.deleteAnnouncement as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteAnnouncement = error; throw error })
      .finally(() => { loading.deleteAnnouncement = false })
  }) as AdminAnnouncementsRepository['deleteAnnouncement']

  const markRead: AnnouncementsRepository['markRead'] = ((...args: unknown[]) => {
    loading.markRead = true
    errors.markRead = null
    return Promise.resolve()
      .then(() => (announcementsRepo.markRead as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.markRead = error; throw error })
      .finally(() => { loading.markRead = false })
  }) as AnnouncementsRepository['markRead']

    return { loading, errors, create, update, deleteAnnouncement, markRead }
  })
}

export const useAnnouncementsActionStore = createAnnouncementsActionStore()
