/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAffiliate — thin orchestrator composable for Affiliate.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAffiliateQueryStore } from '@/features/affiliate/presentation/stores/affiliateQueryStore'
import { useAffiliateActionStore } from '@/features/affiliate/presentation/stores/affiliateActionStore'

export function useAffiliate() {
  const q_affiliateQueryStore = useAffiliateQueryStore()
  const a_affiliateActionStore = useAffiliateActionStore()
  return {
    ...q_affiliateQueryStore,
    ...a_affiliateActionStore,
  }
}
