import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const adminUsersRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/users',
    name: 'AdminUsers',
    component: () => import('@/features/admin-users/presentation/pages/UsersPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: true, title: 'User Management', titleKey: 'admin.users.title', descriptionKey: 'admin.users.description' },
  },
]
