/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminRedeem — thin orchestrator composable for AdminRedeem.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminRedeemQueryStore } from '@/features/admin-redeem/presentation/stores/adminRedeemQueryStore'
import { useAdminRedeemActionStore } from '@/features/admin-redeem/presentation/stores/adminRedeemActionStore'

export function useAdminRedeem() {
  const q_adminRedeemQueryStore = useAdminRedeemQueryStore()
  const a_adminRedeemActionStore = useAdminRedeemActionStore()
  return {
    ...q_adminRedeemQueryStore,
    ...a_adminRedeemActionStore,
  }
}
