/**
 * KeysQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createKeysQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { KeysRepository } from '@/features/keys/domain/repositories/keysRepository'
import { keysRepository as default_keys_repo } from '@/features/keys/data/repositories/keysRepositoryImpl'

export function createKeysQueryStore(keysRepo: KeysRepository = default_keys_repo) {
  return defineStore('keys/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, getById: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, getById: null as unknown })

  const list: KeysRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (keysRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as KeysRepository['list']

  const getById: KeysRepository['getById'] = ((...args: unknown[]) => {
    loading.getById = true
    errors.getById = null
    return Promise.resolve()
      .then(() => (keysRepo.getById as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getById = error; throw error })
      .finally(() => { loading.getById = false })
  }) as KeysRepository['getById']

    return { loading, errors, list, getById }
  })
}

export const useKeysQueryStore = createKeysQueryStore()
