package admin

import (
	"github.com/Wei-Shaw/sub2api/internal/application/service"
	"github.com/Wei-Shaw/sub2api/internal/transport/http/handler/dto"
)

func buildSettingsUpdateResponsePayload(
	settings *service.SystemSettings,
	totpEncryptionKeyConfigured bool,
	passkeyConfigured bool,
	passkeyRPID string,
	passkeyRPOrigins []string,
) dto.SystemSettings {
	return dto.SystemSettings{
		FrontendURL:                 settings.FrontendURL,
		TotpEnabled:                 settings.TotpEnabled,
		TotpEncryptionKeyConfigured: totpEncryptionKeyConfigured,
		PasskeyEnabled:              settings.PasskeyEnabled,
		PasskeyConfigured:           passkeyConfigured,
		PasskeyRPID:                 passkeyRPID,
		PasskeyRPOrigins:            passkeyRPOrigins,
		SessionBindingEnabled:       settings.SessionBindingEnabled,
		StepUpEnabled:               settings.StepUpEnabled,

		SMTPHost:               settings.SMTPHost,
		SMTPPort:               settings.SMTPPort,
		SMTPUsername:           settings.SMTPUsername,
		SMTPPasswordConfigured: settings.SMTPPasswordConfigured,
		SMTPFrom:               settings.SMTPFrom,
		SMTPFromName:           settings.SMTPFromName,
		SMTPUseTLS:             settings.SMTPUseTLS,

		APIKeyACLTrustForwardedIP: settings.APIKeyACLTrustForwardedIP,
		ClientIPResolutionMode:    settings.ClientIPResolutionMode,
		ClientIPTrustedProxies:    settings.ClientIPTrustedProxies,
		ClientIPResolutionStatus:  settings.ClientIPResolutionStatus,

		SiteName:                 settings.SiteName,
		SiteLogo:                 settings.SiteLogo,
		APIBaseURL:               settings.APIBaseURL,
		DocURL:                   settings.DocURL,
		HideCcsImportButton:      settings.HideCcsImportButton,
		TableDefaultPageSize:     settings.TableDefaultPageSize,
		TablePageSizeOptions:     settings.TablePageSizeOptions,
		CustomEndpoints:          dto.ParseCustomEndpoints(settings.CustomEndpoints),
		EnableModelFallback:      settings.EnableModelFallback,
		FallbackModelAnthropic:   settings.FallbackModelAnthropic,
		FallbackModelOpenAI:      settings.FallbackModelOpenAI,
		FallbackModelGemini:      settings.FallbackModelGemini,
		FallbackModelAntigravity: settings.FallbackModelAntigravity,
		EnableIdentityPatch:      settings.EnableIdentityPatch,
		IdentityPatchPrompt:      settings.IdentityPatchPrompt,

		OpsMonitoringEnabled:         settings.OpsMonitoringEnabled,
		OpsRealtimeMonitoringEnabled: settings.OpsRealtimeMonitoringEnabled,
		OpsQueryModeDefault:          settings.OpsQueryModeDefault,
		OpsMetricsIntervalSeconds:    settings.OpsMetricsIntervalSeconds,
		MinClaudeCodeVersion:         settings.MinClaudeCodeVersion,
		MaxClaudeCodeVersion:         settings.MaxClaudeCodeVersion,

		AllowUngroupedKeyScheduling:            settings.AllowUngroupedKeyScheduling,
		SchedulerV2Enabled:                     settings.SchedulerV2Enabled,
		SchedulerV2Status:                      settings.SchedulerV2Status,
		SchedulerV2Error:                       settings.SchedulerV2Error,
		SchedulerV2CandidateLimit:              settings.SchedulerV2CandidateLimit,
		SchedulerV2ScanLimit:                   settings.SchedulerV2ScanLimit,
		RequestPriorityAdmissionEnabled:        settings.RequestPriorityAdmissionEnabled,
		RequestPriorityPendingLimitPerInstance: settings.RequestPriorityPendingLimitPerInstance,
		RequestPriorityPendingMiBPerInstance:   settings.RequestPriorityPendingMiBPerInstance,
		StreamModePerformanceEnabled:           settings.StreamModePerformanceEnabled,
		OpenAIWSModeRouterV2Enabled:            settings.OpenAIWSModeRouterV2Enabled,

		EnableFingerprintUnification:           settings.EnableFingerprintUnification,
		EnableMetadataPassthrough:              settings.EnableMetadataPassthrough,
		EnableCCHSigning:                       settings.EnableCCHSigning,
		EnableClaudeOAuthSystemPromptInjection: settings.EnableClaudeOAuthSystemPromptInjection,
		ClaudeOAuthSystemPrompt:                settings.ClaudeOAuthSystemPrompt,
		ClaudeOAuthSystemPromptBlocks:          settings.ClaudeOAuthSystemPromptBlocks,
		EnableAnthropicCacheTTL1hInjection:     settings.EnableAnthropicCacheTTL1hInjection,
		RewriteMessageCacheControl:             settings.RewriteMessageCacheControl,
		EnableClientDatelineNormalization:      settings.EnableClientDatelineNormalization,
		AntigravityUserAgentVersion:            settings.AntigravityUserAgentVersion,
		OpenAICodexUserAgent:                   settings.OpenAICodexUserAgent,
		OpenAICodexClientVersion:               settings.OpenAICodexClientVersion,
		OpenAICodexClientVersionSynced:         settings.OpenAICodexClientVersionSynced,
		OpenAICodexVersionAutoSyncEnabled:      settings.OpenAICodexVersionAutoSyncEnabled,

		MinCodexVersion:                      settings.MinCodexVersion,
		MaxCodexVersion:                      settings.MaxCodexVersion,
		CodexCLIOnlyBlacklist:                settings.CodexCLIOnlyBlacklist,
		CodexCLIOnlyWhitelist:                settings.CodexCLIOnlyWhitelist,
		CodexCLIOnlyAllowAppServerClients:    settings.CodexCLIOnlyAllowAppServerClients,
		CodexCLIOnlyEngineFingerprintSignals: settings.CodexCLIOnlyEngineFingerprintSignals,
		WebSearchEmulationEnabled:            settings.WebSearchEmulationEnabled,

		OpenAILowUpstreamRatePriorityEnabled:                   settings.OpenAILowUpstreamRatePriorityEnabled,
		OpenAIOAuthSchedulingRateMultiplier:                    settings.OpenAIOAuthSchedulingRateMultiplier,
		OpenAIContentSessionBurstBalanceEnabled:                settings.OpenAIContentSessionBurstBalanceEnabled,
		OpenAIAdvancedSchedulerEnabled:                         settings.OpenAIAdvancedSchedulerEnabled,
		OpenAIAdvancedSchedulerStickyWeightedEnabled:           settings.OpenAIAdvancedSchedulerStickyWeightedEnabled,
		OpenAIAdvancedSchedulerSubscriptionPriorityEnabled:     settings.OpenAIAdvancedSchedulerSubscriptionPriorityEnabled,
		OpenAIAdvancedSchedulerLBTopK:                          settings.OpenAIAdvancedSchedulerLBTopK,
		OpenAIAdvancedSchedulerWeightPriority:                  settings.OpenAIAdvancedSchedulerWeightPriority,
		OpenAIAdvancedSchedulerWeightLoad:                      settings.OpenAIAdvancedSchedulerWeightLoad,
		OpenAIAdvancedSchedulerWeightQueue:                     settings.OpenAIAdvancedSchedulerWeightQueue,
		OpenAIAdvancedSchedulerWeightErrorRate:                 settings.OpenAIAdvancedSchedulerWeightErrorRate,
		OpenAIAdvancedSchedulerWeightTTFT:                      settings.OpenAIAdvancedSchedulerWeightTTFT,
		OpenAIAdvancedSchedulerWeightReset:                     settings.OpenAIAdvancedSchedulerWeightReset,
		OpenAIAdvancedSchedulerWeightQuotaHeadroom:             settings.OpenAIAdvancedSchedulerWeightQuotaHeadroom,
		OpenAIAdvancedSchedulerWeightUpstreamCost:              settings.OpenAIAdvancedSchedulerWeightUpstreamCost,
		OpenAIAdvancedSchedulerWeightPreviousResponse:          settings.OpenAIAdvancedSchedulerWeightPreviousResponse,
		OpenAIAdvancedSchedulerWeightSessionSticky:             settings.OpenAIAdvancedSchedulerWeightSessionSticky,
		OpenAIAdvancedSchedulerEffectiveLBTopK:                 settings.OpenAIAdvancedSchedulerEffectiveLBTopK,
		OpenAIAdvancedSchedulerEffectiveWeightPriority:         settings.OpenAIAdvancedSchedulerEffectiveWeightPriority,
		OpenAIAdvancedSchedulerEffectiveWeightLoad:             settings.OpenAIAdvancedSchedulerEffectiveWeightLoad,
		OpenAIAdvancedSchedulerEffectiveWeightQueue:            settings.OpenAIAdvancedSchedulerEffectiveWeightQueue,
		OpenAIAdvancedSchedulerEffectiveWeightErrorRate:        settings.OpenAIAdvancedSchedulerEffectiveWeightErrorRate,
		OpenAIAdvancedSchedulerEffectiveWeightTTFT:             settings.OpenAIAdvancedSchedulerEffectiveWeightTTFT,
		OpenAIAdvancedSchedulerEffectiveWeightReset:            settings.OpenAIAdvancedSchedulerEffectiveWeightReset,
		OpenAIAdvancedSchedulerEffectiveWeightQuotaHeadroom:    settings.OpenAIAdvancedSchedulerEffectiveWeightQuotaHeadroom,
		OpenAIAdvancedSchedulerEffectiveWeightUpstreamCost:     settings.OpenAIAdvancedSchedulerEffectiveWeightUpstreamCost,
		OpenAIAdvancedSchedulerEffectiveWeightPreviousResponse: settings.OpenAIAdvancedSchedulerEffectiveWeightPreviousResponse,
		OpenAIAdvancedSchedulerEffectiveWeightSessionSticky:    settings.OpenAIAdvancedSchedulerEffectiveWeightSessionSticky,

		AccountQuotaNotifyEnabled:            settings.AccountQuotaNotifyEnabled,
		AccountQuotaNotifyEmails:             dto.NotifyEmailEntriesFromService(settings.AccountQuotaNotifyEmails),
		ChannelMonitorEnabled:                settings.ChannelMonitorEnabled,
		ChannelMonitorDefaultIntervalSeconds: settings.ChannelMonitorDefaultIntervalSeconds,
	}
}
