/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminCluster — thin orchestrator composable for AdminCluster.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminClusterQueryStore } from '@/features/admin-cluster/presentation/stores/adminClusterQueryStore'

export function useAdminCluster() {
  const q_adminClusterQueryStore = useAdminClusterQueryStore()
  return {
    ...q_adminClusterQueryStore,
  }
}
