/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 */
export * as adminAnnouncements from '@/features/announcements/data/datasources/adminAnnouncementsDatasource'
export * as announcements from '@/features/announcements/data/datasources/announcementsDatasource'
