/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { list, getById, create, update, deleteAnnouncement, getReadStatus } from '@/features/announcements/data/datasources/adminAnnouncementsDatasource'
export { default } from '@/features/announcements/data/datasources/adminAnnouncementsDatasource'
export { markRead } from '@/features/announcements/data/datasources/announcementsDatasource'
export * as adminAnnouncements from '@/features/announcements/data/datasources/adminAnnouncementsDatasource'
export * as announcements from '@/features/announcements/data/datasources/announcementsDatasource'
