/**
 * AdminRedeemActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminRedeemActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminRedeemRepository } from '@/features/admin-redeem/domain/repositories/adminRedeemRepository'
import { adminRedeemRepository as default_adminRedeem_repo } from '@/features/admin-redeem/data/repositories/adminRedeemRepositoryImpl'

export function createAdminRedeemActionStore(adminRedeemRepo: AdminRedeemRepository = default_adminRedeem_repo) {
  return defineStore('adminRedeem/action', () => {
    const loading = reactive<Record<string, boolean>>({ generate: false, deleteCode: false, batchDelete: false, batchUpdate: false, expire: false })
    const errors = reactive<Record<string, unknown>>({ generate: null as unknown, deleteCode: null as unknown, batchDelete: null as unknown, batchUpdate: null as unknown, expire: null as unknown })

  const generate: AdminRedeemRepository['generate'] = ((...args: unknown[]) => {
    loading.generate = true
    errors.generate = null
    return Promise.resolve()
      .then(() => (adminRedeemRepo.generate as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.generate = error; throw error })
      .finally(() => { loading.generate = false })
  }) as AdminRedeemRepository['generate']

  const deleteCode: AdminRedeemRepository['deleteCode'] = ((...args: unknown[]) => {
    loading.deleteCode = true
    errors.deleteCode = null
    return Promise.resolve()
      .then(() => (adminRedeemRepo.deleteCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteCode = error; throw error })
      .finally(() => { loading.deleteCode = false })
  }) as AdminRedeemRepository['deleteCode']

  const batchDelete: AdminRedeemRepository['batchDelete'] = ((...args: unknown[]) => {
    loading.batchDelete = true
    errors.batchDelete = null
    return Promise.resolve()
      .then(() => (adminRedeemRepo.batchDelete as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchDelete = error; throw error })
      .finally(() => { loading.batchDelete = false })
  }) as AdminRedeemRepository['batchDelete']

  const batchUpdate: AdminRedeemRepository['batchUpdate'] = ((...args: unknown[]) => {
    loading.batchUpdate = true
    errors.batchUpdate = null
    return Promise.resolve()
      .then(() => (adminRedeemRepo.batchUpdate as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchUpdate = error; throw error })
      .finally(() => { loading.batchUpdate = false })
  }) as AdminRedeemRepository['batchUpdate']

  const expire: AdminRedeemRepository['expire'] = ((...args: unknown[]) => {
    loading.expire = true
    errors.expire = null
    return Promise.resolve()
      .then(() => (adminRedeemRepo.expire as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.expire = error; throw error })
      .finally(() => { loading.expire = false })
  }) as AdminRedeemRepository['expire']

    return { loading, errors, generate, deleteCode, batchDelete, batchUpdate, expire }
  })
}

export const useAdminRedeemActionStore = createAdminRedeemActionStore()
