/**
 * AdminAccountsActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminAccountsActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminAccountsRepository } from '@/features/admin-accounts/domain/repositories/adminAccountsRepository'
import type { AntigravityRepository } from '@/features/admin-accounts/domain/repositories/antigravityRepository'
import type { GeminiRepository } from '@/features/admin-accounts/domain/repositories/geminiRepository'
import type { GrokRepository } from '@/features/admin-accounts/domain/repositories/grokRepository'
import type { ScheduledTestsRepository } from '@/features/admin-accounts/domain/repositories/scheduledTestsRepository'
import { adminAccountsRepository as default_adminAccounts_repo } from '@/features/admin-accounts/data/repositories/adminAccountsRepositoryImpl'
import { antigravityRepository as default_antigravity_repo } from '@/features/admin-accounts/data/repositories/antigravityRepositoryImpl'
import { geminiRepository as default_gemini_repo } from '@/features/admin-accounts/data/repositories/geminiRepositoryImpl'
import { grokRepository as default_grok_repo } from '@/features/admin-accounts/data/repositories/grokRepositoryImpl'
import { scheduledTestsRepository as default_scheduledTests_repo } from '@/features/admin-accounts/data/repositories/scheduledTestsRepositoryImpl'

export function createAdminAccountsActionStore(adminAccountsRepo: AdminAccountsRepository = default_adminAccounts_repo, antigravityRepo: AntigravityRepository = default_antigravity_repo, geminiRepo: GeminiRepository = default_gemini_repo, grokRepo: GrokRepository = default_grok_repo, scheduledTestsRepo: ScheduledTestsRepository = default_scheduledTests_repo) {
  return defineStore('adminAccounts/action', () => {
    const loading = reactive<Record<string, boolean>>({ create: false, duplicate: false, update: false, deleteAccount: false, toggleStatus: false, testAccount: false, refreshCredentials: false, applyOAuthCredentials: false, clearError: false, clearRateLimit: false, recoverState: false, resetAccountQuota: false, resetTempUnschedulable: false, generateAuthUrl: false, exchangeCode: false, batchCreate: false, batchUpdateCredentials: false, bulkUpdate: false, setSchedulable: false, syncUpstreamModels: false, syncUpstreamModelsPreview: false, syncFromCrs: false, importData: false, importCodexSession: false, createOpenAICodexPAT: false, refreshOpenAIToken: false, revertProxyFallback: false, batchClearError: false, batchRefresh: false, setPrivacy: false, resetOpenAIQuota: false, createSparkShadow: false, updateUpstreamBillingProbeSettings: false, setUpstreamBillingProbeEnabled: false, antigravity_generateAuthUrl: false, antigravity_exchangeCode: false, refreshAntigravityToken: false, gemini_generateAuthUrl: false, gemini_exchangeCode: false, grok_generateAuthUrl: false, grok_exchangeCode: false, refreshGrokToken: false, resetQuota: false, createFromSSO: false, scheduledTests_create: false, scheduledTests_update: false, deletePlan: false })
    const errors = reactive<Record<string, unknown>>({ create: null as unknown, duplicate: null as unknown, update: null as unknown, deleteAccount: null as unknown, toggleStatus: null as unknown, testAccount: null as unknown, refreshCredentials: null as unknown, applyOAuthCredentials: null as unknown, clearError: null as unknown, clearRateLimit: null as unknown, recoverState: null as unknown, resetAccountQuota: null as unknown, resetTempUnschedulable: null as unknown, generateAuthUrl: null as unknown, exchangeCode: null as unknown, batchCreate: null as unknown, batchUpdateCredentials: null as unknown, bulkUpdate: null as unknown, setSchedulable: null as unknown, syncUpstreamModels: null as unknown, syncUpstreamModelsPreview: null as unknown, syncFromCrs: null as unknown, importData: null as unknown, importCodexSession: null as unknown, createOpenAICodexPAT: null as unknown, refreshOpenAIToken: null as unknown, revertProxyFallback: null as unknown, batchClearError: null as unknown, batchRefresh: null as unknown, setPrivacy: null as unknown, resetOpenAIQuota: null as unknown, createSparkShadow: null as unknown, updateUpstreamBillingProbeSettings: null as unknown, setUpstreamBillingProbeEnabled: null as unknown, antigravity_generateAuthUrl: null as unknown, antigravity_exchangeCode: null as unknown, refreshAntigravityToken: null as unknown, gemini_generateAuthUrl: null as unknown, gemini_exchangeCode: null as unknown, grok_generateAuthUrl: null as unknown, grok_exchangeCode: null as unknown, refreshGrokToken: null as unknown, resetQuota: null as unknown, createFromSSO: null as unknown, scheduledTests_create: null as unknown, scheduledTests_update: null as unknown, deletePlan: null as unknown })

  const create: AdminAccountsRepository['create'] = ((...args: unknown[]) => {
    loading.create = true
    errors.create = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.create as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.create = error; throw error })
      .finally(() => { loading.create = false })
  }) as AdminAccountsRepository['create']

  const duplicate: AdminAccountsRepository['duplicate'] = ((...args: unknown[]) => {
    loading.duplicate = true
    errors.duplicate = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.duplicate as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.duplicate = error; throw error })
      .finally(() => { loading.duplicate = false })
  }) as AdminAccountsRepository['duplicate']

  const update: AdminAccountsRepository['update'] = ((...args: unknown[]) => {
    loading.update = true
    errors.update = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.update as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.update = error; throw error })
      .finally(() => { loading.update = false })
  }) as AdminAccountsRepository['update']

  const deleteAccount: AdminAccountsRepository['deleteAccount'] = ((...args: unknown[]) => {
    loading.deleteAccount = true
    errors.deleteAccount = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.deleteAccount as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteAccount = error; throw error })
      .finally(() => { loading.deleteAccount = false })
  }) as AdminAccountsRepository['deleteAccount']

  const toggleStatus: AdminAccountsRepository['toggleStatus'] = ((...args: unknown[]) => {
    loading.toggleStatus = true
    errors.toggleStatus = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.toggleStatus as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.toggleStatus = error; throw error })
      .finally(() => { loading.toggleStatus = false })
  }) as AdminAccountsRepository['toggleStatus']

  const testAccount: AdminAccountsRepository['testAccount'] = ((...args: unknown[]) => {
    loading.testAccount = true
    errors.testAccount = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.testAccount as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.testAccount = error; throw error })
      .finally(() => { loading.testAccount = false })
  }) as AdminAccountsRepository['testAccount']

  const refreshCredentials: AdminAccountsRepository['refreshCredentials'] = ((...args: unknown[]) => {
    loading.refreshCredentials = true
    errors.refreshCredentials = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.refreshCredentials as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.refreshCredentials = error; throw error })
      .finally(() => { loading.refreshCredentials = false })
  }) as AdminAccountsRepository['refreshCredentials']

  const applyOAuthCredentials: AdminAccountsRepository['applyOAuthCredentials'] = ((...args: unknown[]) => {
    loading.applyOAuthCredentials = true
    errors.applyOAuthCredentials = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.applyOAuthCredentials as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.applyOAuthCredentials = error; throw error })
      .finally(() => { loading.applyOAuthCredentials = false })
  }) as AdminAccountsRepository['applyOAuthCredentials']

  const clearError: AdminAccountsRepository['clearError'] = ((...args: unknown[]) => {
    loading.clearError = true
    errors.clearError = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.clearError as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.clearError = error; throw error })
      .finally(() => { loading.clearError = false })
  }) as AdminAccountsRepository['clearError']

  const clearRateLimit: AdminAccountsRepository['clearRateLimit'] = ((...args: unknown[]) => {
    loading.clearRateLimit = true
    errors.clearRateLimit = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.clearRateLimit as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.clearRateLimit = error; throw error })
      .finally(() => { loading.clearRateLimit = false })
  }) as AdminAccountsRepository['clearRateLimit']

  const recoverState: AdminAccountsRepository['recoverState'] = ((...args: unknown[]) => {
    loading.recoverState = true
    errors.recoverState = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.recoverState as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.recoverState = error; throw error })
      .finally(() => { loading.recoverState = false })
  }) as AdminAccountsRepository['recoverState']

  const resetAccountQuota: AdminAccountsRepository['resetAccountQuota'] = ((...args: unknown[]) => {
    loading.resetAccountQuota = true
    errors.resetAccountQuota = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.resetAccountQuota as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.resetAccountQuota = error; throw error })
      .finally(() => { loading.resetAccountQuota = false })
  }) as AdminAccountsRepository['resetAccountQuota']

  const resetTempUnschedulable: AdminAccountsRepository['resetTempUnschedulable'] = ((...args: unknown[]) => {
    loading.resetTempUnschedulable = true
    errors.resetTempUnschedulable = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.resetTempUnschedulable as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.resetTempUnschedulable = error; throw error })
      .finally(() => { loading.resetTempUnschedulable = false })
  }) as AdminAccountsRepository['resetTempUnschedulable']

  const generateAuthUrl: AdminAccountsRepository['generateAuthUrl'] = ((...args: unknown[]) => {
    loading.generateAuthUrl = true
    errors.generateAuthUrl = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.generateAuthUrl as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.generateAuthUrl = error; throw error })
      .finally(() => { loading.generateAuthUrl = false })
  }) as AdminAccountsRepository['generateAuthUrl']

  const exchangeCode: AdminAccountsRepository['exchangeCode'] = ((...args: unknown[]) => {
    loading.exchangeCode = true
    errors.exchangeCode = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.exchangeCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.exchangeCode = error; throw error })
      .finally(() => { loading.exchangeCode = false })
  }) as AdminAccountsRepository['exchangeCode']

  const batchCreate: AdminAccountsRepository['batchCreate'] = ((...args: unknown[]) => {
    loading.batchCreate = true
    errors.batchCreate = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.batchCreate as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchCreate = error; throw error })
      .finally(() => { loading.batchCreate = false })
  }) as AdminAccountsRepository['batchCreate']

  const batchUpdateCredentials: AdminAccountsRepository['batchUpdateCredentials'] = ((...args: unknown[]) => {
    loading.batchUpdateCredentials = true
    errors.batchUpdateCredentials = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.batchUpdateCredentials as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchUpdateCredentials = error; throw error })
      .finally(() => { loading.batchUpdateCredentials = false })
  }) as AdminAccountsRepository['batchUpdateCredentials']

  const bulkUpdate: AdminAccountsRepository['bulkUpdate'] = ((...args: unknown[]) => {
    loading.bulkUpdate = true
    errors.bulkUpdate = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.bulkUpdate as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.bulkUpdate = error; throw error })
      .finally(() => { loading.bulkUpdate = false })
  }) as AdminAccountsRepository['bulkUpdate']

  const setSchedulable: AdminAccountsRepository['setSchedulable'] = ((...args: unknown[]) => {
    loading.setSchedulable = true
    errors.setSchedulable = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.setSchedulable as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.setSchedulable = error; throw error })
      .finally(() => { loading.setSchedulable = false })
  }) as AdminAccountsRepository['setSchedulable']

  const syncUpstreamModels: AdminAccountsRepository['syncUpstreamModels'] = ((...args: unknown[]) => {
    loading.syncUpstreamModels = true
    errors.syncUpstreamModels = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.syncUpstreamModels as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.syncUpstreamModels = error; throw error })
      .finally(() => { loading.syncUpstreamModels = false })
  }) as AdminAccountsRepository['syncUpstreamModels']

  const syncUpstreamModelsPreview: AdminAccountsRepository['syncUpstreamModelsPreview'] = ((...args: unknown[]) => {
    loading.syncUpstreamModelsPreview = true
    errors.syncUpstreamModelsPreview = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.syncUpstreamModelsPreview as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.syncUpstreamModelsPreview = error; throw error })
      .finally(() => { loading.syncUpstreamModelsPreview = false })
  }) as AdminAccountsRepository['syncUpstreamModelsPreview']

  const syncFromCrs: AdminAccountsRepository['syncFromCrs'] = ((...args: unknown[]) => {
    loading.syncFromCrs = true
    errors.syncFromCrs = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.syncFromCrs as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.syncFromCrs = error; throw error })
      .finally(() => { loading.syncFromCrs = false })
  }) as AdminAccountsRepository['syncFromCrs']

  const importData: AdminAccountsRepository['importData'] = ((...args: unknown[]) => {
    loading.importData = true
    errors.importData = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.importData as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.importData = error; throw error })
      .finally(() => { loading.importData = false })
  }) as AdminAccountsRepository['importData']

  const importCodexSession: AdminAccountsRepository['importCodexSession'] = ((...args: unknown[]) => {
    loading.importCodexSession = true
    errors.importCodexSession = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.importCodexSession as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.importCodexSession = error; throw error })
      .finally(() => { loading.importCodexSession = false })
  }) as AdminAccountsRepository['importCodexSession']

  const createOpenAICodexPAT: AdminAccountsRepository['createOpenAICodexPAT'] = ((...args: unknown[]) => {
    loading.createOpenAICodexPAT = true
    errors.createOpenAICodexPAT = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.createOpenAICodexPAT as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createOpenAICodexPAT = error; throw error })
      .finally(() => { loading.createOpenAICodexPAT = false })
  }) as AdminAccountsRepository['createOpenAICodexPAT']

  const refreshOpenAIToken: AdminAccountsRepository['refreshOpenAIToken'] = ((...args: unknown[]) => {
    loading.refreshOpenAIToken = true
    errors.refreshOpenAIToken = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.refreshOpenAIToken as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.refreshOpenAIToken = error; throw error })
      .finally(() => { loading.refreshOpenAIToken = false })
  }) as AdminAccountsRepository['refreshOpenAIToken']

  const revertProxyFallback: AdminAccountsRepository['revertProxyFallback'] = ((...args: unknown[]) => {
    loading.revertProxyFallback = true
    errors.revertProxyFallback = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.revertProxyFallback as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.revertProxyFallback = error; throw error })
      .finally(() => { loading.revertProxyFallback = false })
  }) as AdminAccountsRepository['revertProxyFallback']

  const batchClearError: AdminAccountsRepository['batchClearError'] = ((...args: unknown[]) => {
    loading.batchClearError = true
    errors.batchClearError = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.batchClearError as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchClearError = error; throw error })
      .finally(() => { loading.batchClearError = false })
  }) as AdminAccountsRepository['batchClearError']

  const batchRefresh: AdminAccountsRepository['batchRefresh'] = ((...args: unknown[]) => {
    loading.batchRefresh = true
    errors.batchRefresh = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.batchRefresh as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchRefresh = error; throw error })
      .finally(() => { loading.batchRefresh = false })
  }) as AdminAccountsRepository['batchRefresh']

  const setPrivacy: AdminAccountsRepository['setPrivacy'] = ((...args: unknown[]) => {
    loading.setPrivacy = true
    errors.setPrivacy = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.setPrivacy as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.setPrivacy = error; throw error })
      .finally(() => { loading.setPrivacy = false })
  }) as AdminAccountsRepository['setPrivacy']

  const resetOpenAIQuota: AdminAccountsRepository['resetOpenAIQuota'] = ((...args: unknown[]) => {
    loading.resetOpenAIQuota = true
    errors.resetOpenAIQuota = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.resetOpenAIQuota as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.resetOpenAIQuota = error; throw error })
      .finally(() => { loading.resetOpenAIQuota = false })
  }) as AdminAccountsRepository['resetOpenAIQuota']

  const createSparkShadow: AdminAccountsRepository['createSparkShadow'] = ((...args: unknown[]) => {
    loading.createSparkShadow = true
    errors.createSparkShadow = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.createSparkShadow as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createSparkShadow = error; throw error })
      .finally(() => { loading.createSparkShadow = false })
  }) as AdminAccountsRepository['createSparkShadow']

  const updateUpstreamBillingProbeSettings: AdminAccountsRepository['updateUpstreamBillingProbeSettings'] = ((...args: unknown[]) => {
    loading.updateUpstreamBillingProbeSettings = true
    errors.updateUpstreamBillingProbeSettings = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.updateUpstreamBillingProbeSettings as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateUpstreamBillingProbeSettings = error; throw error })
      .finally(() => { loading.updateUpstreamBillingProbeSettings = false })
  }) as AdminAccountsRepository['updateUpstreamBillingProbeSettings']

  const setUpstreamBillingProbeEnabled: AdminAccountsRepository['setUpstreamBillingProbeEnabled'] = ((...args: unknown[]) => {
    loading.setUpstreamBillingProbeEnabled = true
    errors.setUpstreamBillingProbeEnabled = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.setUpstreamBillingProbeEnabled as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.setUpstreamBillingProbeEnabled = error; throw error })
      .finally(() => { loading.setUpstreamBillingProbeEnabled = false })
  }) as AdminAccountsRepository['setUpstreamBillingProbeEnabled']

  const antigravity_generateAuthUrl: AntigravityRepository['generateAuthUrl'] = ((...args: unknown[]) => {
    loading.antigravity_generateAuthUrl = true
    errors.antigravity_generateAuthUrl = null
    return Promise.resolve()
      .then(() => (antigravityRepo.generateAuthUrl as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.antigravity_generateAuthUrl = error; throw error })
      .finally(() => { loading.antigravity_generateAuthUrl = false })
  }) as AntigravityRepository['generateAuthUrl']

  const antigravity_exchangeCode: AntigravityRepository['exchangeCode'] = ((...args: unknown[]) => {
    loading.antigravity_exchangeCode = true
    errors.antigravity_exchangeCode = null
    return Promise.resolve()
      .then(() => (antigravityRepo.exchangeCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.antigravity_exchangeCode = error; throw error })
      .finally(() => { loading.antigravity_exchangeCode = false })
  }) as AntigravityRepository['exchangeCode']

  const refreshAntigravityToken: AntigravityRepository['refreshAntigravityToken'] = ((...args: unknown[]) => {
    loading.refreshAntigravityToken = true
    errors.refreshAntigravityToken = null
    return Promise.resolve()
      .then(() => (antigravityRepo.refreshAntigravityToken as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.refreshAntigravityToken = error; throw error })
      .finally(() => { loading.refreshAntigravityToken = false })
  }) as AntigravityRepository['refreshAntigravityToken']

  const gemini_generateAuthUrl: GeminiRepository['generateAuthUrl'] = ((...args: unknown[]) => {
    loading.gemini_generateAuthUrl = true
    errors.gemini_generateAuthUrl = null
    return Promise.resolve()
      .then(() => (geminiRepo.generateAuthUrl as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.gemini_generateAuthUrl = error; throw error })
      .finally(() => { loading.gemini_generateAuthUrl = false })
  }) as GeminiRepository['generateAuthUrl']

  const gemini_exchangeCode: GeminiRepository['exchangeCode'] = ((...args: unknown[]) => {
    loading.gemini_exchangeCode = true
    errors.gemini_exchangeCode = null
    return Promise.resolve()
      .then(() => (geminiRepo.exchangeCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.gemini_exchangeCode = error; throw error })
      .finally(() => { loading.gemini_exchangeCode = false })
  }) as GeminiRepository['exchangeCode']

  const grok_generateAuthUrl: GrokRepository['generateAuthUrl'] = ((...args: unknown[]) => {
    loading.grok_generateAuthUrl = true
    errors.grok_generateAuthUrl = null
    return Promise.resolve()
      .then(() => (grokRepo.generateAuthUrl as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.grok_generateAuthUrl = error; throw error })
      .finally(() => { loading.grok_generateAuthUrl = false })
  }) as GrokRepository['generateAuthUrl']

  const grok_exchangeCode: GrokRepository['exchangeCode'] = ((...args: unknown[]) => {
    loading.grok_exchangeCode = true
    errors.grok_exchangeCode = null
    return Promise.resolve()
      .then(() => (grokRepo.exchangeCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.grok_exchangeCode = error; throw error })
      .finally(() => { loading.grok_exchangeCode = false })
  }) as GrokRepository['exchangeCode']

  const refreshGrokToken: GrokRepository['refreshGrokToken'] = ((...args: unknown[]) => {
    loading.refreshGrokToken = true
    errors.refreshGrokToken = null
    return Promise.resolve()
      .then(() => (grokRepo.refreshGrokToken as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.refreshGrokToken = error; throw error })
      .finally(() => { loading.refreshGrokToken = false })
  }) as GrokRepository['refreshGrokToken']

  const resetQuota: GrokRepository['resetQuota'] = ((...args: unknown[]) => {
    loading.resetQuota = true
    errors.resetQuota = null
    return Promise.resolve()
      .then(() => (grokRepo.resetQuota as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.resetQuota = error; throw error })
      .finally(() => { loading.resetQuota = false })
  }) as GrokRepository['resetQuota']

  const createFromSSO: GrokRepository['createFromSSO'] = ((...args: unknown[]) => {
    loading.createFromSSO = true
    errors.createFromSSO = null
    return Promise.resolve()
      .then(() => (grokRepo.createFromSSO as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createFromSSO = error; throw error })
      .finally(() => { loading.createFromSSO = false })
  }) as GrokRepository['createFromSSO']

  const scheduledTests_create: ScheduledTestsRepository['create'] = ((...args: unknown[]) => {
    loading.scheduledTests_create = true
    errors.scheduledTests_create = null
    return Promise.resolve()
      .then(() => (scheduledTestsRepo.create as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.scheduledTests_create = error; throw error })
      .finally(() => { loading.scheduledTests_create = false })
  }) as ScheduledTestsRepository['create']

  const scheduledTests_update: ScheduledTestsRepository['update'] = ((...args: unknown[]) => {
    loading.scheduledTests_update = true
    errors.scheduledTests_update = null
    return Promise.resolve()
      .then(() => (scheduledTestsRepo.update as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.scheduledTests_update = error; throw error })
      .finally(() => { loading.scheduledTests_update = false })
  }) as ScheduledTestsRepository['update']

  const deletePlan: ScheduledTestsRepository['deletePlan'] = ((...args: unknown[]) => {
    loading.deletePlan = true
    errors.deletePlan = null
    return Promise.resolve()
      .then(() => (scheduledTestsRepo.deletePlan as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deletePlan = error; throw error })
      .finally(() => { loading.deletePlan = false })
  }) as ScheduledTestsRepository['deletePlan']

    return { loading, errors, create, duplicate, update, deleteAccount, toggleStatus, testAccount, refreshCredentials, applyOAuthCredentials, clearError, clearRateLimit, recoverState, resetAccountQuota, resetTempUnschedulable, generateAuthUrl, exchangeCode, batchCreate, batchUpdateCredentials, bulkUpdate, setSchedulable, syncUpstreamModels, syncUpstreamModelsPreview, syncFromCrs, importData, importCodexSession, createOpenAICodexPAT, refreshOpenAIToken, revertProxyFallback, batchClearError, batchRefresh, setPrivacy, resetOpenAIQuota, createSparkShadow, updateUpstreamBillingProbeSettings, setUpstreamBillingProbeEnabled, antigravity_generateAuthUrl, antigravity_exchangeCode, refreshAntigravityToken, gemini_generateAuthUrl, gemini_exchangeCode, grok_generateAuthUrl, grok_exchangeCode, refreshGrokToken, resetQuota, createFromSSO, scheduledTests_create, scheduledTests_update, deletePlan }
  })
}

export const useAdminAccountsActionStore = createAdminAccountsActionStore()
