/**
 * AdminAccountsQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminAccountsQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminAccountsRepository } from '@/features/admin-accounts/domain/repositories/adminAccountsRepository'
import type { GeminiRepository } from '@/features/admin-accounts/domain/repositories/geminiRepository'
import type { GrokRepository } from '@/features/admin-accounts/domain/repositories/grokRepository'
import type { ScheduledTestsRepository } from '@/features/admin-accounts/domain/repositories/scheduledTestsRepository'
import { adminAccountsRepository as default_adminAccounts_repo } from '@/features/admin-accounts/data/repositories/adminAccountsRepositoryImpl'
import { geminiRepository as default_gemini_repo } from '@/features/admin-accounts/data/repositories/geminiRepositoryImpl'
import { grokRepository as default_grok_repo } from '@/features/admin-accounts/data/repositories/grokRepositoryImpl'
import { scheduledTestsRepository as default_scheduledTests_repo } from '@/features/admin-accounts/data/repositories/scheduledTestsRepositoryImpl'

export function createAdminAccountsQueryStore(adminAccountsRepo: AdminAccountsRepository = default_adminAccounts_repo, geminiRepo: GeminiRepository = default_gemini_repo, grokRepo: GrokRepository = default_grok_repo, scheduledTestsRepo: ScheduledTestsRepository = default_scheduledTests_repo) {
  return defineStore('adminAccounts/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, listWithEtag: false, getById: false, getBatchSummaries: false, checkMixedChannelRisk: false, getStats: false, getUsage: false, getTempUnschedulableStatus: false, getTodayStats: false, getBatchTodayStats: false, getAvailableModels: false, previewFromCrs: false, exportData: false, getAntigravityDefaultModelMapping: false, queryOpenAIQuota: false, getUpstreamBillingProbeSettings: false, probeUpstreamBilling: false, probeUpstreamBillingBatch: false, getCapabilities: false, queryQuota: false, listByAccount: false, listResults: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, listWithEtag: null as unknown, getById: null as unknown, getBatchSummaries: null as unknown, checkMixedChannelRisk: null as unknown, getStats: null as unknown, getUsage: null as unknown, getTempUnschedulableStatus: null as unknown, getTodayStats: null as unknown, getBatchTodayStats: null as unknown, getAvailableModels: null as unknown, previewFromCrs: null as unknown, exportData: null as unknown, getAntigravityDefaultModelMapping: null as unknown, queryOpenAIQuota: null as unknown, getUpstreamBillingProbeSettings: null as unknown, probeUpstreamBilling: null as unknown, probeUpstreamBillingBatch: null as unknown, getCapabilities: null as unknown, queryQuota: null as unknown, listByAccount: null as unknown, listResults: null as unknown })

  const list: AdminAccountsRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as AdminAccountsRepository['list']

  const listWithEtag: AdminAccountsRepository['listWithEtag'] = ((...args: unknown[]) => {
    loading.listWithEtag = true
    errors.listWithEtag = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.listWithEtag as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listWithEtag = error; throw error })
      .finally(() => { loading.listWithEtag = false })
  }) as AdminAccountsRepository['listWithEtag']

  const getById: AdminAccountsRepository['getById'] = ((...args: unknown[]) => {
    loading.getById = true
    errors.getById = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.getById as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getById = error; throw error })
      .finally(() => { loading.getById = false })
  }) as AdminAccountsRepository['getById']

  const getBatchSummaries: AdminAccountsRepository['getBatchSummaries'] = ((...args: unknown[]) => {
    loading.getBatchSummaries = true
    errors.getBatchSummaries = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.getBatchSummaries as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getBatchSummaries = error; throw error })
      .finally(() => { loading.getBatchSummaries = false })
  }) as AdminAccountsRepository['getBatchSummaries']

  const checkMixedChannelRisk: AdminAccountsRepository['checkMixedChannelRisk'] = ((...args: unknown[]) => {
    loading.checkMixedChannelRisk = true
    errors.checkMixedChannelRisk = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.checkMixedChannelRisk as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.checkMixedChannelRisk = error; throw error })
      .finally(() => { loading.checkMixedChannelRisk = false })
  }) as AdminAccountsRepository['checkMixedChannelRisk']

  const getStats: AdminAccountsRepository['getStats'] = ((...args: unknown[]) => {
    loading.getStats = true
    errors.getStats = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.getStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getStats = error; throw error })
      .finally(() => { loading.getStats = false })
  }) as AdminAccountsRepository['getStats']

  const getUsage: AdminAccountsRepository['getUsage'] = ((...args: unknown[]) => {
    loading.getUsage = true
    errors.getUsage = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.getUsage as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUsage = error; throw error })
      .finally(() => { loading.getUsage = false })
  }) as AdminAccountsRepository['getUsage']

  const getTempUnschedulableStatus: AdminAccountsRepository['getTempUnschedulableStatus'] = ((...args: unknown[]) => {
    loading.getTempUnschedulableStatus = true
    errors.getTempUnschedulableStatus = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.getTempUnschedulableStatus as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getTempUnschedulableStatus = error; throw error })
      .finally(() => { loading.getTempUnschedulableStatus = false })
  }) as AdminAccountsRepository['getTempUnschedulableStatus']

  const getTodayStats: AdminAccountsRepository['getTodayStats'] = ((...args: unknown[]) => {
    loading.getTodayStats = true
    errors.getTodayStats = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.getTodayStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getTodayStats = error; throw error })
      .finally(() => { loading.getTodayStats = false })
  }) as AdminAccountsRepository['getTodayStats']

  const getBatchTodayStats: AdminAccountsRepository['getBatchTodayStats'] = ((...args: unknown[]) => {
    loading.getBatchTodayStats = true
    errors.getBatchTodayStats = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.getBatchTodayStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getBatchTodayStats = error; throw error })
      .finally(() => { loading.getBatchTodayStats = false })
  }) as AdminAccountsRepository['getBatchTodayStats']

  const getAvailableModels: AdminAccountsRepository['getAvailableModels'] = ((...args: unknown[]) => {
    loading.getAvailableModels = true
    errors.getAvailableModels = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.getAvailableModels as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAvailableModels = error; throw error })
      .finally(() => { loading.getAvailableModels = false })
  }) as AdminAccountsRepository['getAvailableModels']

  const previewFromCrs: AdminAccountsRepository['previewFromCrs'] = ((...args: unknown[]) => {
    loading.previewFromCrs = true
    errors.previewFromCrs = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.previewFromCrs as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.previewFromCrs = error; throw error })
      .finally(() => { loading.previewFromCrs = false })
  }) as AdminAccountsRepository['previewFromCrs']

  const exportData: AdminAccountsRepository['exportData'] = ((...args: unknown[]) => {
    loading.exportData = true
    errors.exportData = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.exportData as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.exportData = error; throw error })
      .finally(() => { loading.exportData = false })
  }) as AdminAccountsRepository['exportData']

  const getAntigravityDefaultModelMapping: AdminAccountsRepository['getAntigravityDefaultModelMapping'] = ((...args: unknown[]) => {
    loading.getAntigravityDefaultModelMapping = true
    errors.getAntigravityDefaultModelMapping = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.getAntigravityDefaultModelMapping as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAntigravityDefaultModelMapping = error; throw error })
      .finally(() => { loading.getAntigravityDefaultModelMapping = false })
  }) as AdminAccountsRepository['getAntigravityDefaultModelMapping']

  const queryOpenAIQuota: AdminAccountsRepository['queryOpenAIQuota'] = ((...args: unknown[]) => {
    loading.queryOpenAIQuota = true
    errors.queryOpenAIQuota = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.queryOpenAIQuota as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.queryOpenAIQuota = error; throw error })
      .finally(() => { loading.queryOpenAIQuota = false })
  }) as AdminAccountsRepository['queryOpenAIQuota']

  const getUpstreamBillingProbeSettings: AdminAccountsRepository['getUpstreamBillingProbeSettings'] = ((...args: unknown[]) => {
    loading.getUpstreamBillingProbeSettings = true
    errors.getUpstreamBillingProbeSettings = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.getUpstreamBillingProbeSettings as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUpstreamBillingProbeSettings = error; throw error })
      .finally(() => { loading.getUpstreamBillingProbeSettings = false })
  }) as AdminAccountsRepository['getUpstreamBillingProbeSettings']

  const probeUpstreamBilling: AdminAccountsRepository['probeUpstreamBilling'] = ((...args: unknown[]) => {
    loading.probeUpstreamBilling = true
    errors.probeUpstreamBilling = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.probeUpstreamBilling as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.probeUpstreamBilling = error; throw error })
      .finally(() => { loading.probeUpstreamBilling = false })
  }) as AdminAccountsRepository['probeUpstreamBilling']

  const probeUpstreamBillingBatch: AdminAccountsRepository['probeUpstreamBillingBatch'] = ((...args: unknown[]) => {
    loading.probeUpstreamBillingBatch = true
    errors.probeUpstreamBillingBatch = null
    return Promise.resolve()
      .then(() => (adminAccountsRepo.probeUpstreamBillingBatch as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.probeUpstreamBillingBatch = error; throw error })
      .finally(() => { loading.probeUpstreamBillingBatch = false })
  }) as AdminAccountsRepository['probeUpstreamBillingBatch']

  const getCapabilities: GeminiRepository['getCapabilities'] = ((...args: unknown[]) => {
    loading.getCapabilities = true
    errors.getCapabilities = null
    return Promise.resolve()
      .then(() => (geminiRepo.getCapabilities as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getCapabilities = error; throw error })
      .finally(() => { loading.getCapabilities = false })
  }) as GeminiRepository['getCapabilities']

  const queryQuota: GrokRepository['queryQuota'] = ((...args: unknown[]) => {
    loading.queryQuota = true
    errors.queryQuota = null
    return Promise.resolve()
      .then(() => (grokRepo.queryQuota as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.queryQuota = error; throw error })
      .finally(() => { loading.queryQuota = false })
  }) as GrokRepository['queryQuota']

  const listByAccount: ScheduledTestsRepository['listByAccount'] = ((...args: unknown[]) => {
    loading.listByAccount = true
    errors.listByAccount = null
    return Promise.resolve()
      .then(() => (scheduledTestsRepo.listByAccount as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listByAccount = error; throw error })
      .finally(() => { loading.listByAccount = false })
  }) as ScheduledTestsRepository['listByAccount']

  const listResults: ScheduledTestsRepository['listResults'] = ((...args: unknown[]) => {
    loading.listResults = true
    errors.listResults = null
    return Promise.resolve()
      .then(() => (scheduledTestsRepo.listResults as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listResults = error; throw error })
      .finally(() => { loading.listResults = false })
  }) as ScheduledTestsRepository['listResults']

    return { loading, errors, list, listWithEtag, getById, getBatchSummaries, checkMixedChannelRisk, getStats, getUsage, getTempUnschedulableStatus, getTodayStats, getBatchTodayStats, getAvailableModels, previewFromCrs, exportData, getAntigravityDefaultModelMapping, queryOpenAIQuota, getUpstreamBillingProbeSettings, probeUpstreamBilling, probeUpstreamBillingBatch, getCapabilities, queryQuota, listByAccount, listResults }
  })
}

export const useAdminAccountsQueryStore = createAdminAccountsQueryStore()
