/**
 * AdminChannelMonitorActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminChannelMonitorActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminChannelMonitorRepository } from '@/features/admin-channel-monitor/domain/repositories/adminChannelMonitorRepository'
import type { AdminChannelMonitorTemplateRepository } from '@/features/admin-channel-monitor/domain/repositories/adminChannelMonitorTemplateRepository'
import { adminChannelMonitorRepository as default_adminChannelMonitor_repo } from '@/features/admin-channel-monitor/data/repositories/adminChannelMonitorRepositoryImpl'
import { adminChannelMonitorTemplateRepository as default_adminChannelMonitorTemplate_repo } from '@/features/admin-channel-monitor/data/repositories/adminChannelMonitorTemplateRepositoryImpl'

export function createAdminChannelMonitorActionStore(adminChannelMonitorRepo: AdminChannelMonitorRepository = default_adminChannelMonitor_repo, adminChannelMonitorTemplateRepo: AdminChannelMonitorTemplateRepository = default_adminChannelMonitorTemplate_repo) {
  return defineStore('adminChannelMonitor/action', () => {
    const loading = reactive<Record<string, boolean>>({ create: false, duplicate: false, update: false, del: false, runNow: false, adminChannelMonitorTemplate_create: false, adminChannelMonitorTemplate_update: false, adminChannelMonitorTemplate_del: false, apply: false })
    const errors = reactive<Record<string, unknown>>({ create: null as unknown, duplicate: null as unknown, update: null as unknown, del: null as unknown, runNow: null as unknown, adminChannelMonitorTemplate_create: null as unknown, adminChannelMonitorTemplate_update: null as unknown, adminChannelMonitorTemplate_del: null as unknown, apply: null as unknown })

  const create: AdminChannelMonitorRepository['create'] = ((...args: unknown[]) => {
    loading.create = true
    errors.create = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorRepo.create as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.create = error; throw error })
      .finally(() => { loading.create = false })
  }) as AdminChannelMonitorRepository['create']

  const duplicate: AdminChannelMonitorRepository['duplicate'] = ((...args: unknown[]) => {
    loading.duplicate = true
    errors.duplicate = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorRepo.duplicate as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.duplicate = error; throw error })
      .finally(() => { loading.duplicate = false })
  }) as AdminChannelMonitorRepository['duplicate']

  const update: AdminChannelMonitorRepository['update'] = ((...args: unknown[]) => {
    loading.update = true
    errors.update = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorRepo.update as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.update = error; throw error })
      .finally(() => { loading.update = false })
  }) as AdminChannelMonitorRepository['update']

  const del: AdminChannelMonitorRepository['del'] = ((...args: unknown[]) => {
    loading.del = true
    errors.del = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorRepo.del as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.del = error; throw error })
      .finally(() => { loading.del = false })
  }) as AdminChannelMonitorRepository['del']

  const runNow: AdminChannelMonitorRepository['runNow'] = ((...args: unknown[]) => {
    loading.runNow = true
    errors.runNow = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorRepo.runNow as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.runNow = error; throw error })
      .finally(() => { loading.runNow = false })
  }) as AdminChannelMonitorRepository['runNow']

  const adminChannelMonitorTemplate_create: AdminChannelMonitorTemplateRepository['create'] = ((...args: unknown[]) => {
    loading.adminChannelMonitorTemplate_create = true
    errors.adminChannelMonitorTemplate_create = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorTemplateRepo.create as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.adminChannelMonitorTemplate_create = error; throw error })
      .finally(() => { loading.adminChannelMonitorTemplate_create = false })
  }) as AdminChannelMonitorTemplateRepository['create']

  const adminChannelMonitorTemplate_update: AdminChannelMonitorTemplateRepository['update'] = ((...args: unknown[]) => {
    loading.adminChannelMonitorTemplate_update = true
    errors.adminChannelMonitorTemplate_update = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorTemplateRepo.update as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.adminChannelMonitorTemplate_update = error; throw error })
      .finally(() => { loading.adminChannelMonitorTemplate_update = false })
  }) as AdminChannelMonitorTemplateRepository['update']

  const adminChannelMonitorTemplate_del: AdminChannelMonitorTemplateRepository['del'] = ((...args: unknown[]) => {
    loading.adminChannelMonitorTemplate_del = true
    errors.adminChannelMonitorTemplate_del = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorTemplateRepo.del as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.adminChannelMonitorTemplate_del = error; throw error })
      .finally(() => { loading.adminChannelMonitorTemplate_del = false })
  }) as AdminChannelMonitorTemplateRepository['del']

  const apply: AdminChannelMonitorTemplateRepository['apply'] = ((...args: unknown[]) => {
    loading.apply = true
    errors.apply = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorTemplateRepo.apply as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.apply = error; throw error })
      .finally(() => { loading.apply = false })
  }) as AdminChannelMonitorTemplateRepository['apply']

    return { loading, errors, create, duplicate, update, del, runNow, adminChannelMonitorTemplate_create, adminChannelMonitorTemplate_update, adminChannelMonitorTemplate_del, apply }
  })
}

export const useAdminChannelMonitorActionStore = createAdminChannelMonitorActionStore()
