/**
 * AdminChannelMonitorQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminChannelMonitorQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminChannelMonitorRepository } from '@/features/admin-channel-monitor/domain/repositories/adminChannelMonitorRepository'
import type { AdminChannelMonitorTemplateRepository } from '@/features/admin-channel-monitor/domain/repositories/adminChannelMonitorTemplateRepository'
import { adminChannelMonitorRepository as default_adminChannelMonitor_repo } from '@/features/admin-channel-monitor/data/repositories/adminChannelMonitorRepositoryImpl'
import { adminChannelMonitorTemplateRepository as default_adminChannelMonitorTemplate_repo } from '@/features/admin-channel-monitor/data/repositories/adminChannelMonitorTemplateRepositoryImpl'

export function createAdminChannelMonitorQueryStore(adminChannelMonitorRepo: AdminChannelMonitorRepository = default_adminChannelMonitor_repo, adminChannelMonitorTemplateRepo: AdminChannelMonitorTemplateRepository = default_adminChannelMonitorTemplate_repo) {
  return defineStore('adminChannelMonitor/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, get: false, listHistory: false, adminChannelMonitorTemplate_list: false, adminChannelMonitorTemplate_get: false, listAssociatedMonitors: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, get: null as unknown, listHistory: null as unknown, adminChannelMonitorTemplate_list: null as unknown, adminChannelMonitorTemplate_get: null as unknown, listAssociatedMonitors: null as unknown })

  const list: AdminChannelMonitorRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as AdminChannelMonitorRepository['list']

  const get: AdminChannelMonitorRepository['get'] = ((...args: unknown[]) => {
    loading.get = true
    errors.get = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorRepo.get as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.get = error; throw error })
      .finally(() => { loading.get = false })
  }) as AdminChannelMonitorRepository['get']

  const listHistory: AdminChannelMonitorRepository['listHistory'] = ((...args: unknown[]) => {
    loading.listHistory = true
    errors.listHistory = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorRepo.listHistory as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listHistory = error; throw error })
      .finally(() => { loading.listHistory = false })
  }) as AdminChannelMonitorRepository['listHistory']

  const adminChannelMonitorTemplate_list: AdminChannelMonitorTemplateRepository['list'] = ((...args: unknown[]) => {
    loading.adminChannelMonitorTemplate_list = true
    errors.adminChannelMonitorTemplate_list = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorTemplateRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.adminChannelMonitorTemplate_list = error; throw error })
      .finally(() => { loading.adminChannelMonitorTemplate_list = false })
  }) as AdminChannelMonitorTemplateRepository['list']

  const adminChannelMonitorTemplate_get: AdminChannelMonitorTemplateRepository['get'] = ((...args: unknown[]) => {
    loading.adminChannelMonitorTemplate_get = true
    errors.adminChannelMonitorTemplate_get = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorTemplateRepo.get as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.adminChannelMonitorTemplate_get = error; throw error })
      .finally(() => { loading.adminChannelMonitorTemplate_get = false })
  }) as AdminChannelMonitorTemplateRepository['get']

  const listAssociatedMonitors: AdminChannelMonitorTemplateRepository['listAssociatedMonitors'] = ((...args: unknown[]) => {
    loading.listAssociatedMonitors = true
    errors.listAssociatedMonitors = null
    return Promise.resolve()
      .then(() => (adminChannelMonitorTemplateRepo.listAssociatedMonitors as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listAssociatedMonitors = error; throw error })
      .finally(() => { loading.listAssociatedMonitors = false })
  }) as AdminChannelMonitorTemplateRepository['listAssociatedMonitors']

    return { loading, errors, list, get, listHistory, adminChannelMonitorTemplate_list, adminChannelMonitorTemplate_get, listAssociatedMonitors }
  })
}

export const useAdminChannelMonitorQueryStore = createAdminChannelMonitorQueryStore()
