/**
 * ProfileQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createProfileQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { ProfileRepository } from '@/features/profile/domain/repositories/profileRepository'
import type { TotpRepository } from '@/features/profile/domain/repositories/totpRepository'
import { profileRepository as default_profile_repo } from '@/features/profile/data/repositories/profileRepositoryImpl'
import { totpRepository as default_totp_repo } from '@/features/profile/data/repositories/totpRepositoryImpl'

export function createProfileQueryStore(profileRepo: ProfileRepository = default_profile_repo, totpRepo: TotpRepository = default_totp_repo) {
  return defineStore('profile/query', () => {
    const loading = reactive<Record<string, boolean>>({ getProfile: false, getAffiliateDetail: false, getMyPlatformQuotas: false, getStatus: false, getVerificationMethod: false })
    const errors = reactive<Record<string, unknown>>({ getProfile: null as unknown, getAffiliateDetail: null as unknown, getMyPlatformQuotas: null as unknown, getStatus: null as unknown, getVerificationMethod: null as unknown })

  const getProfile: ProfileRepository['getProfile'] = ((...args: unknown[]) => {
    loading.getProfile = true
    errors.getProfile = null
    return Promise.resolve()
      .then(() => (profileRepo.getProfile as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getProfile = error; throw error })
      .finally(() => { loading.getProfile = false })
  }) as ProfileRepository['getProfile']

  const getAffiliateDetail: ProfileRepository['getAffiliateDetail'] = ((...args: unknown[]) => {
    loading.getAffiliateDetail = true
    errors.getAffiliateDetail = null
    return Promise.resolve()
      .then(() => (profileRepo.getAffiliateDetail as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAffiliateDetail = error; throw error })
      .finally(() => { loading.getAffiliateDetail = false })
  }) as ProfileRepository['getAffiliateDetail']

  const getMyPlatformQuotas: ProfileRepository['getMyPlatformQuotas'] = ((...args: unknown[]) => {
    loading.getMyPlatformQuotas = true
    errors.getMyPlatformQuotas = null
    return Promise.resolve()
      .then(() => (profileRepo.getMyPlatformQuotas as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getMyPlatformQuotas = error; throw error })
      .finally(() => { loading.getMyPlatformQuotas = false })
  }) as ProfileRepository['getMyPlatformQuotas']

  const getStatus: TotpRepository['getStatus'] = ((...args: unknown[]) => {
    loading.getStatus = true
    errors.getStatus = null
    return Promise.resolve()
      .then(() => (totpRepo.getStatus as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getStatus = error; throw error })
      .finally(() => { loading.getStatus = false })
  }) as TotpRepository['getStatus']

  const getVerificationMethod: TotpRepository['getVerificationMethod'] = ((...args: unknown[]) => {
    loading.getVerificationMethod = true
    errors.getVerificationMethod = null
    return Promise.resolve()
      .then(() => (totpRepo.getVerificationMethod as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getVerificationMethod = error; throw error })
      .finally(() => { loading.getVerificationMethod = false })
  }) as TotpRepository['getVerificationMethod']

    return { loading, errors, getProfile, getAffiliateDetail, getMyPlatformQuotas, getStatus, getVerificationMethod }
  })
}

export const useProfileQueryStore = createProfileQueryStore()
