/**
 * ProfileActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createProfileActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { ProfileRepository } from '@/features/profile/domain/repositories/profileRepository'
import type { TotpRepository } from '@/features/profile/domain/repositories/totpRepository'
import { profileRepository as default_profile_repo } from '@/features/profile/data/repositories/profileRepositoryImpl'
import { totpRepository as default_totp_repo } from '@/features/profile/data/repositories/totpRepositoryImpl'

export function createProfileActionStore(profileRepo: ProfileRepository = default_profile_repo, totpRepo: TotpRepository = default_totp_repo) {
  return defineStore('profile/action', () => {
    const loading = reactive<Record<string, boolean>>({ updateProfile: false, changePassword: false, sendNotifyEmailCode: false, verifyNotifyEmail: false, removeNotifyEmail: false, toggleNotifyEmail: false, sendEmailBindingCode: false, bindEmailIdentity: false, unbindAuthIdentity: false, startOAuthBinding: false, transferAffiliateQuota: false, sendVerifyCode: false, initiateSetup: false, enable: false, disable: false, stepUp: false })
    const errors = reactive<Record<string, unknown>>({ updateProfile: null as unknown, changePassword: null as unknown, sendNotifyEmailCode: null as unknown, verifyNotifyEmail: null as unknown, removeNotifyEmail: null as unknown, toggleNotifyEmail: null as unknown, sendEmailBindingCode: null as unknown, bindEmailIdentity: null as unknown, unbindAuthIdentity: null as unknown, startOAuthBinding: null as unknown, transferAffiliateQuota: null as unknown, sendVerifyCode: null as unknown, initiateSetup: null as unknown, enable: null as unknown, disable: null as unknown, stepUp: null as unknown })

  const updateProfile: ProfileRepository['updateProfile'] = ((...args: unknown[]) => {
    loading.updateProfile = true
    errors.updateProfile = null
    return Promise.resolve()
      .then(() => (profileRepo.updateProfile as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateProfile = error; throw error })
      .finally(() => { loading.updateProfile = false })
  }) as ProfileRepository['updateProfile']

  const changePassword: ProfileRepository['changePassword'] = ((...args: unknown[]) => {
    loading.changePassword = true
    errors.changePassword = null
    return Promise.resolve()
      .then(() => (profileRepo.changePassword as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.changePassword = error; throw error })
      .finally(() => { loading.changePassword = false })
  }) as ProfileRepository['changePassword']

  const sendNotifyEmailCode: ProfileRepository['sendNotifyEmailCode'] = ((...args: unknown[]) => {
    loading.sendNotifyEmailCode = true
    errors.sendNotifyEmailCode = null
    return Promise.resolve()
      .then(() => (profileRepo.sendNotifyEmailCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.sendNotifyEmailCode = error; throw error })
      .finally(() => { loading.sendNotifyEmailCode = false })
  }) as ProfileRepository['sendNotifyEmailCode']

  const verifyNotifyEmail: ProfileRepository['verifyNotifyEmail'] = ((...args: unknown[]) => {
    loading.verifyNotifyEmail = true
    errors.verifyNotifyEmail = null
    return Promise.resolve()
      .then(() => (profileRepo.verifyNotifyEmail as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.verifyNotifyEmail = error; throw error })
      .finally(() => { loading.verifyNotifyEmail = false })
  }) as ProfileRepository['verifyNotifyEmail']

  const removeNotifyEmail: ProfileRepository['removeNotifyEmail'] = ((...args: unknown[]) => {
    loading.removeNotifyEmail = true
    errors.removeNotifyEmail = null
    return Promise.resolve()
      .then(() => (profileRepo.removeNotifyEmail as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.removeNotifyEmail = error; throw error })
      .finally(() => { loading.removeNotifyEmail = false })
  }) as ProfileRepository['removeNotifyEmail']

  const toggleNotifyEmail: ProfileRepository['toggleNotifyEmail'] = ((...args: unknown[]) => {
    loading.toggleNotifyEmail = true
    errors.toggleNotifyEmail = null
    return Promise.resolve()
      .then(() => (profileRepo.toggleNotifyEmail as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.toggleNotifyEmail = error; throw error })
      .finally(() => { loading.toggleNotifyEmail = false })
  }) as ProfileRepository['toggleNotifyEmail']

  const sendEmailBindingCode: ProfileRepository['sendEmailBindingCode'] = ((...args: unknown[]) => {
    loading.sendEmailBindingCode = true
    errors.sendEmailBindingCode = null
    return Promise.resolve()
      .then(() => (profileRepo.sendEmailBindingCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.sendEmailBindingCode = error; throw error })
      .finally(() => { loading.sendEmailBindingCode = false })
  }) as ProfileRepository['sendEmailBindingCode']

  const bindEmailIdentity: ProfileRepository['bindEmailIdentity'] = ((...args: unknown[]) => {
    loading.bindEmailIdentity = true
    errors.bindEmailIdentity = null
    return Promise.resolve()
      .then(() => (profileRepo.bindEmailIdentity as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.bindEmailIdentity = error; throw error })
      .finally(() => { loading.bindEmailIdentity = false })
  }) as ProfileRepository['bindEmailIdentity']

  const unbindAuthIdentity: ProfileRepository['unbindAuthIdentity'] = ((...args: unknown[]) => {
    loading.unbindAuthIdentity = true
    errors.unbindAuthIdentity = null
    return Promise.resolve()
      .then(() => (profileRepo.unbindAuthIdentity as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.unbindAuthIdentity = error; throw error })
      .finally(() => { loading.unbindAuthIdentity = false })
  }) as ProfileRepository['unbindAuthIdentity']

  const startOAuthBinding: ProfileRepository['startOAuthBinding'] = ((...args: unknown[]) => {
    loading.startOAuthBinding = true
    errors.startOAuthBinding = null
    return Promise.resolve()
      .then(() => (profileRepo.startOAuthBinding as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.startOAuthBinding = error; throw error })
      .finally(() => { loading.startOAuthBinding = false })
  }) as ProfileRepository['startOAuthBinding']

  const transferAffiliateQuota: ProfileRepository['transferAffiliateQuota'] = ((...args: unknown[]) => {
    loading.transferAffiliateQuota = true
    errors.transferAffiliateQuota = null
    return Promise.resolve()
      .then(() => (profileRepo.transferAffiliateQuota as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.transferAffiliateQuota = error; throw error })
      .finally(() => { loading.transferAffiliateQuota = false })
  }) as ProfileRepository['transferAffiliateQuota']

  const sendVerifyCode: TotpRepository['sendVerifyCode'] = ((...args: unknown[]) => {
    loading.sendVerifyCode = true
    errors.sendVerifyCode = null
    return Promise.resolve()
      .then(() => (totpRepo.sendVerifyCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.sendVerifyCode = error; throw error })
      .finally(() => { loading.sendVerifyCode = false })
  }) as TotpRepository['sendVerifyCode']

  const initiateSetup: TotpRepository['initiateSetup'] = ((...args: unknown[]) => {
    loading.initiateSetup = true
    errors.initiateSetup = null
    return Promise.resolve()
      .then(() => (totpRepo.initiateSetup as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.initiateSetup = error; throw error })
      .finally(() => { loading.initiateSetup = false })
  }) as TotpRepository['initiateSetup']

  const enable: TotpRepository['enable'] = ((...args: unknown[]) => {
    loading.enable = true
    errors.enable = null
    return Promise.resolve()
      .then(() => (totpRepo.enable as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.enable = error; throw error })
      .finally(() => { loading.enable = false })
  }) as TotpRepository['enable']

  const disable: TotpRepository['disable'] = ((...args: unknown[]) => {
    loading.disable = true
    errors.disable = null
    return Promise.resolve()
      .then(() => (totpRepo.disable as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.disable = error; throw error })
      .finally(() => { loading.disable = false })
  }) as TotpRepository['disable']

  const stepUp: TotpRepository['stepUp'] = ((...args: unknown[]) => {
    loading.stepUp = true
    errors.stepUp = null
    return Promise.resolve()
      .then(() => (totpRepo.stepUp as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.stepUp = error; throw error })
      .finally(() => { loading.stepUp = false })
  }) as TotpRepository['stepUp']

    return { loading, errors, updateProfile, changePassword, sendNotifyEmailCode, verifyNotifyEmail, removeNotifyEmail, toggleNotifyEmail, sendEmailBindingCode, bindEmailIdentity, unbindAuthIdentity, startOAuthBinding, transferAffiliateQuota, sendVerifyCode, initiateSetup, enable, disable, stepUp }
  })
}

export const useProfileActionStore = createProfileActionStore()
