/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useProfile — thin orchestrator composable for Profile.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useProfileQueryStore } from '@/features/profile/presentation/stores/profileQueryStore'
import { useProfileActionStore } from '@/features/profile/presentation/stores/profileActionStore'

export function useProfile() {
  const q_profileQueryStore = useProfileQueryStore()
  const a_profileActionStore = useProfileActionStore()
  return {
    ...q_profileQueryStore,
    ...a_profileActionStore,
  }
}
