/**
 * GroupsUserQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createGroupsUserQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { GroupsUserRepository } from '@/features/groups-user/domain/repositories/groupsUserRepository'
import { groupsUserRepository as default_groupsUser_repo } from '@/features/groups-user/data/repositories/groupsUserRepositoryImpl'

export function createGroupsUserQueryStore(groupsUserRepo: GroupsUserRepository = default_groupsUser_repo) {
  return defineStore('groupsUser/query', () => {
    const loading = reactive<Record<string, boolean>>({ getAvailable: false, getUserGroupRates: false })
    const errors = reactive<Record<string, unknown>>({ getAvailable: null as unknown, getUserGroupRates: null as unknown })

  const getAvailable: GroupsUserRepository['getAvailable'] = ((...args: unknown[]) => {
    loading.getAvailable = true
    errors.getAvailable = null
    return Promise.resolve()
      .then(() => (groupsUserRepo.getAvailable as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAvailable = error; throw error })
      .finally(() => { loading.getAvailable = false })
  }) as GroupsUserRepository['getAvailable']

  const getUserGroupRates: GroupsUserRepository['getUserGroupRates'] = ((...args: unknown[]) => {
    loading.getUserGroupRates = true
    errors.getUserGroupRates = null
    return Promise.resolve()
      .then(() => (groupsUserRepo.getUserGroupRates as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserGroupRates = error; throw error })
      .finally(() => { loading.getUserGroupRates = false })
  }) as GroupsUserRepository['getUserGroupRates']

    return { loading, errors, getAvailable, getUserGroupRates }
  })
}

export const useGroupsUserQueryStore = createGroupsUserQueryStore()
