/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminAudit — thin orchestrator composable for AdminAudit.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminAuditQueryStore } from '@/features/admin-audit/presentation/stores/adminAuditQueryStore'
import { useAdminAuditActionStore } from '@/features/admin-audit/presentation/stores/adminAuditActionStore'

export function useAdminAudit() {
  const q_adminAuditQueryStore = useAdminAuditQueryStore()
  const a_adminAuditActionStore = useAdminAuditActionStore()
  return {
    ...q_adminAuditQueryStore,
    ...a_adminAuditActionStore,
  }
}
