/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { getS3Config, updateS3Config, testS3Connection, getImageStorageConfig, updateImageStorageConfig, testImageStorageConnection, getSchedule, updateSchedule, createBackup, listBackups, getBackup, deleteBackup, getDownloadURL, restoreBackup, backupAPI } from '@/features/admin-backup/data/datasources/adminBackupDatasource'
export type { BackupS3Config, BackupScheduleConfig, BackupRecord, CreateBackupRequest, TestS3Response, ImageStorageConfig, ImageStorageConfigResponse } from '@/features/admin-backup/data/datasources/adminBackupDatasource'
export { default } from '@/features/admin-backup/data/datasources/adminBackupDatasource'
export { getAgentHealth, getConfig, updateConfig, testS3, listSourceProfiles, createSourceProfile, updateSourceProfile, deleteSourceProfile, setActiveSourceProfile, listS3Profiles, createS3Profile, updateS3Profile, deleteS3Profile, setActiveS3Profile, createBackupJob, listBackupJobs, getBackupJob, dataManagementAPI } from '@/features/admin-backup/data/datasources/dataManagementDatasource'
export type { BackupType, BackupJobStatus, BackupAgentInfo, BackupAgentHealth, DataManagementPostgresConfig, DataManagementRedisConfig, DataManagementS3Config, DataManagementConfig, SourceType, DataManagementSourceConfig, DataManagementSourceProfile, TestS3Request, CreateBackupJobRequest, CreateBackupJobResponse, BackupArtifactInfo, BackupS3Info, BackupJob, ListSourceProfilesResponse, CreateSourceProfileRequest, UpdateSourceProfileRequest, DataManagementS3Profile, ListS3ProfilesResponse, CreateS3ProfileRequest, UpdateS3ProfileRequest, ListBackupJobsRequest, ListBackupJobsResponse } from '@/features/admin-backup/data/datasources/dataManagementDatasource'
export * as adminBackup from '@/features/admin-backup/data/datasources/adminBackupDatasource'
export * as dataManagement from '@/features/admin-backup/data/datasources/dataManagementDatasource'
