/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 */
export * from '@/features/admin-groups/data/datasources/adminGroupsDatasource'
export { default } from '@/features/admin-groups/data/datasources/adminGroupsDatasource'
