/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { list, getAll, getAllIncludingInactive, getByPlatform, getById, getModelsListCandidates, create, duplicate, update, deleteGroup, toggleStatus, getStats, getGroupApiKeys, listCompositeRoutes, createCompositeRoute, updateCompositeRoute, deleteCompositeRoute, previewCompositeRoute, getGroupRateMultipliers, updateSortOrder, clearGroupRateMultipliers, batchSetGroupRateMultipliers, getGroupRPMOverrides, batchSetGroupRPMOverrides, clearGroupRPMOverrides, getUsageSummary, getCapacitySummary, groupsAPI } from '@/features/admin-groups/data/datasources/adminGroupsDatasource'
export type { GroupRateMultiplierEntry, GroupRPMOverrideEntry } from '@/features/admin-groups/data/datasources/adminGroupsDatasource'
export { default } from '@/features/admin-groups/data/datasources/adminGroupsDatasource'
