/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { getClusterStatus, clusterAPI } from '@/features/admin-cluster/data/datasources/adminClusterDatasource'
export type { ClusterInstanceStatus, ClusterTaskStatus, ClusterDeploymentStatus, ClusterSummary, ClusterInstance, ClusterTaskRun, ClusterStatusResponse } from '@/features/admin-cluster/data/datasources/adminClusterDatasource'
export { default } from '@/features/admin-cluster/data/datasources/adminClusterDatasource'
