/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 */
export * from '@/features/admin-dashboard/data/datasources/adminDashboardDatasource'
export { default } from '@/features/admin-dashboard/data/datasources/adminDashboardDatasource'
