/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { getStats, getRealtimeMetrics, getUsageTrend, getModelStats, getGroupStats, getUserBreakdown, getSnapshotV2, getApiKeyUsageTrend, getUserUsageTrend, getUserSpendingRanking, getBatchUsersUsage, getBatchApiKeysUsage, dashboardAPI } from '@/features/admin-dashboard/data/datasources/adminDashboardDatasource'
export type { TrendParams, TrendResponse, ModelStatsParams, ModelStatsResponse, GroupStatsParams, GroupStatsResponse, DashboardSnapshotV2Params, DashboardSnapshotV2Stats, DashboardSnapshotV2Response, UserBreakdownParams, UserBreakdownResponse, ApiKeyTrendParams, ApiKeyTrendResponse, UserTrendParams, UserTrendResponse, UserSpendingRankingParams, PlatformUsage, BatchUserUsageStats, BatchUsersUsageResponse, BatchApiKeyUsageStats, BatchApiKeysUsageResponse } from '@/features/admin-dashboard/data/datasources/adminDashboardDatasource'
export { default } from '@/features/admin-dashboard/data/datasources/adminDashboardDatasource'
