export class DashboardStats {
  totalUsers!: number
  todayNewUsers!: number
  activeUsers!: number
  hourlyActiveUsers!: number
  statsUpdatedAt!: string
  statsStale!: boolean
  totalApiKeys!: number
  activeApiKeys!: number
  totalAccounts!: number
  normalAccounts!: number
  errorAccounts!: number
  ratelimitAccounts!: number
  overloadAccounts!: number
  totalRequests!: number
  totalInputTokens!: number
  totalOutputTokens!: number
  totalCacheCreationTokens!: number
  totalCacheReadTokens!: number
  totalTokens!: number
  totalCost!: number
  totalActualCost!: number
  totalAccountCost!: number
  todayRequests!: number
  todayInputTokens!: number
  todayOutputTokens!: number
  todayCacheCreationTokens!: number
  todayCacheReadTokens!: number
  todayTokens!: number
  todayCost!: number
  todayActualCost!: number
  todayAccountCost!: number
  averageDurationMs!: number
  uptime!: number
  rpm!: number
  tpm!: number
}
