/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */
export { default as AdminOrdersPage } from './presentation/pages/AdminOrdersPage.vue'
export { default as AdminPaymentDashboardPage } from './presentation/pages/AdminPaymentDashboardPage.vue'
export { default as AdminPaymentPlansPage } from './presentation/pages/AdminPaymentPlansPage.vue'


// Route fragment — import in core/routes/index.ts

// export const adminOrdersRoutes: RouteRecordRaw[] = [{ path: '/todo', component: AdminOrdersPage }]
// export const adminOrdersRoutes: RouteRecordRaw[] = [{ path: '/todo', component: AdminPaymentDashboardPage }]
// export const adminOrdersRoutes: RouteRecordRaw[] = [{ path: '/todo', component: AdminPaymentPlansPage }]
