import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const adminUsageRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/usage',
    name: 'AdminUsage',
    component: () => import('@/features/admin-usage/presentation/pages/UsagePage.vue'),
    meta: { requiresAuth: true, requiresAdmin: true, title: 'Usage Records', titleKey: 'admin.usage.title', descriptionKey: 'admin.usage.description' },
  },
]
