import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const adminSubscriptionsRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/subscriptions',
    name: 'AdminSubscriptions',
    component: () => import('@/features/admin-subscriptions/presentation/pages/SubscriptionsPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: true, title: 'Subscription Management', titleKey: 'admin.subscriptions.title', descriptionKey: 'admin.subscriptions.description', simpleModeRestricted: true },
  },
]
