/**
 * AdminUsageQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminUsageQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminUsageRepository } from '@/features/admin-usage/domain/repositories/adminUsageRepository'
import { adminUsageRepository as default_adminUsage_repo } from '@/features/admin-usage/data/repositories/adminUsageRepositoryImpl'

export function createAdminUsageQueryStore(adminUsageRepo: AdminUsageRepository = default_adminUsage_repo) {
  return defineStore('adminUsage/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, getStats: false, searchUsers: false, searchApiKeys: false, listCleanupTasks: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, getStats: null as unknown, searchUsers: null as unknown, searchApiKeys: null as unknown, listCleanupTasks: null as unknown })

  const list: AdminUsageRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (adminUsageRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as AdminUsageRepository['list']

  const getStats: AdminUsageRepository['getStats'] = ((...args: unknown[]) => {
    loading.getStats = true
    errors.getStats = null
    return Promise.resolve()
      .then(() => (adminUsageRepo.getStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getStats = error; throw error })
      .finally(() => { loading.getStats = false })
  }) as AdminUsageRepository['getStats']

  const searchUsers: AdminUsageRepository['searchUsers'] = ((...args: unknown[]) => {
    loading.searchUsers = true
    errors.searchUsers = null
    return Promise.resolve()
      .then(() => (adminUsageRepo.searchUsers as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.searchUsers = error; throw error })
      .finally(() => { loading.searchUsers = false })
  }) as AdminUsageRepository['searchUsers']

  const searchApiKeys: AdminUsageRepository['searchApiKeys'] = ((...args: unknown[]) => {
    loading.searchApiKeys = true
    errors.searchApiKeys = null
    return Promise.resolve()
      .then(() => (adminUsageRepo.searchApiKeys as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.searchApiKeys = error; throw error })
      .finally(() => { loading.searchApiKeys = false })
  }) as AdminUsageRepository['searchApiKeys']

  const listCleanupTasks: AdminUsageRepository['listCleanupTasks'] = ((...args: unknown[]) => {
    loading.listCleanupTasks = true
    errors.listCleanupTasks = null
    return Promise.resolve()
      .then(() => (adminUsageRepo.listCleanupTasks as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listCleanupTasks = error; throw error })
      .finally(() => { loading.listCleanupTasks = false })
  }) as AdminUsageRepository['listCleanupTasks']

    return { loading, errors, list, getStats, searchUsers, searchApiKeys, listCleanupTasks }
  })
}

export const useAdminUsageQueryStore = createAdminUsageQueryStore()
