import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const adminRedeemRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/redeem',
    name: 'AdminRedeem',
    component: () => import('@/features/admin-redeem/presentation/pages/RedeemPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: true, title: 'Redeem Code Management', titleKey: 'admin.redeem.title', descriptionKey: 'admin.redeem.description', simpleModeRestricted: true },
  },
]
