/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */
export { default as PromptAuditPage } from './presentation/pages/PromptAuditPage.vue'
export type * from './domain/models/promptAuditTypes'

// Route fragment — import in core/routes/index.ts

// export const promptAuditRoutes: RouteRecordRaw[] = [{ path: '/todo', component: PromptAuditPage }]
