/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 */
export * from '@/features/admin-orders/data/datasources/adminPaymentDatasource'
export { default } from '@/features/admin-orders/data/datasources/adminPaymentDatasource'
