/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { adminPaymentAPI } from '@/features/admin-orders/data/datasources/adminPaymentDatasource'
export type { AdminPaymentConfig, UpdatePaymentConfigRequest, RefundResult } from '@/features/admin-orders/data/datasources/adminPaymentDatasource'
export { default } from '@/features/admin-orders/data/datasources/adminPaymentDatasource'
