/**
 * BatchImageActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createBatchImageActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { BatchImageRepository } from '@/features/batch-image/domain/repositories/batchImageRepository'
import { batchImageRepository as default_batchImage_repo } from '@/features/batch-image/data/repositories/batchImageRepositoryImpl'

export function createBatchImageActionStore(batchImageRepo: BatchImageRepository = default_batchImage_repo) {
  return defineStore('batchImage/action', () => {
    const loading = reactive<Record<string, boolean>>({ submitBatchImageJob: false, cancelBatchImageJob: false, downloadBatchImageZip: false, deleteBatchImageJobRecord: false })
    const errors = reactive<Record<string, unknown>>({ submitBatchImageJob: null as unknown, cancelBatchImageJob: null as unknown, downloadBatchImageZip: null as unknown, deleteBatchImageJobRecord: null as unknown })

  const submitBatchImageJob: BatchImageRepository['submitBatchImageJob'] = ((...args: unknown[]) => {
    loading.submitBatchImageJob = true
    errors.submitBatchImageJob = null
    return Promise.resolve()
      .then(() => (batchImageRepo.submitBatchImageJob as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.submitBatchImageJob = error; throw error })
      .finally(() => { loading.submitBatchImageJob = false })
  }) as BatchImageRepository['submitBatchImageJob']

  const cancelBatchImageJob: BatchImageRepository['cancelBatchImageJob'] = ((...args: unknown[]) => {
    loading.cancelBatchImageJob = true
    errors.cancelBatchImageJob = null
    return Promise.resolve()
      .then(() => (batchImageRepo.cancelBatchImageJob as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.cancelBatchImageJob = error; throw error })
      .finally(() => { loading.cancelBatchImageJob = false })
  }) as BatchImageRepository['cancelBatchImageJob']

  const downloadBatchImageZip: BatchImageRepository['downloadBatchImageZip'] = ((...args: unknown[]) => {
    loading.downloadBatchImageZip = true
    errors.downloadBatchImageZip = null
    return Promise.resolve()
      .then(() => (batchImageRepo.downloadBatchImageZip as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.downloadBatchImageZip = error; throw error })
      .finally(() => { loading.downloadBatchImageZip = false })
  }) as BatchImageRepository['downloadBatchImageZip']

  const deleteBatchImageJobRecord: BatchImageRepository['deleteBatchImageJobRecord'] = ((...args: unknown[]) => {
    loading.deleteBatchImageJobRecord = true
    errors.deleteBatchImageJobRecord = null
    return Promise.resolve()
      .then(() => (batchImageRepo.deleteBatchImageJobRecord as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteBatchImageJobRecord = error; throw error })
      .finally(() => { loading.deleteBatchImageJobRecord = false })
  }) as BatchImageRepository['deleteBatchImageJobRecord']

    return { loading, errors, submitBatchImageJob, cancelBatchImageJob, downloadBatchImageZip, deleteBatchImageJobRecord }
  })
}

export const useBatchImageActionStore = createBatchImageActionStore()
