/**
 * BatchImageQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createBatchImageQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { BatchImageRepository } from '@/features/batch-image/domain/repositories/batchImageRepository'
import { batchImageRepository as default_batchImage_repo } from '@/features/batch-image/data/repositories/batchImageRepositoryImpl'

export function createBatchImageQueryStore(batchImageRepo: BatchImageRepository = default_batchImage_repo) {
  return defineStore('batchImage/query', () => {
    const loading = reactive<Record<string, boolean>>({ getBatchImageJob: false, listBatchImageJobs: false, listBatchImageModels: false, listBatchImageItems: false, getBatchImageItemContent: false })
    const errors = reactive<Record<string, unknown>>({ getBatchImageJob: null as unknown, listBatchImageJobs: null as unknown, listBatchImageModels: null as unknown, listBatchImageItems: null as unknown, getBatchImageItemContent: null as unknown })

  const getBatchImageJob: BatchImageRepository['getBatchImageJob'] = ((...args: unknown[]) => {
    loading.getBatchImageJob = true
    errors.getBatchImageJob = null
    return Promise.resolve()
      .then(() => (batchImageRepo.getBatchImageJob as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getBatchImageJob = error; throw error })
      .finally(() => { loading.getBatchImageJob = false })
  }) as BatchImageRepository['getBatchImageJob']

  const listBatchImageJobs: BatchImageRepository['listBatchImageJobs'] = ((...args: unknown[]) => {
    loading.listBatchImageJobs = true
    errors.listBatchImageJobs = null
    return Promise.resolve()
      .then(() => (batchImageRepo.listBatchImageJobs as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listBatchImageJobs = error; throw error })
      .finally(() => { loading.listBatchImageJobs = false })
  }) as BatchImageRepository['listBatchImageJobs']

  const listBatchImageModels: BatchImageRepository['listBatchImageModels'] = ((...args: unknown[]) => {
    loading.listBatchImageModels = true
    errors.listBatchImageModels = null
    return Promise.resolve()
      .then(() => (batchImageRepo.listBatchImageModels as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listBatchImageModels = error; throw error })
      .finally(() => { loading.listBatchImageModels = false })
  }) as BatchImageRepository['listBatchImageModels']

  const listBatchImageItems: BatchImageRepository['listBatchImageItems'] = ((...args: unknown[]) => {
    loading.listBatchImageItems = true
    errors.listBatchImageItems = null
    return Promise.resolve()
      .then(() => (batchImageRepo.listBatchImageItems as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listBatchImageItems = error; throw error })
      .finally(() => { loading.listBatchImageItems = false })
  }) as BatchImageRepository['listBatchImageItems']

  const getBatchImageItemContent: BatchImageRepository['getBatchImageItemContent'] = ((...args: unknown[]) => {
    loading.getBatchImageItemContent = true
    errors.getBatchImageItemContent = null
    return Promise.resolve()
      .then(() => (batchImageRepo.getBatchImageItemContent as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getBatchImageItemContent = error; throw error })
      .finally(() => { loading.getBatchImageItemContent = false })
  }) as BatchImageRepository['getBatchImageItemContent']

    return { loading, errors, getBatchImageJob, listBatchImageJobs, listBatchImageModels, listBatchImageItems, getBatchImageItemContent }
  })
}

export const useBatchImageQueryStore = createBatchImageQueryStore()
