/**
 * AdminDashboardQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminDashboardQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminDashboardRepository } from '@/features/admin-dashboard/domain/repositories/adminDashboardRepository'
import { adminDashboardRepository as default_adminDashboard_repo } from '@/features/admin-dashboard/data/repositories/adminDashboardRepositoryImpl'

export function createAdminDashboardQueryStore(adminDashboardRepo: AdminDashboardRepository = default_adminDashboard_repo) {
  return defineStore('adminDashboard/query', () => {
    const loading = reactive<Record<string, boolean>>({ getStats: false, getRealtimeMetrics: false, getUsageTrend: false, getModelStats: false, getGroupStats: false, getUserBreakdown: false, getSnapshotV2: false, getApiKeyUsageTrend: false, getUserUsageTrend: false, getUserSpendingRanking: false, getBatchUsersUsage: false, getBatchApiKeysUsage: false })
    const errors = reactive<Record<string, unknown>>({ getStats: null as unknown, getRealtimeMetrics: null as unknown, getUsageTrend: null as unknown, getModelStats: null as unknown, getGroupStats: null as unknown, getUserBreakdown: null as unknown, getSnapshotV2: null as unknown, getApiKeyUsageTrend: null as unknown, getUserUsageTrend: null as unknown, getUserSpendingRanking: null as unknown, getBatchUsersUsage: null as unknown, getBatchApiKeysUsage: null as unknown })

  const getStats: AdminDashboardRepository['getStats'] = ((...args: unknown[]) => {
    loading.getStats = true
    errors.getStats = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getStats = error; throw error })
      .finally(() => { loading.getStats = false })
  }) as AdminDashboardRepository['getStats']

  const getRealtimeMetrics: AdminDashboardRepository['getRealtimeMetrics'] = ((...args: unknown[]) => {
    loading.getRealtimeMetrics = true
    errors.getRealtimeMetrics = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getRealtimeMetrics as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getRealtimeMetrics = error; throw error })
      .finally(() => { loading.getRealtimeMetrics = false })
  }) as AdminDashboardRepository['getRealtimeMetrics']

  const getUsageTrend: AdminDashboardRepository['getUsageTrend'] = ((...args: unknown[]) => {
    loading.getUsageTrend = true
    errors.getUsageTrend = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getUsageTrend as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUsageTrend = error; throw error })
      .finally(() => { loading.getUsageTrend = false })
  }) as AdminDashboardRepository['getUsageTrend']

  const getModelStats: AdminDashboardRepository['getModelStats'] = ((...args: unknown[]) => {
    loading.getModelStats = true
    errors.getModelStats = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getModelStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getModelStats = error; throw error })
      .finally(() => { loading.getModelStats = false })
  }) as AdminDashboardRepository['getModelStats']

  const getGroupStats: AdminDashboardRepository['getGroupStats'] = ((...args: unknown[]) => {
    loading.getGroupStats = true
    errors.getGroupStats = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getGroupStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getGroupStats = error; throw error })
      .finally(() => { loading.getGroupStats = false })
  }) as AdminDashboardRepository['getGroupStats']

  const getUserBreakdown: AdminDashboardRepository['getUserBreakdown'] = ((...args: unknown[]) => {
    loading.getUserBreakdown = true
    errors.getUserBreakdown = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getUserBreakdown as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserBreakdown = error; throw error })
      .finally(() => { loading.getUserBreakdown = false })
  }) as AdminDashboardRepository['getUserBreakdown']

  const getSnapshotV2: AdminDashboardRepository['getSnapshotV2'] = ((...args: unknown[]) => {
    loading.getSnapshotV2 = true
    errors.getSnapshotV2 = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getSnapshotV2 as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getSnapshotV2 = error; throw error })
      .finally(() => { loading.getSnapshotV2 = false })
  }) as AdminDashboardRepository['getSnapshotV2']

  const getApiKeyUsageTrend: AdminDashboardRepository['getApiKeyUsageTrend'] = ((...args: unknown[]) => {
    loading.getApiKeyUsageTrend = true
    errors.getApiKeyUsageTrend = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getApiKeyUsageTrend as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getApiKeyUsageTrend = error; throw error })
      .finally(() => { loading.getApiKeyUsageTrend = false })
  }) as AdminDashboardRepository['getApiKeyUsageTrend']

  const getUserUsageTrend: AdminDashboardRepository['getUserUsageTrend'] = ((...args: unknown[]) => {
    loading.getUserUsageTrend = true
    errors.getUserUsageTrend = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getUserUsageTrend as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserUsageTrend = error; throw error })
      .finally(() => { loading.getUserUsageTrend = false })
  }) as AdminDashboardRepository['getUserUsageTrend']

  const getUserSpendingRanking: AdminDashboardRepository['getUserSpendingRanking'] = ((...args: unknown[]) => {
    loading.getUserSpendingRanking = true
    errors.getUserSpendingRanking = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getUserSpendingRanking as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserSpendingRanking = error; throw error })
      .finally(() => { loading.getUserSpendingRanking = false })
  }) as AdminDashboardRepository['getUserSpendingRanking']

  const getBatchUsersUsage: AdminDashboardRepository['getBatchUsersUsage'] = ((...args: unknown[]) => {
    loading.getBatchUsersUsage = true
    errors.getBatchUsersUsage = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getBatchUsersUsage as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getBatchUsersUsage = error; throw error })
      .finally(() => { loading.getBatchUsersUsage = false })
  }) as AdminDashboardRepository['getBatchUsersUsage']

  const getBatchApiKeysUsage: AdminDashboardRepository['getBatchApiKeysUsage'] = ((...args: unknown[]) => {
    loading.getBatchApiKeysUsage = true
    errors.getBatchApiKeysUsage = null
    return Promise.resolve()
      .then(() => (adminDashboardRepo.getBatchApiKeysUsage as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getBatchApiKeysUsage = error; throw error })
      .finally(() => { loading.getBatchApiKeysUsage = false })
  }) as AdminDashboardRepository['getBatchApiKeysUsage']

    return { loading, errors, getStats, getRealtimeMetrics, getUsageTrend, getModelStats, getGroupStats, getUserBreakdown, getSnapshotV2, getApiKeyUsageTrend, getUserUsageTrend, getUserSpendingRanking, getBatchUsersUsage, getBatchApiKeysUsage }
  })
}

export const useAdminDashboardQueryStore = createAdminDashboardQueryStore()
