/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */
export { default as AvailableChannelsPage } from './presentation/pages/AvailableChannelsPage.vue'
export { default as ChannelStatusPage } from './presentation/pages/ChannelStatusPage.vue'
export { default as CustomLandingPage } from './presentation/pages/CustomLandingPage.vue'


// Route fragment — import in core/routes/index.ts

// export const channelsUserRoutes: RouteRecordRaw[] = [{ path: '/todo', component: AvailableChannelsPage }]
// export const channelsUserRoutes: RouteRecordRaw[] = [{ path: '/todo', component: ChannelStatusPage }]
// export const channelsUserRoutes: RouteRecordRaw[] = [{ path: '/todo', component: CustomLandingPage }]
