import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const channelsUserRoutes: RouteRecordRaw[] = [
  {
    path: '/available-channels',
    name: 'UserAvailableChannels',
    component: () => import('@/features/channels-user/presentation/pages/AvailableChannelsPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: false, title: 'Available Channels', titleKey: 'availableChannels.title', descriptionKey: 'availableChannels.description' },
  },
  {
    path: '/monitor',
    name: 'ChannelStatus',
    component: () => import('@/features/channels-user/presentation/pages/ChannelStatusPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: false, title: 'Channel Status', titleKey: 'nav.channelStatus' },
  },
  {
    path: '/custom/:id',
    name: 'CustomPage',
    component: () => import('@/features/channels-user/presentation/pages/CustomLandingPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: false, title: 'Custom Page', titleKey: 'customPage.title' },
  },
]
