import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const adminDashboardRoutes: RouteRecordRaw[] = [
  {
    path: '/admin',
    redirect: '/admin/dashboard',
  },
  {
    path: '/admin/dashboard',
    name: 'AdminDashboard',
    component: () => import('@/features/admin-dashboard/presentation/pages/DashboardPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: true, title: 'Admin Dashboard', titleKey: 'admin.dashboard.title', descriptionKey: 'admin.dashboard.description' },
  },
]
