import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const authRoutes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/features/auth/presentation/pages/LoginPage.vue'),
    meta: { requiresAuth: false, title: 'Login', titleKey: 'home.login', backendModePublic: true },
  },
  {
    path: '/register',
    name: 'Register',
    component: () => import('@/features/auth/presentation/pages/RegisterPage.vue'),
    meta: { requiresAuth: false, title: 'Register', titleKey: 'auth.createAccount', backendModePendingAuth: true },
  },
  {
    path: '/email-verify',
    name: 'EmailVerify',
    component: () => import('@/features/auth/presentation/pages/EmailVerifyPage.vue'),
    meta: { requiresAuth: false, title: 'Verify Email', backendModePendingAuth: true },
  },
  {
    path: '/auth/callback',
    name: 'OAuthCallback',
    alias: '/auth/oauth/callback',
    component: () => import('@/features/auth/presentation/pages/OAuthCallbackPage.vue'),
    meta: { requiresAuth: false, title: 'OAuth Callback', titleKey: 'auth.oauthCallbackPageTitle', backendModeCallback: true },
  },
  {
    path: '/auth/linuxdo/callback',
    name: 'LinuxDoOAuthCallback',
    component: () => import('@/features/auth/presentation/pages/LinuxDoCallbackPage.vue'),
    meta: { requiresAuth: false, title: 'LinuxDo OAuth Callback', titleKey: 'auth.linuxdoCallbackPageTitle', backendModeCallback: true },
  },
  {
    path: '/auth/wechat/callback',
    name: 'WeChatOAuthCallback',
    component: () => import('@/features/auth/presentation/pages/WechatCallbackPage.vue'),
    meta: { requiresAuth: false, title: 'WeChat OAuth Callback', titleKey: 'auth.wechatCallbackPageTitle', backendModeCallback: true },
  },
  {
    path: '/auth/wechat/payment/callback',
    name: 'WeChatPaymentOAuthCallback',
    component: () => import('@/features/billing/presentation/pages/WechatPaymentCallbackPage.vue'),
    meta: { requiresAuth: false, title: 'WeChat Payment Callback', titleKey: 'auth.wechatPaymentCallbackPageTitle', backendModeCallback: true },
  },
  {
    path: '/auth/dingtalk/callback',
    name: 'DingTalkOAuthCallback',
    component: () => import('@/features/auth/presentation/pages/DingTalkCallbackPage.vue'),
    meta: { requiresAuth: false, title: 'DingTalk OAuth Callback', titleKey: 'auth.dingtalkCallbackPageTitle', backendModeCallback: true },
  },
  {
    path: '/auth/dingtalk/email-completion',
    name: 'dingtalk-email-completion',
    component: () => import('@/features/auth/presentation/pages/DingTalkEmailCompletionPage.vue'),
    meta: { requiresAuth: false, title: 'DingTalk Email Completion', backendModeCallback: true },
  },
  {
    path: '/auth/oidc/callback',
    name: 'OIDCOAuthCallback',
    component: () => import('@/features/auth/presentation/pages/OidcCallbackPage.vue'),
    meta: { requiresAuth: false, title: 'OIDC OAuth Callback', titleKey: 'auth.oidcCallbackPageTitle', backendModeCallback: true },
  },
  {
    path: '/forgot-password',
    name: 'ForgotPassword',
    component: () => import('@/features/auth/presentation/pages/ForgotPasswordPage.vue'),
    meta: { requiresAuth: false, title: 'Forgot Password', titleKey: 'auth.forgotPasswordTitle' },
  },
  {
    path: '/reset-password',
    name: 'ResetPassword',
    component: () => import('@/features/auth/presentation/pages/ResetPasswordPage.vue'),
    meta: { requiresAuth: false, title: 'Reset Password' },
  },
]

// Router guard composition export.
export { useAuthStore } from '@/features/auth/presentation/stores/authStore'
