/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */
export { default as DingTalkCallbackPage } from './presentation/pages/DingTalkCallbackPage.vue'
export { default as DingTalkEmailCompletionPage } from './presentation/pages/DingTalkEmailCompletionPage.vue'
export { default as EmailVerifyPage } from './presentation/pages/EmailVerifyPage.vue'
export { default as ForgotPasswordPage } from './presentation/pages/ForgotPasswordPage.vue'
export { default as LinuxDoCallbackPage } from './presentation/pages/LinuxDoCallbackPage.vue'
export { default as LoginPage } from './presentation/pages/LoginPage.vue'
export { default as OAuthCallbackPage } from './presentation/pages/OAuthCallbackPage.vue'
export { default as OidcCallbackPage } from './presentation/pages/OidcCallbackPage.vue'
export { default as RegisterPage } from './presentation/pages/RegisterPage.vue'
export { default as ResetPasswordPage } from './presentation/pages/ResetPasswordPage.vue'
export { default as WechatCallbackPage } from './presentation/pages/WechatCallbackPage.vue'


// Route fragment — import in core/routes/index.ts

// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: DingTalkCallbackPage }]
// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: DingTalkEmailCompletionPage }]
// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: EmailVerifyPage }]
// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: ForgotPasswordPage }]
// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: LinuxDoCallbackPage }]
// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: LoginPage }]
// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: OAuthCallbackPage }]
// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: OidcCallbackPage }]
// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: RegisterPage }]
// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: ResetPasswordPage }]
// export const authRoutes: RouteRecordRaw[] = [{ path: '/todo', component: WechatCallbackPage }]
