/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { list, getById, generate, deleteCode, batchDelete, batchUpdate, expire, getStats, exportCodes, redeemAPI } from '@/features/admin-redeem/data/datasources/adminRedeemDatasource'
export { default } from '@/features/admin-redeem/data/datasources/adminRedeemDatasource'
