/**
 * SetupActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createSetupActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { SetupRepository } from '@/features/setup/domain/repositories/setupRepository'
import { setupRepository as default_setup_repo } from '@/features/setup/data/repositories/setupRepositoryImpl'

export function createSetupActionStore(setupRepo: SetupRepository = default_setup_repo) {
  return defineStore('setup/action', () => {
    const loading = reactive<Record<string, boolean>>({ testDatabase: false, testRedis: false, install: false })
    const errors = reactive<Record<string, unknown>>({ testDatabase: null as unknown, testRedis: null as unknown, install: null as unknown })

  const testDatabase: SetupRepository['testDatabase'] = ((...args: unknown[]) => {
    loading.testDatabase = true
    errors.testDatabase = null
    return Promise.resolve()
      .then(() => (setupRepo.testDatabase as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.testDatabase = error; throw error })
      .finally(() => { loading.testDatabase = false })
  }) as SetupRepository['testDatabase']

  const testRedis: SetupRepository['testRedis'] = ((...args: unknown[]) => {
    loading.testRedis = true
    errors.testRedis = null
    return Promise.resolve()
      .then(() => (setupRepo.testRedis as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.testRedis = error; throw error })
      .finally(() => { loading.testRedis = false })
  }) as SetupRepository['testRedis']

  const install: SetupRepository['install'] = ((...args: unknown[]) => {
    loading.install = true
    errors.install = null
    return Promise.resolve()
      .then(() => (setupRepo.install as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.install = error; throw error })
      .finally(() => { loading.install = false })
  }) as SetupRepository['install']

    return { loading, errors, testDatabase, testRedis, install }
  })
}

export const useSetupActionStore = createSetupActionStore()
