/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useUsage — thin orchestrator composable for Usage.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useUsageQueryStore } from '@/features/usage/presentation/stores/usageQueryStore'

export function useUsage() {
  const q_usageQueryStore = useUsageQueryStore()
  return {
    ...q_usageQueryStore,
  }
}
