/**
 * ChannelMonitorUserActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createChannelMonitorUserActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { ChannelMonitorUserRepository } from '@/features/channel-monitor-user/domain/repositories/channelMonitorUserRepository'
import { channelMonitorUserRepository as default_channelMonitorUser_repo } from '@/features/channel-monitor-user/data/repositories/channelMonitorUserRepositoryImpl'

export function createChannelMonitorUserActionStore(channelMonitorUserRepo: ChannelMonitorUserRepository = default_channelMonitorUser_repo) {
  return defineStore('channelMonitorUser/action', () => {
    const loading = reactive<Record<string, boolean>>({ status: false, statusBatch: false })
    const errors = reactive<Record<string, unknown>>({ status: null as unknown, statusBatch: null as unknown })

  const status: ChannelMonitorUserRepository['status'] = ((...args: unknown[]) => {
    loading.status = true
    errors.status = null
    return Promise.resolve()
      .then(() => (channelMonitorUserRepo.status as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.status = error; throw error })
      .finally(() => { loading.status = false })
  }) as ChannelMonitorUserRepository['status']

  const statusBatch: ChannelMonitorUserRepository['statusBatch'] = ((...args: unknown[]) => {
    loading.statusBatch = true
    errors.statusBatch = null
    return Promise.resolve()
      .then(() => (channelMonitorUserRepo.statusBatch as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.statusBatch = error; throw error })
      .finally(() => { loading.statusBatch = false })
  }) as ChannelMonitorUserRepository['statusBatch']

    return { loading, errors, status, statusBatch }
  })
}

export const useChannelMonitorUserActionStore = createChannelMonitorUserActionStore()
