/**
 * ChannelMonitorUserQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createChannelMonitorUserQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { ChannelMonitorUserRepository } from '@/features/channel-monitor-user/domain/repositories/channelMonitorUserRepository'
import { channelMonitorUserRepository as default_channelMonitorUser_repo } from '@/features/channel-monitor-user/data/repositories/channelMonitorUserRepositoryImpl'

export function createChannelMonitorUserQueryStore(channelMonitorUserRepo: ChannelMonitorUserRepository = default_channelMonitorUser_repo) {
  return defineStore('channelMonitorUser/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown })

  const list: ChannelMonitorUserRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (channelMonitorUserRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as ChannelMonitorUserRepository['list']

    return { loading, errors, list }
  })
}

export const useChannelMonitorUserQueryStore = createChannelMonitorUserQueryStore()
