/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { list, getById, create, update, deleteUser, updateBalance, updateConcurrency, batchUpdateLimits, toggleStatus, getUserApiKeys, getUserUsageStats, getUserBalanceHistory, replaceGroup, bindUserAuthIdentity, getPlatformQuotas, getBatchPlatformQuotas, updatePlatformQuotas, resetPlatformQuotaWindow, usersAPI } from '@/features/admin-users/data/datasources/adminUsersDatasource'
export type { AdminBindAuthIdentityChannelRequest, AdminBindAuthIdentityRequest, AdminBoundAuthIdentityChannel, AdminBoundAuthIdentity, BatchUpdateUserLimitsRequest, BatchUpdateUserLimitsResponse, BalanceHistoryItem, BalanceHistoryResponse, PlatformQuotaPlatform, PlatformQuotaWindow, PlatformQuotaItem, PlatformQuotaUpdateItem, PlatformQuotasResponse, BatchPlatformQuotasResponse } from '@/features/admin-users/data/datasources/adminUsersDatasource'
export { default } from '@/features/admin-users/data/datasources/adminUsersDatasource'
export { listDefinitions, listEnabledDefinitions, createDefinition, updateDefinition, deleteDefinition, reorderDefinitions, getUserAttributeValues, updateUserAttributeValues, getBatchUserAttributes, userAttributesAPI } from '@/features/admin-users/data/datasources/userAttributesDatasource'
export type { BatchUserAttributesResponse } from '@/features/admin-users/data/datasources/userAttributesDatasource'
export * as adminUsers from '@/features/admin-users/data/datasources/adminUsersDatasource'
export * as userAttributes from '@/features/admin-users/data/datasources/userAttributesDatasource'
