/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { normalizePlatformQuotasMap, sanitizePlatformQuotasMap, normalizeDefaultSubscriptionSettings, buildAuthSourceDefaultsState, appendAuthSourceDefaultsToUpdateRequest, getPaymentVisibleMethodSourceOptions, normalizePaymentVisibleMethodSource, getWeChatConnectModeOptions, normalizeWeChatConnectMode, defaultWeChatConnectScopesForMode, resolveWeChatConnectModeCapabilities, deriveWeChatConnectStoredMode, getSettings, updateSettings, testSmtpConnection, sendTestEmail, getEmailTemplates, getEmailTemplate, updateEmailTemplate, restoreOfficialEmailTemplate, previewEmailTemplate, listAdminApiKeys, createAdminApiKey, updateAdminApiKey, rotateAdminApiKey, revokeAdminApiKey, getAdminApiKey, regenerateAdminApiKey, deleteAdminApiKey, getOverloadCooldownSettings, updateOverloadCooldownSettings, getRateLimit429CooldownSettings, updateRateLimit429CooldownSettings, getGlobalTempUnschedulableSettings, updateGlobalTempUnschedulableSettings, getStreamTimeoutSettings, updateStreamTimeoutSettings, getRectifierSettings, updateRectifierSettings, getBetaPolicySettings, updateBetaPolicySettings, getWebSearchEmulationConfig, updateWebSearchEmulationConfig, testWebSearchEmulation, resetWebSearchUsage, settingsAPI } from '@/features/admin-settings/data/datasources/adminSettingsDatasource'
export type { ClientIPResolutionMode, ClientIPResolutionStatus, DefaultSubscriptionSetting, PlatformType, QuotaWindowType, PlatformQuotaLimits, DefaultPlatformQuotasMap, AuthSourceType, AuthSourceDefaultsValue, AuthSourceDefaultsState, PaymentVisibleMethod, PaymentVisibleMethodSource, WeChatConnectMode, PaymentVisibleMethodSourceOption, WeChatConnectModeOption, SystemSettings, UpdateSettingsRequest, TestSmtpRequest, SendTestEmailRequest, EmailTemplateOption, EmailTemplateEventOption, EmailTemplateSummary, EmailTemplateListResponse, EmailTemplateDetail, UpdateEmailTemplateRequest, PreviewEmailTemplateRequest, EmailTemplatePreviewResponse, AdminApiKeyStatus, AdminApiKeyScope, AdminApiKey, CreateAdminApiKeyRequest, UpdateAdminApiKeyRequest, OverloadCooldownSettings, RateLimit429CooldownSettings, GlobalTempUnschedulableSettings, StreamTimeoutSettings, ThinkingDisplayMode, RectifierSettings, OpenAIFastPolicyRule, OpenAIFastPolicySettings, BetaPolicyRule, BetaPolicySettings, WebSearchProviderConfig, WebSearchEmulationConfig, WebSearchTestResult } from '@/features/admin-settings/data/datasources/adminSettingsDatasource'
export { default } from '@/features/admin-settings/data/datasources/adminSettingsDatasource'
export { adminComplianceAPI } from '@/features/admin-settings/data/datasources/complianceDatasource'
export type { AdminComplianceAcknowledgement, AdminComplianceStatus, AcceptAdminComplianceRequest } from '@/features/admin-settings/data/datasources/complianceDatasource'
export { list, getById, create, update, deleteRule, toggleEnabled, errorPassthroughAPI } from '@/features/admin-settings/data/datasources/errorPassthroughDatasource'
export type { ErrorPassthroughRule, CreateRuleRequest, UpdateRuleRequest } from '@/features/admin-settings/data/datasources/errorPassthroughDatasource'
export { getVersion, checkUpdates, getRollbackVersions, performUpdate, rollback, restartService, systemAPI } from '@/features/admin-settings/data/datasources/systemDatasource'
export type { ReleaseInfo, VersionInfo, UpdateResult, RollbackVersionInfo } from '@/features/admin-settings/data/datasources/systemDatasource'
export { deleteProfile, tlsFingerprintProfileAPI } from '@/features/admin-settings/data/datasources/tlsFingerprintProfileDatasource'
export type { TLSFingerprintProfile, CreateProfileRequest, UpdateProfileRequest } from '@/features/admin-settings/data/datasources/tlsFingerprintProfileDatasource'
export * as adminSettings from '@/features/admin-settings/data/datasources/adminSettingsDatasource'
export * as compliance from '@/features/admin-settings/data/datasources/complianceDatasource'
export * as errorPassthrough from '@/features/admin-settings/data/datasources/errorPassthroughDatasource'
export * as system from '@/features/admin-settings/data/datasources/systemDatasource'
export * as tlsFingerprintProfile from '@/features/admin-settings/data/datasources/tlsFingerprintProfileDatasource'
