import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const adminSettingsRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/settings',
    name: 'AdminSettings',
    component: () => import('@/features/admin-settings/presentation/pages/SettingsPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: true, title: 'System Settings', titleKey: 'admin.settings.title', descriptionKey: 'admin.settings.description' },
  },
]
