/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { getProfile, updateProfile, changePassword, sendNotifyEmailCode, verifyNotifyEmail, removeNotifyEmail, toggleNotifyEmail, sendEmailBindingCode, bindEmailIdentity, unbindAuthIdentity, resolveWeChatOAuthMode, buildOAuthBindingStartURL, startOAuthBinding, getAffiliateDetail, transferAffiliateQuota, getMyPlatformQuotas, userAPI } from '@/features/profile/data/datasources/profileDatasource'
export type { BindableOAuthProvider } from '@/features/profile/data/datasources/profileDatasource'
export { default } from '@/features/profile/data/datasources/profileDatasource'
export { getStatus, getVerificationMethod, sendVerifyCode, initiateSetup, enable, disable, stepUp, totpAPI } from '@/features/profile/data/datasources/totpDatasource'
export type { TotpStepUpResponse } from '@/features/profile/data/datasources/totpDatasource'
export * as profile from '@/features/profile/data/datasources/profileDatasource'
export * as totp from '@/features/profile/data/datasources/totpDatasource'
