/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminUsers — thin orchestrator composable for AdminUsers.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminUsersQueryStore } from '@/features/admin-users/presentation/stores/adminUsersQueryStore'
import { useAdminUsersActionStore } from '@/features/admin-users/presentation/stores/adminUsersActionStore'

export function useAdminUsers() {
  const q_adminUsersQueryStore = useAdminUsersQueryStore()
  const a_adminUsersActionStore = useAdminUsersActionStore()
  return {
    ...q_adminUsersQueryStore,
    ...a_adminUsersActionStore,
  }
}
