/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { list, getStats, searchUsers, searchApiKeys, listCleanupTasks, createCleanupTask, cancelCleanupTask, adminUsageAPI } from '@/features/admin-usage/data/datasources/adminUsageDatasource'
export type { AdminUsageStatsResponse, SimpleUser, SimpleApiKey, UsageCleanupFilters, UsageCleanupTask, CreateUsageCleanupTaskRequest, AdminUsageQueryParams } from '@/features/admin-usage/data/datasources/adminUsageDatasource'
export { default } from '@/features/admin-usage/data/datasources/adminUsageDatasource'
export { updateApiKeyGroup, apiKeysAPI } from '@/features/admin-usage/data/datasources/apiKeysDatasource'
export type { UpdateApiKeyGroupResult } from '@/features/admin-usage/data/datasources/apiKeysDatasource'
export * as adminUsage from '@/features/admin-usage/data/datasources/adminUsageDatasource'
export * as apiKeys from '@/features/admin-usage/data/datasources/apiKeysDatasource'
