/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminSubscriptions — thin orchestrator composable for AdminSubscriptions.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminSubscriptionsQueryStore } from '@/features/admin-subscriptions/presentation/stores/adminSubscriptionsQueryStore'
import { useAdminSubscriptionsActionStore } from '@/features/admin-subscriptions/presentation/stores/adminSubscriptionsActionStore'

export function useAdminSubscriptions() {
  const q_adminSubscriptionsQueryStore = useAdminSubscriptionsQueryStore()
  const a_adminSubscriptionsActionStore = useAdminSubscriptionsActionStore()
  return {
    ...q_adminSubscriptionsQueryStore,
    ...a_adminSubscriptionsActionStore,
  }
}
