/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { list, listWithEtag, getById, getBatchSummaries, create, duplicate, update, checkMixedChannelRisk, deleteAccount, toggleStatus, testAccount, refreshCredentials, applyOAuthCredentials, getStats, clearError, getUsage, clearRateLimit, recoverState, resetAccountQuota, getTempUnschedulableStatus, resetTempUnschedulable, generateAuthUrl, exchangeCode, batchCreate, batchUpdateCredentials, bulkUpdate, getTodayStats, getBatchTodayStats, setSchedulable, getAvailableModels, syncUpstreamModels, syncUpstreamModelsPreview, previewFromCrs, syncFromCrs, exportData, importData, importCodexSession, createOpenAICodexPAT, getAntigravityDefaultModelMapping, refreshOpenAIToken, revertProxyFallback, batchClearError, batchRefresh, setPrivacy, queryOpenAIQuota, resetOpenAIQuota, createSparkShadow, getUpstreamBillingProbeSettings, updateUpstreamBillingProbeSettings, setUpstreamBillingProbeEnabled, probeUpstreamBilling, probeUpstreamBillingBatch, accountsAPI } from '@/features/admin-accounts/data/datasources/adminAccountsDatasource'
export type { AccountListWithEtagResult, AccountSummary, BatchTodayStatsResponse, SyncUpstreamModelsResult, SyncUpstreamPreviewParams, CRSPreviewAccount, PreviewFromCRSResult, BatchOperationResult, OpenAIRateLimitWindow, OpenAIRateLimit, OpenAIAdditionalRateLimit, OpenAIRateLimitResetCreditDetail, OpenAIRateLimitResetCredits, OpenAIQuotaUsage, OpenAIQuotaResetCredit, OpenAIQuotaResetResult, SparkShadowCreatePayload } from '@/features/admin-accounts/data/datasources/adminAccountsDatasource'
export { default } from '@/features/admin-accounts/data/datasources/adminAccountsDatasource'
export { refreshAntigravityToken } from '@/features/admin-accounts/data/datasources/antigravityDatasource'
export type { AntigravityAuthUrlResponse, AntigravityAuthUrlRequest, AntigravityExchangeCodeRequest, AntigravityTokenInfo } from '@/features/admin-accounts/data/datasources/antigravityDatasource'
export { getCapabilities } from '@/features/admin-accounts/data/datasources/geminiDatasource'
export type { GeminiAuthUrlResponse, GeminiOAuthCapabilities, GeminiAuthUrlRequest, GeminiExchangeCodeRequest, GeminiTokenInfo } from '@/features/admin-accounts/data/datasources/geminiDatasource'
export { getGrokSSOImportTimeout, refreshGrokToken, queryQuota, resetQuota, createFromSSO } from '@/features/admin-accounts/data/datasources/grokDatasource'
export type { GrokAuthUrlResponse, GrokAuthUrlRequest, GrokExchangeCodeRequest, GrokTokenInfo, GrokSSOToOAuthRequest, GrokSSOToOAuthItemResult, GrokSSOToOAuthResponse, GrokQuotaSnapshot, GrokQuotaProbeResult, GrokQuotaResetResult, GrokBillingSummary, GrokQuotaWindow } from '@/features/admin-accounts/data/datasources/grokDatasource'
export { listByAccount, deletePlan, listResults, scheduledTestsAPI } from '@/features/admin-accounts/data/datasources/scheduledTestsDatasource'
export * as adminAccounts from '@/features/admin-accounts/data/datasources/adminAccountsDatasource'
export * as antigravity from '@/features/admin-accounts/data/datasources/antigravityDatasource'
export * as gemini from '@/features/admin-accounts/data/datasources/geminiDatasource'
export * as grok from '@/features/admin-accounts/data/datasources/grokDatasource'
export * as scheduledTests from '@/features/admin-accounts/data/datasources/scheduledTestsDatasource'
