/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useSubscriptions — thin orchestrator composable for Subscriptions.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useSubscriptionsQueryStore } from '@/features/subscriptions/presentation/stores/subscriptionsQueryStore'

export function useSubscriptions() {
  const q_subscriptionsQueryStore = useSubscriptionsQueryStore()
  return {
    ...q_subscriptionsQueryStore,
  }
}
