/**
 * AffiliateActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAffiliateActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminAffiliatesRepository } from '@/features/affiliate/domain/repositories/adminAffiliatesRepository'
import { adminAffiliatesRepository as default_adminAffiliates_repo } from '@/features/affiliate/data/repositories/adminAffiliatesRepositoryImpl'

export function createAffiliateActionStore(adminAffiliatesRepo: AdminAffiliatesRepository = default_adminAffiliates_repo) {
  return defineStore('affiliate/action', () => {
    const loading = reactive<Record<string, boolean>>({ lookupUsers: false, updateUserSettings: false, clearUserSettings: false, batchSetRate: false })
    const errors = reactive<Record<string, unknown>>({ lookupUsers: null as unknown, updateUserSettings: null as unknown, clearUserSettings: null as unknown, batchSetRate: null as unknown })

  const lookupUsers: AdminAffiliatesRepository['lookupUsers'] = ((...args: unknown[]) => {
    loading.lookupUsers = true
    errors.lookupUsers = null
    return Promise.resolve()
      .then(() => (adminAffiliatesRepo.lookupUsers as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.lookupUsers = error; throw error })
      .finally(() => { loading.lookupUsers = false })
  }) as AdminAffiliatesRepository['lookupUsers']

  const updateUserSettings: AdminAffiliatesRepository['updateUserSettings'] = ((...args: unknown[]) => {
    loading.updateUserSettings = true
    errors.updateUserSettings = null
    return Promise.resolve()
      .then(() => (adminAffiliatesRepo.updateUserSettings as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateUserSettings = error; throw error })
      .finally(() => { loading.updateUserSettings = false })
  }) as AdminAffiliatesRepository['updateUserSettings']

  const clearUserSettings: AdminAffiliatesRepository['clearUserSettings'] = ((...args: unknown[]) => {
    loading.clearUserSettings = true
    errors.clearUserSettings = null
    return Promise.resolve()
      .then(() => (adminAffiliatesRepo.clearUserSettings as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.clearUserSettings = error; throw error })
      .finally(() => { loading.clearUserSettings = false })
  }) as AdminAffiliatesRepository['clearUserSettings']

  const batchSetRate: AdminAffiliatesRepository['batchSetRate'] = ((...args: unknown[]) => {
    loading.batchSetRate = true
    errors.batchSetRate = null
    return Promise.resolve()
      .then(() => (adminAffiliatesRepo.batchSetRate as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchSetRate = error; throw error })
      .finally(() => { loading.batchSetRate = false })
  }) as AdminAffiliatesRepository['batchSetRate']

    return { loading, errors, lookupUsers, updateUserSettings, clearUserSettings, batchSetRate }
  })
}

export const useAffiliateActionStore = createAffiliateActionStore()
