/**
 * AffiliateQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAffiliateQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminAffiliatesRepository } from '@/features/affiliate/domain/repositories/adminAffiliatesRepository'
import { adminAffiliatesRepository as default_adminAffiliates_repo } from '@/features/affiliate/data/repositories/adminAffiliatesRepositoryImpl'

export function createAffiliateQueryStore(adminAffiliatesRepo: AdminAffiliatesRepository = default_adminAffiliates_repo) {
  return defineStore('affiliate/query', () => {
    const loading = reactive<Record<string, boolean>>({ listUsers: false, listInviteRecords: false, listRebateRecords: false, listTransferRecords: false, getUserOverview: false })
    const errors = reactive<Record<string, unknown>>({ listUsers: null as unknown, listInviteRecords: null as unknown, listRebateRecords: null as unknown, listTransferRecords: null as unknown, getUserOverview: null as unknown })

  const listUsers: AdminAffiliatesRepository['listUsers'] = ((...args: unknown[]) => {
    loading.listUsers = true
    errors.listUsers = null
    return Promise.resolve()
      .then(() => (adminAffiliatesRepo.listUsers as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listUsers = error; throw error })
      .finally(() => { loading.listUsers = false })
  }) as AdminAffiliatesRepository['listUsers']

  const listInviteRecords: AdminAffiliatesRepository['listInviteRecords'] = ((...args: unknown[]) => {
    loading.listInviteRecords = true
    errors.listInviteRecords = null
    return Promise.resolve()
      .then(() => (adminAffiliatesRepo.listInviteRecords as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listInviteRecords = error; throw error })
      .finally(() => { loading.listInviteRecords = false })
  }) as AdminAffiliatesRepository['listInviteRecords']

  const listRebateRecords: AdminAffiliatesRepository['listRebateRecords'] = ((...args: unknown[]) => {
    loading.listRebateRecords = true
    errors.listRebateRecords = null
    return Promise.resolve()
      .then(() => (adminAffiliatesRepo.listRebateRecords as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listRebateRecords = error; throw error })
      .finally(() => { loading.listRebateRecords = false })
  }) as AdminAffiliatesRepository['listRebateRecords']

  const listTransferRecords: AdminAffiliatesRepository['listTransferRecords'] = ((...args: unknown[]) => {
    loading.listTransferRecords = true
    errors.listTransferRecords = null
    return Promise.resolve()
      .then(() => (adminAffiliatesRepo.listTransferRecords as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listTransferRecords = error; throw error })
      .finally(() => { loading.listTransferRecords = false })
  }) as AdminAffiliatesRepository['listTransferRecords']

  const getUserOverview: AdminAffiliatesRepository['getUserOverview'] = ((...args: unknown[]) => {
    loading.getUserOverview = true
    errors.getUserOverview = null
    return Promise.resolve()
      .then(() => (adminAffiliatesRepo.getUserOverview as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserOverview = error; throw error })
      .finally(() => { loading.getUserOverview = false })
  }) as AdminAffiliatesRepository['getUserOverview']

    return { loading, errors, listUsers, listInviteRecords, listRebateRecords, listTransferRecords, getUserOverview }
  })
}

export const useAffiliateQueryStore = createAffiliateQueryStore()
