/**
 * AdminBackupQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminBackupQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminBackupRepository } from '@/features/admin-backup/domain/repositories/adminBackupRepository'
import type { DataManagementRepository } from '@/features/admin-backup/domain/repositories/dataManagementRepository'
import { adminBackupRepository as default_adminBackup_repo } from '@/features/admin-backup/data/repositories/adminBackupRepositoryImpl'
import { dataManagementRepository as default_dataManagement_repo } from '@/features/admin-backup/data/repositories/dataManagementRepositoryImpl'

export function createAdminBackupQueryStore(adminBackupRepo: AdminBackupRepository = default_adminBackup_repo, dataManagementRepo: DataManagementRepository = default_dataManagement_repo) {
  return defineStore('adminBackup/query', () => {
    const loading = reactive<Record<string, boolean>>({ getS3Config: false, getImageStorageConfig: false, getSchedule: false, listBackups: false, getBackup: false, getDownloadURL: false, getAgentHealth: false, getConfig: false, listSourceProfiles: false, listS3Profiles: false, listBackupJobs: false, getBackupJob: false })
    const errors = reactive<Record<string, unknown>>({ getS3Config: null as unknown, getImageStorageConfig: null as unknown, getSchedule: null as unknown, listBackups: null as unknown, getBackup: null as unknown, getDownloadURL: null as unknown, getAgentHealth: null as unknown, getConfig: null as unknown, listSourceProfiles: null as unknown, listS3Profiles: null as unknown, listBackupJobs: null as unknown, getBackupJob: null as unknown })

  const getS3Config: AdminBackupRepository['getS3Config'] = ((...args: unknown[]) => {
    loading.getS3Config = true
    errors.getS3Config = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.getS3Config as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getS3Config = error; throw error })
      .finally(() => { loading.getS3Config = false })
  }) as AdminBackupRepository['getS3Config']

  const getImageStorageConfig: AdminBackupRepository['getImageStorageConfig'] = ((...args: unknown[]) => {
    loading.getImageStorageConfig = true
    errors.getImageStorageConfig = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.getImageStorageConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getImageStorageConfig = error; throw error })
      .finally(() => { loading.getImageStorageConfig = false })
  }) as AdminBackupRepository['getImageStorageConfig']

  const getSchedule: AdminBackupRepository['getSchedule'] = ((...args: unknown[]) => {
    loading.getSchedule = true
    errors.getSchedule = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.getSchedule as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getSchedule = error; throw error })
      .finally(() => { loading.getSchedule = false })
  }) as AdminBackupRepository['getSchedule']

  const listBackups: AdminBackupRepository['listBackups'] = ((...args: unknown[]) => {
    loading.listBackups = true
    errors.listBackups = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.listBackups as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listBackups = error; throw error })
      .finally(() => { loading.listBackups = false })
  }) as AdminBackupRepository['listBackups']

  const getBackup: AdminBackupRepository['getBackup'] = ((...args: unknown[]) => {
    loading.getBackup = true
    errors.getBackup = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.getBackup as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getBackup = error; throw error })
      .finally(() => { loading.getBackup = false })
  }) as AdminBackupRepository['getBackup']

  const getDownloadURL: AdminBackupRepository['getDownloadURL'] = ((...args: unknown[]) => {
    loading.getDownloadURL = true
    errors.getDownloadURL = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.getDownloadURL as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getDownloadURL = error; throw error })
      .finally(() => { loading.getDownloadURL = false })
  }) as AdminBackupRepository['getDownloadURL']

  const getAgentHealth: DataManagementRepository['getAgentHealth'] = ((...args: unknown[]) => {
    loading.getAgentHealth = true
    errors.getAgentHealth = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.getAgentHealth as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAgentHealth = error; throw error })
      .finally(() => { loading.getAgentHealth = false })
  }) as DataManagementRepository['getAgentHealth']

  const getConfig: DataManagementRepository['getConfig'] = ((...args: unknown[]) => {
    loading.getConfig = true
    errors.getConfig = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.getConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getConfig = error; throw error })
      .finally(() => { loading.getConfig = false })
  }) as DataManagementRepository['getConfig']

  const listSourceProfiles: DataManagementRepository['listSourceProfiles'] = ((...args: unknown[]) => {
    loading.listSourceProfiles = true
    errors.listSourceProfiles = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.listSourceProfiles as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listSourceProfiles = error; throw error })
      .finally(() => { loading.listSourceProfiles = false })
  }) as DataManagementRepository['listSourceProfiles']

  const listS3Profiles: DataManagementRepository['listS3Profiles'] = ((...args: unknown[]) => {
    loading.listS3Profiles = true
    errors.listS3Profiles = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.listS3Profiles as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listS3Profiles = error; throw error })
      .finally(() => { loading.listS3Profiles = false })
  }) as DataManagementRepository['listS3Profiles']

  const listBackupJobs: DataManagementRepository['listBackupJobs'] = ((...args: unknown[]) => {
    loading.listBackupJobs = true
    errors.listBackupJobs = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.listBackupJobs as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listBackupJobs = error; throw error })
      .finally(() => { loading.listBackupJobs = false })
  }) as DataManagementRepository['listBackupJobs']

  const getBackupJob: DataManagementRepository['getBackupJob'] = ((...args: unknown[]) => {
    loading.getBackupJob = true
    errors.getBackupJob = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.getBackupJob as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getBackupJob = error; throw error })
      .finally(() => { loading.getBackupJob = false })
  }) as DataManagementRepository['getBackupJob']

    return { loading, errors, getS3Config, getImageStorageConfig, getSchedule, listBackups, getBackup, getDownloadURL, getAgentHealth, getConfig, listSourceProfiles, listS3Profiles, listBackupJobs, getBackupJob }
  })
}

export const useAdminBackupQueryStore = createAdminBackupQueryStore()
