/**
 * AdminBackupActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminBackupActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminBackupRepository } from '@/features/admin-backup/domain/repositories/adminBackupRepository'
import type { DataManagementRepository } from '@/features/admin-backup/domain/repositories/dataManagementRepository'
import { adminBackupRepository as default_adminBackup_repo } from '@/features/admin-backup/data/repositories/adminBackupRepositoryImpl'
import { dataManagementRepository as default_dataManagement_repo } from '@/features/admin-backup/data/repositories/dataManagementRepositoryImpl'

export function createAdminBackupActionStore(adminBackupRepo: AdminBackupRepository = default_adminBackup_repo, dataManagementRepo: DataManagementRepository = default_dataManagement_repo) {
  return defineStore('adminBackup/action', () => {
    const loading = reactive<Record<string, boolean>>({ updateS3Config: false, testS3Connection: false, updateImageStorageConfig: false, testImageStorageConnection: false, updateSchedule: false, createBackup: false, deleteBackup: false, restoreBackup: false, updateConfig: false, testS3: false, createSourceProfile: false, updateSourceProfile: false, deleteSourceProfile: false, setActiveSourceProfile: false, createS3Profile: false, updateS3Profile: false, deleteS3Profile: false, setActiveS3Profile: false, createBackupJob: false })
    const errors = reactive<Record<string, unknown>>({ updateS3Config: null as unknown, testS3Connection: null as unknown, updateImageStorageConfig: null as unknown, testImageStorageConnection: null as unknown, updateSchedule: null as unknown, createBackup: null as unknown, deleteBackup: null as unknown, restoreBackup: null as unknown, updateConfig: null as unknown, testS3: null as unknown, createSourceProfile: null as unknown, updateSourceProfile: null as unknown, deleteSourceProfile: null as unknown, setActiveSourceProfile: null as unknown, createS3Profile: null as unknown, updateS3Profile: null as unknown, deleteS3Profile: null as unknown, setActiveS3Profile: null as unknown, createBackupJob: null as unknown })

  const updateS3Config: AdminBackupRepository['updateS3Config'] = ((...args: unknown[]) => {
    loading.updateS3Config = true
    errors.updateS3Config = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.updateS3Config as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateS3Config = error; throw error })
      .finally(() => { loading.updateS3Config = false })
  }) as AdminBackupRepository['updateS3Config']

  const testS3Connection: AdminBackupRepository['testS3Connection'] = ((...args: unknown[]) => {
    loading.testS3Connection = true
    errors.testS3Connection = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.testS3Connection as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.testS3Connection = error; throw error })
      .finally(() => { loading.testS3Connection = false })
  }) as AdminBackupRepository['testS3Connection']

  const updateImageStorageConfig: AdminBackupRepository['updateImageStorageConfig'] = ((...args: unknown[]) => {
    loading.updateImageStorageConfig = true
    errors.updateImageStorageConfig = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.updateImageStorageConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateImageStorageConfig = error; throw error })
      .finally(() => { loading.updateImageStorageConfig = false })
  }) as AdminBackupRepository['updateImageStorageConfig']

  const testImageStorageConnection: AdminBackupRepository['testImageStorageConnection'] = ((...args: unknown[]) => {
    loading.testImageStorageConnection = true
    errors.testImageStorageConnection = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.testImageStorageConnection as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.testImageStorageConnection = error; throw error })
      .finally(() => { loading.testImageStorageConnection = false })
  }) as AdminBackupRepository['testImageStorageConnection']

  const updateSchedule: AdminBackupRepository['updateSchedule'] = ((...args: unknown[]) => {
    loading.updateSchedule = true
    errors.updateSchedule = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.updateSchedule as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateSchedule = error; throw error })
      .finally(() => { loading.updateSchedule = false })
  }) as AdminBackupRepository['updateSchedule']

  const createBackup: AdminBackupRepository['createBackup'] = ((...args: unknown[]) => {
    loading.createBackup = true
    errors.createBackup = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.createBackup as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createBackup = error; throw error })
      .finally(() => { loading.createBackup = false })
  }) as AdminBackupRepository['createBackup']

  const deleteBackup: AdminBackupRepository['deleteBackup'] = ((...args: unknown[]) => {
    loading.deleteBackup = true
    errors.deleteBackup = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.deleteBackup as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteBackup = error; throw error })
      .finally(() => { loading.deleteBackup = false })
  }) as AdminBackupRepository['deleteBackup']

  const restoreBackup: AdminBackupRepository['restoreBackup'] = ((...args: unknown[]) => {
    loading.restoreBackup = true
    errors.restoreBackup = null
    return Promise.resolve()
      .then(() => (adminBackupRepo.restoreBackup as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.restoreBackup = error; throw error })
      .finally(() => { loading.restoreBackup = false })
  }) as AdminBackupRepository['restoreBackup']

  const updateConfig: DataManagementRepository['updateConfig'] = ((...args: unknown[]) => {
    loading.updateConfig = true
    errors.updateConfig = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.updateConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateConfig = error; throw error })
      .finally(() => { loading.updateConfig = false })
  }) as DataManagementRepository['updateConfig']

  const testS3: DataManagementRepository['testS3'] = ((...args: unknown[]) => {
    loading.testS3 = true
    errors.testS3 = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.testS3 as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.testS3 = error; throw error })
      .finally(() => { loading.testS3 = false })
  }) as DataManagementRepository['testS3']

  const createSourceProfile: DataManagementRepository['createSourceProfile'] = ((...args: unknown[]) => {
    loading.createSourceProfile = true
    errors.createSourceProfile = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.createSourceProfile as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createSourceProfile = error; throw error })
      .finally(() => { loading.createSourceProfile = false })
  }) as DataManagementRepository['createSourceProfile']

  const updateSourceProfile: DataManagementRepository['updateSourceProfile'] = ((...args: unknown[]) => {
    loading.updateSourceProfile = true
    errors.updateSourceProfile = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.updateSourceProfile as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateSourceProfile = error; throw error })
      .finally(() => { loading.updateSourceProfile = false })
  }) as DataManagementRepository['updateSourceProfile']

  const deleteSourceProfile: DataManagementRepository['deleteSourceProfile'] = ((...args: unknown[]) => {
    loading.deleteSourceProfile = true
    errors.deleteSourceProfile = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.deleteSourceProfile as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteSourceProfile = error; throw error })
      .finally(() => { loading.deleteSourceProfile = false })
  }) as DataManagementRepository['deleteSourceProfile']

  const setActiveSourceProfile: DataManagementRepository['setActiveSourceProfile'] = ((...args: unknown[]) => {
    loading.setActiveSourceProfile = true
    errors.setActiveSourceProfile = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.setActiveSourceProfile as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.setActiveSourceProfile = error; throw error })
      .finally(() => { loading.setActiveSourceProfile = false })
  }) as DataManagementRepository['setActiveSourceProfile']

  const createS3Profile: DataManagementRepository['createS3Profile'] = ((...args: unknown[]) => {
    loading.createS3Profile = true
    errors.createS3Profile = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.createS3Profile as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createS3Profile = error; throw error })
      .finally(() => { loading.createS3Profile = false })
  }) as DataManagementRepository['createS3Profile']

  const updateS3Profile: DataManagementRepository['updateS3Profile'] = ((...args: unknown[]) => {
    loading.updateS3Profile = true
    errors.updateS3Profile = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.updateS3Profile as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateS3Profile = error; throw error })
      .finally(() => { loading.updateS3Profile = false })
  }) as DataManagementRepository['updateS3Profile']

  const deleteS3Profile: DataManagementRepository['deleteS3Profile'] = ((...args: unknown[]) => {
    loading.deleteS3Profile = true
    errors.deleteS3Profile = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.deleteS3Profile as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteS3Profile = error; throw error })
      .finally(() => { loading.deleteS3Profile = false })
  }) as DataManagementRepository['deleteS3Profile']

  const setActiveS3Profile: DataManagementRepository['setActiveS3Profile'] = ((...args: unknown[]) => {
    loading.setActiveS3Profile = true
    errors.setActiveS3Profile = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.setActiveS3Profile as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.setActiveS3Profile = error; throw error })
      .finally(() => { loading.setActiveS3Profile = false })
  }) as DataManagementRepository['setActiveS3Profile']

  const createBackupJob: DataManagementRepository['createBackupJob'] = ((...args: unknown[]) => {
    loading.createBackupJob = true
    errors.createBackupJob = null
    return Promise.resolve()
      .then(() => (dataManagementRepo.createBackupJob as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createBackupJob = error; throw error })
      .finally(() => { loading.createBackupJob = false })
  }) as DataManagementRepository['createBackupJob']

    return { loading, errors, updateS3Config, testS3Connection, updateImageStorageConfig, testImageStorageConnection, updateSchedule, createBackup, deleteBackup, restoreBackup, updateConfig, testS3, createSourceProfile, updateSourceProfile, deleteSourceProfile, setActiveSourceProfile, createS3Profile, updateS3Profile, deleteS3Profile, setActiveS3Profile, createBackupJob }
  })
}

export const useAdminBackupActionStore = createAdminBackupActionStore()
