/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminChannelMonitor — thin orchestrator composable for AdminChannelMonitor.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminChannelMonitorQueryStore } from '@/features/admin-channel-monitor/presentation/stores/adminChannelMonitorQueryStore'
import { useAdminChannelMonitorActionStore } from '@/features/admin-channel-monitor/presentation/stores/adminChannelMonitorActionStore'

export function useAdminChannelMonitor() {
  const q_adminChannelMonitorQueryStore = useAdminChannelMonitorQueryStore()
  const a_adminChannelMonitorActionStore = useAdminChannelMonitorActionStore()
  return {
    ...q_adminChannelMonitorQueryStore,
    ...a_adminChannelMonitorActionStore,
  }
}
