/**
 * AdminAuditQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminAuditQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminAuditRepository } from '@/features/admin-audit/domain/repositories/adminAuditRepository'
import { adminAuditRepository as default_adminAudit_repo } from '@/features/admin-audit/data/repositories/adminAuditRepositoryImpl'

export function createAdminAuditQueryStore(adminAuditRepo: AdminAuditRepository = default_adminAudit_repo) {
  return defineStore('adminAudit/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, get: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, get: null as unknown })

  const list: AdminAuditRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (adminAuditRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as AdminAuditRepository['list']

  const get: AdminAuditRepository['get'] = ((...args: unknown[]) => {
    loading.get = true
    errors.get = null
    return Promise.resolve()
      .then(() => (adminAuditRepo.get as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.get = error; throw error })
      .finally(() => { loading.get = false })
  }) as AdminAuditRepository['get']

    return { loading, errors, list, get }
  })
}

export const useAdminAuditQueryStore = createAdminAuditQueryStore()
