/**
 * AdminAuditActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminAuditActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminAuditRepository } from '@/features/admin-audit/domain/repositories/adminAuditRepository'
import { adminAuditRepository as default_adminAudit_repo } from '@/features/admin-audit/data/repositories/adminAuditRepositoryImpl'

export function createAdminAuditActionStore(adminAuditRepo: AdminAuditRepository = default_adminAudit_repo) {
  return defineStore('adminAudit/action', () => {
    const loading = reactive<Record<string, boolean>>({ clear: false })
    const errors = reactive<Record<string, unknown>>({ clear: null as unknown })

  const clear: AdminAuditRepository['clear'] = ((...args: unknown[]) => {
    loading.clear = true
    errors.clear = null
    return Promise.resolve()
      .then(() => (adminAuditRepo.clear as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.clear = error; throw error })
      .finally(() => { loading.clear = false })
  }) as AdminAuditRepository['clear']

    return { loading, errors, clear }
  })
}

export const useAdminAuditActionStore = createAdminAuditActionStore()
