/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminGroups — thin orchestrator composable for AdminGroups.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminGroupsQueryStore } from '@/features/admin-groups/presentation/stores/adminGroupsQueryStore'
import { useAdminGroupsActionStore } from '@/features/admin-groups/presentation/stores/adminGroupsActionStore'

export function useAdminGroups() {
  const q_adminGroupsQueryStore = useAdminGroupsQueryStore()
  const a_adminGroupsActionStore = useAdminGroupsActionStore()
  return {
    ...q_adminGroupsQueryStore,
    ...a_adminGroupsActionStore,
  }
}
