/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */
export { default as ProxiesPage } from './presentation/pages/ProxiesPage.vue'


// Route fragment — import in core/routes/index.ts

// export const adminProxiesRoutes: RouteRecordRaw[] = [{ path: '/todo', component: ProxiesPage }]
