/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { submitBatchImageJob, getBatchImageJob, listBatchImageJobs, listBatchImageModels, listBatchImageItems, cancelBatchImageJob, downloadBatchImageZip, getBatchImageItemContent, deleteBatchImageJobRecord, saveBlob } from '@/features/batch-image/data/datasources/batchImageDatasource'
export type { BatchImageStatus, BatchImageSubmitItem, BatchImageReferenceImage, BatchImageSubmitRequest, BatchImageJob, BatchImageItem, BatchImageItemsResponse, BatchImageJobsResponse, BatchImageModel, BatchImageModelsResponse, BatchImageJobsListOptions } from '@/features/batch-image/data/datasources/batchImageDatasource'
