/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminRiskControl — thin orchestrator composable for AdminRiskControl.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminRiskControlQueryStore } from '@/features/admin-risk-control/presentation/stores/adminRiskControlQueryStore'
import { useAdminRiskControlActionStore } from '@/features/admin-risk-control/presentation/stores/adminRiskControlActionStore'

export function useAdminRiskControl() {
  const q_adminRiskControlQueryStore = useAdminRiskControlQueryStore()
  const a_adminRiskControlActionStore = useAdminRiskControlActionStore()
  return {
    ...q_adminRiskControlQueryStore,
    ...a_adminRiskControlActionStore,
  }
}
