/**
 * AdminSubscriptionsQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminSubscriptionsQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminSubscriptionsRepository } from '@/features/admin-subscriptions/domain/repositories/adminSubscriptionsRepository'
import { adminSubscriptionsRepository as default_adminSubscriptions_repo } from '@/features/admin-subscriptions/data/repositories/adminSubscriptionsRepositoryImpl'

export function createAdminSubscriptionsQueryStore(adminSubscriptionsRepo: AdminSubscriptionsRepository = default_adminSubscriptions_repo) {
  return defineStore('adminSubscriptions/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, getById: false, getProgress: false, listByGroup: false, listByUser: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, getById: null as unknown, getProgress: null as unknown, listByGroup: null as unknown, listByUser: null as unknown })

  const list: AdminSubscriptionsRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as AdminSubscriptionsRepository['list']

  const getById: AdminSubscriptionsRepository['getById'] = ((...args: unknown[]) => {
    loading.getById = true
    errors.getById = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.getById as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getById = error; throw error })
      .finally(() => { loading.getById = false })
  }) as AdminSubscriptionsRepository['getById']

  const getProgress: AdminSubscriptionsRepository['getProgress'] = ((...args: unknown[]) => {
    loading.getProgress = true
    errors.getProgress = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.getProgress as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getProgress = error; throw error })
      .finally(() => { loading.getProgress = false })
  }) as AdminSubscriptionsRepository['getProgress']

  const listByGroup: AdminSubscriptionsRepository['listByGroup'] = ((...args: unknown[]) => {
    loading.listByGroup = true
    errors.listByGroup = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.listByGroup as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listByGroup = error; throw error })
      .finally(() => { loading.listByGroup = false })
  }) as AdminSubscriptionsRepository['listByGroup']

  const listByUser: AdminSubscriptionsRepository['listByUser'] = ((...args: unknown[]) => {
    loading.listByUser = true
    errors.listByUser = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.listByUser as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listByUser = error; throw error })
      .finally(() => { loading.listByUser = false })
  }) as AdminSubscriptionsRepository['listByUser']

    return { loading, errors, list, getById, getProgress, listByGroup, listByUser }
  })
}

export const useAdminSubscriptionsQueryStore = createAdminSubscriptionsQueryStore()
