/**
 * AdminSubscriptionsActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminSubscriptionsActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminSubscriptionsRepository } from '@/features/admin-subscriptions/domain/repositories/adminSubscriptionsRepository'
import { adminSubscriptionsRepository as default_adminSubscriptions_repo } from '@/features/admin-subscriptions/data/repositories/adminSubscriptionsRepositoryImpl'

export function createAdminSubscriptionsActionStore(adminSubscriptionsRepo: AdminSubscriptionsRepository = default_adminSubscriptions_repo) {
  return defineStore('adminSubscriptions/action', () => {
    const loading = reactive<Record<string, boolean>>({ assign: false, bulkAssign: false, extend: false, revoke: false, restore: false, resetQuota: false })
    const errors = reactive<Record<string, unknown>>({ assign: null as unknown, bulkAssign: null as unknown, extend: null as unknown, revoke: null as unknown, restore: null as unknown, resetQuota: null as unknown })

  const assign: AdminSubscriptionsRepository['assign'] = ((...args: unknown[]) => {
    loading.assign = true
    errors.assign = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.assign as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.assign = error; throw error })
      .finally(() => { loading.assign = false })
  }) as AdminSubscriptionsRepository['assign']

  const bulkAssign: AdminSubscriptionsRepository['bulkAssign'] = ((...args: unknown[]) => {
    loading.bulkAssign = true
    errors.bulkAssign = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.bulkAssign as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.bulkAssign = error; throw error })
      .finally(() => { loading.bulkAssign = false })
  }) as AdminSubscriptionsRepository['bulkAssign']

  const extend: AdminSubscriptionsRepository['extend'] = ((...args: unknown[]) => {
    loading.extend = true
    errors.extend = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.extend as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.extend = error; throw error })
      .finally(() => { loading.extend = false })
  }) as AdminSubscriptionsRepository['extend']

  const revoke: AdminSubscriptionsRepository['revoke'] = ((...args: unknown[]) => {
    loading.revoke = true
    errors.revoke = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.revoke as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.revoke = error; throw error })
      .finally(() => { loading.revoke = false })
  }) as AdminSubscriptionsRepository['revoke']

  const restore: AdminSubscriptionsRepository['restore'] = ((...args: unknown[]) => {
    loading.restore = true
    errors.restore = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.restore as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.restore = error; throw error })
      .finally(() => { loading.restore = false })
  }) as AdminSubscriptionsRepository['restore']

  const resetQuota: AdminSubscriptionsRepository['resetQuota'] = ((...args: unknown[]) => {
    loading.resetQuota = true
    errors.resetQuota = null
    return Promise.resolve()
      .then(() => (adminSubscriptionsRepo.resetQuota as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.resetQuota = error; throw error })
      .finally(() => { loading.resetQuota = false })
  }) as AdminSubscriptionsRepository['resetQuota']

    return { loading, errors, assign, bulkAssign, extend, revoke, restore, resetQuota }
  })
}

export const useAdminSubscriptionsActionStore = createAdminSubscriptionsActionStore()
