import type { CustomEndpoint } from '@/core/models/domain/customEndpoint'
import type { CustomMenuItem } from '@/core/models/domain/customMenuItem'
import type { LoginAgreementDocument } from '@/core/models/domain/loginAgreementDocument'
import type { NotifyEmailEntry } from '@/core/models/domain/notifyEmailEntry'
import type { PlatformQuotaLimits } from './platformQuotaLimits'
import type { DefaultSubscriptionSetting } from './defaultSubscriptionSetting'
import type { ClientIpResolutionStatus } from './clientIpResolutionStatus'
import type { OpenAIFastPolicySettings } from './openAIFastPolicySettings'
import type { AuthSourceDefaultsValue } from './authSourceDefaultsValue'
import type { PlatformType } from '@/features/admin-settings/enums/platformType'
import type { ClientIpResolutionMode } from '@/features/admin-settings/enums/clientIpResolutionMode'
import type { AuthSourceType } from '@/features/admin-settings/enums/authSourceType'

export type DefaultPlatformQuotasMap = Partial<Record<PlatformType, PlatformQuotaLimits>>
export type AuthSourceDefaultsState = Record<AuthSourceType, AuthSourceDefaultsValue>

export class SystemSettings {
  registrationEnabled!: boolean
  emailVerifyEnabled!: boolean
  registrationEmailSuffixWhitelist!: string[]
  promoCodeEnabled!: boolean
  passwordResetEnabled!: boolean
  frontendUrl!: string
  invitationCodeEnabled!: boolean
  totpEnabled!: boolean
  totpEncryptionKeyConfigured!: boolean
  sessionBindingEnabled!: boolean
  stepUpEnabled!: boolean
  auditLogRetentionDays!: number
  loginAgreementEnabled!: boolean
  loginAgreementMode!: 'modal' | 'checkbox' | string
  loginAgreementUpdatedAt!: string
  loginAgreementDocuments!: LoginAgreementDocument[]
  defaultBalance!: number
  affiliateRebateRate!: number
  affiliateRebateFreezeHours!: number
  affiliateRebateDurationDays!: number
  affiliateRebatePerInviteeCap!: number
  affiliateAdminRechargeEnabled!: boolean
  defaultConcurrency!: number
  defaultUserRpmLimit!: number
  defaultSubscriptions!: DefaultSubscriptionSetting[]
  defaultPlatformQuotas?: DefaultPlatformQuotasMap
  siteName!: string
  siteLogo!: string
  siteSubtitle!: string
  apiBaseUrl!: string
  contactInfo!: string
  docUrl!: string
  homeContent!: string
  hideCcsImportButton!: boolean
  tableDefaultPageSize!: number
  tablePageSizeOptions!: number[]
  backendModeEnabled!: boolean
  streamModePerformanceEnabled!: boolean
  customMenuItems!: CustomMenuItem[]
  customEndpoints!: CustomEndpoint[]
  smtpHost!: string
  smtpPort!: number
  smtpUsername!: string
  smtpPasswordConfigured!: boolean
  smtpFromEmail!: string
  smtpFromName!: string
  smtpUseTls!: boolean
  turnstileEnabled!: boolean
  turnstileSiteKey!: string
  turnstileSecretKeyConfigured!: boolean
  recaptchaEnabled!: boolean
  recaptchaSiteKey!: string
  recaptchaSecretKeyConfigured!: boolean
  capEnabled!: boolean
  capApiEndpoint!: string
  capSecretKeyConfigured!: boolean
  localCaptchaEnabled!: boolean
  apiKeyAclTrustForwardedIp!: boolean
  clientIpResolutionMode!: ClientIpResolutionMode
  clientIpTrustedProxies!: string[]
  clientIpResolutionStatus!: ClientIpResolutionStatus
  linuxdoConnectEnabled!: boolean
  linuxdoConnectClientId!: string
  linuxdoConnectClientSecretConfigured!: boolean
  linuxdoConnectRedirectUrl!: string
  dingtalkConnectEnabled!: boolean
  dingtalkConnectClientId!: string
  dingtalkConnectClientSecretConfigured!: boolean
  dingtalkConnectRedirectUrl!: string
  dingtalkConnectCorpRestrictionPolicy!: string
  dingtalkConnectInternalCorpId!: string
  dingtalkConnectBypassRegistration!: boolean
  dingtalkConnectSyncCorpEmail!: boolean
  dingtalkConnectSyncDisplayName!: boolean
  dingtalkConnectSyncDept!: boolean
  dingtalkConnectSyncCorpEmailAttrKey!: string
  dingtalkConnectSyncDisplayNameAttrKey!: string
  dingtalkConnectSyncDeptAttrKey!: string
  dingtalkConnectSyncCorpEmailAttrName!: string
  dingtalkConnectSyncDisplayNameAttrName!: string
  dingtalkConnectSyncDeptAttrName!: string
  wechatConnectEnabled!: boolean
  wechatConnectAppId!: string
  wechatConnectAppSecretConfigured!: boolean
  wechatConnectOpenAppId?: string
  wechatConnectOpenAppSecretConfigured?: boolean
  wechatConnectMpAppId?: string
  wechatConnectMpAppSecretConfigured?: boolean
  wechatConnectMobileAppId?: string
  wechatConnectMobileAppSecretConfigured?: boolean
  wechatConnectOpenEnabled?: boolean
  wechatConnectMpEnabled?: boolean
  wechatConnectMobileEnabled?: boolean
  wechatConnectMode!: string
  wechatConnectScopes!: string
  wechatConnectRedirectUrl!: string
  wechatConnectFrontendRedirectUrl!: string
  oidcConnectEnabled!: boolean
  oidcConnectProviderName!: string
  oidcConnectClientId!: string
  oidcConnectClientSecretConfigured!: boolean
  oidcConnectIssuerUrl!: string
  oidcConnectDiscoveryUrl!: string
  oidcConnectAuthorizeUrl!: string
  oidcConnectTokenUrl!: string
  oidcConnectUserinfoUrl!: string
  oidcConnectJwksUrl!: string
  oidcConnectScopes!: string
  oidcConnectRedirectUrl!: string
  oidcConnectFrontendRedirectUrl!: string
  oidcConnectTokenAuthMethod!: string
  oidcConnectUsePkce!: boolean
  oidcConnectValidateIdToken!: boolean
  oidcConnectAllowedSigningAlgs!: string
  oidcConnectClockSkewSeconds!: number
  oidcConnectRequireEmailVerified!: boolean
  oidcConnectUserinfoEmailPath!: string
  oidcConnectUserinfoIdPath!: string
  oidcConnectUserinfoUsernamePath!: string
  githubOauthEnabled!: boolean
  githubOauthClientId!: string
  githubOauthClientSecretConfigured!: boolean
  githubOauthRedirectUrl!: string
  githubOauthFrontendRedirectUrl!: string
  googleOauthEnabled!: boolean
  googleOauthClientId!: string
  googleOauthClientSecretConfigured!: boolean
  googleOauthRedirectUrl!: string
  googleOauthFrontendRedirectUrl!: string
  enableModelFallback!: boolean
  fallbackModelAnthropic!: string
  fallbackModelOpenai!: string
  fallbackModelGemini!: string
  fallbackModelAntigravity!: string
  enableIdentityPatch!: boolean
  identityPatchPrompt!: string
  opsMonitoringEnabled!: boolean
  opsRealtimeMonitoringEnabled!: boolean
  opsQueryModeDefault!: 'auto' | 'raw' | 'preagg' | string
  opsMetricsIntervalSeconds!: number
  minClaudeCodeVersion!: string
  maxClaudeCodeVersion!: string
  allowUngroupedKeyScheduling!: boolean
  schedulerV2Enabled!: boolean
  schedulerV2Status!: string
  schedulerV2Error!: string
  schedulerV2CandidateLimit!: number
  schedulerV2ScanLimit!: number
  enableFingerprintUnification!: boolean
  enableMetadataPassthrough!: boolean
  enableCchSigning!: boolean
  enableClaudeOauthSystemPromptInjection!: boolean
  claudeOauthSystemPrompt!: string
  claudeOauthSystemPromptBlocks!: string
  enableAnthropicCacheTtl1hInjection!: boolean
  rewriteMessageCacheControl!: boolean
  enableClientDatelineNormalization!: boolean
  antigravityUserAgentVersion!: string
  openaiCodexUserAgent!: string
  minCodexVersion!: string
  maxCodexVersion!: string
  codexCliOnlyBlacklist!: string
  codexCliOnlyWhitelist!: string
  codexCliOnlyAllowAppServerClients!: boolean
  codexCliOnlyEngineFingerprintSignals!: string
  webSearchEmulationEnabled?: boolean
  paymentEnabled!: boolean
  riskControlEnabled!: boolean
  cyberSessionBlockEnabled!: boolean
  cyberSessionBlockTtlSeconds!: number
  paymentMinAmount!: number
  paymentMaxAmount!: number
  paymentDailyLimit!: number
  paymentOrderTimeoutMinutes!: number
  paymentMaxPendingOrders!: number
  paymentEnabledTypes!: string[]
  paymentBalanceDisabled!: boolean
  paymentBalanceRechargeMultiplier!: number
  paymentSubscriptionUsdToCnyRate!: number
  paymentRechargeFeeRate!: number
  paymentLoadBalanceStrategy!: string
  paymentProductNamePrefix!: string
  paymentProductNameSuffix!: string
  paymentHelpImageUrl!: string
  paymentHelpText!: string
  paymentCancelRateLimitEnabled!: boolean
  paymentCancelRateLimitMax!: number
  paymentCancelRateLimitWindow!: number
  paymentCancelRateLimitUnit!: string
  paymentCancelRateLimitWindowMode!: string
  paymentAlipayForceQrcode?: boolean
  paymentVisibleMethodAlipaySource?: string
  paymentVisibleMethodWxpaySource?: string
  paymentVisibleMethodAlipayEnabled?: boolean
  paymentVisibleMethodWxpayEnabled?: boolean
  openaiLowUpstreamRatePriorityEnabled?: boolean
  openaiOauthSchedulingRateMultiplier?: number
  openaiAdvancedSchedulerEnabled?: boolean
  openaiAdvancedSchedulerStickyWeightedEnabled?: boolean
  openaiAdvancedSchedulerSubscriptionPriorityEnabled?: boolean
  openaiAdvancedSchedulerLbTopK?: string
  openaiAdvancedSchedulerWeightPriority?: string
  openaiAdvancedSchedulerWeightLoad?: string
  openaiAdvancedSchedulerWeightQueue?: string
  openaiAdvancedSchedulerWeightErrorRate?: string
  openaiAdvancedSchedulerWeightTtft?: string
  openaiAdvancedSchedulerWeightReset?: string
  openaiAdvancedSchedulerWeightQuotaHeadroom?: string
  openaiAdvancedSchedulerWeightUpstreamCost?: string
  openaiAdvancedSchedulerWeightPreviousResponse?: string
  openaiAdvancedSchedulerWeightSessionSticky?: string
  openaiAdvancedSchedulerEffectiveLbTopK?: string
  openaiAdvancedSchedulerEffectiveWeightPriority?: string
  openaiAdvancedSchedulerEffectiveWeightLoad?: string
  openaiAdvancedSchedulerEffectiveWeightQueue?: string
  openaiAdvancedSchedulerEffectiveWeightErrorRate?: string
  openaiAdvancedSchedulerEffectiveWeightTtft?: string
  openaiAdvancedSchedulerEffectiveWeightReset?: string
  openaiAdvancedSchedulerEffectiveWeightQuotaHeadroom?: string
  openaiAdvancedSchedulerEffectiveWeightUpstreamCost?: string
  openaiAdvancedSchedulerEffectiveWeightPreviousResponse?: string
  openaiAdvancedSchedulerEffectiveWeightSessionSticky?: string
  balanceLowNotifyEnabled!: boolean
  balanceLowNotifyThreshold!: number
  balanceLowNotifyRechargeUrl!: string
  subscriptionExpiryNotifyEnabled!: boolean
  accountQuotaNotifyEnabled!: boolean
  accountQuotaNotifyEmails!: NotifyEmailEntry[]
  channelMonitorEnabled!: boolean
  channelMonitorDefaultIntervalSeconds!: number
  availableChannelsEnabled!: boolean
  affiliateEnabled!: boolean
  openaiAdvancedFastPolicySettings?: OpenAIFastPolicySettings
  allowUserViewErrorRequests!: boolean
  allowUserViewUsageDetails!: boolean
}
