/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */
export { default as AdminAffiliateInvitesPage } from './presentation/pages/AdminAffiliateInvitesPage.vue'
export { default as AdminAffiliateRebatesPage } from './presentation/pages/AdminAffiliateRebatesPage.vue'
export { default as AdminAffiliateTransfersPage } from './presentation/pages/AdminAffiliateTransfersPage.vue'
export { default as AffiliatePage } from './presentation/pages/AffiliatePage.vue'


// Route fragment — import in core/routes/index.ts

// export const affiliateRoutes: RouteRecordRaw[] = [{ path: '/todo', component: AdminAffiliateInvitesPage }]
// export const affiliateRoutes: RouteRecordRaw[] = [{ path: '/todo', component: AdminAffiliateRebatesPage }]
// export const affiliateRoutes: RouteRecordRaw[] = [{ path: '/todo', component: AdminAffiliateTransfersPage }]
// export const affiliateRoutes: RouteRecordRaw[] = [{ path: '/todo', component: AffiliatePage }]
