/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useSetup — thin orchestrator composable for Setup.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useSetupQueryStore } from '@/features/setup/presentation/stores/setupQueryStore'
import { useSetupActionStore } from '@/features/setup/presentation/stores/setupActionStore'

export function useSetup() {
  const q_setupQueryStore = useSetupQueryStore()
  const a_setupActionStore = useSetupActionStore()
  return {
    ...q_setupQueryStore,
    ...a_setupActionStore,
  }
}
