import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const usageRoutes: RouteRecordRaw[] = [
  {
    path: '/usage',
    name: 'Usage',
    component: () => import('@/features/usage/presentation/pages/UsagePage.vue'),
    meta: { requiresAuth: true, requiresAdmin: false, title: 'Usage Records', titleKey: 'usage.title', descriptionKey: 'usage.description' },
  },
]
