/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 */
export * from '@/features/admin-subscriptions/data/datasources/adminSubscriptionsDatasource'
export { default } from '@/features/admin-subscriptions/data/datasources/adminSubscriptionsDatasource'
