// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountgroup"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitor"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitordailyrollup"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitorhistory"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitorrequesttemplate"
	"github.com/Wei-Shaw/sub2api/ent/compositemodelroute"
	"github.com/Wei-Shaw/sub2api/ent/errorpassthroughrule"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/idempotencyrecord"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/schema"
	"github.com/Wei-Shaw/sub2api/ent/securitysecret"
	"github.com/Wei-Shaw/sub2api/ent/setting"
	"github.com/Wei-Shaw/sub2api/ent/tlsfingerprintprofile"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyMixin := schema.APIKey{}.Mixin()
	apikeyMixinHooks1 := apikeyMixin[1].Hooks()
	apikey.Hooks[0] = apikeyMixinHooks1[0]
	apikeyMixinInters1 := apikeyMixin[1].Interceptors()
	apikey.Interceptors[0] = apikeyMixinInters1[0]
	apikeyMixinFields0 := apikeyMixin[0].Fields()
	_ = apikeyMixinFields0
	apikeyFields := schema.APIKey{}.Fields()
	_ = apikeyFields
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyMixinFields0[0].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	// apikeyDescUpdatedAt is the schema descriptor for updated_at field.
	apikeyDescUpdatedAt := apikeyMixinFields0[1].Descriptor()
	// apikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apikey.DefaultUpdatedAt = apikeyDescUpdatedAt.Default.(func() time.Time)
	// apikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apikey.UpdateDefaultUpdatedAt = apikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apikeyDescKey is the schema descriptor for key field.
	apikeyDescKey := apikeyFields[1].Descriptor()
	// apikey.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	apikey.KeyValidator = func() func(string) error {
		validators := apikeyDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apikeyDescName is the schema descriptor for name field.
	apikeyDescName := apikeyFields[2].Descriptor()
	// apikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apikey.NameValidator = func() func(string) error {
		validators := apikeyDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apikeyDescStatus is the schema descriptor for status field.
	apikeyDescStatus := apikeyFields[4].Descriptor()
	// apikey.DefaultStatus holds the default value on creation for the status field.
	apikey.DefaultStatus = apikeyDescStatus.Default.(string)
	// apikey.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	apikey.StatusValidator = apikeyDescStatus.Validators[0].(func(string) error)
	// apikeyDescConcurrencyLimit is the schema descriptor for concurrency_limit field.
	apikeyDescConcurrencyLimit := apikeyFields[9].Descriptor()
	// apikey.DefaultConcurrencyLimit holds the default value on creation for the concurrency_limit field.
	apikey.DefaultConcurrencyLimit = apikeyDescConcurrencyLimit.Default.(int)
	// apikey.ConcurrencyLimitValidator is a validator for the "concurrency_limit" field. It is called by the builders before save.
	apikey.ConcurrencyLimitValidator = apikeyDescConcurrencyLimit.Validators[0].(func(int) error)
	accountMixin := schema.Account{}.Mixin()
	accountMixinHooks1 := accountMixin[1].Hooks()
	account.Hooks[0] = accountMixinHooks1[0]
	accountMixinInters1 := accountMixin[1].Interceptors()
	account.Interceptors[0] = accountMixinInters1[0]
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountMixinFields0[0].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountMixinFields0[1].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = func() func(string) error {
		validators := accountDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescPlatform is the schema descriptor for platform field.
	accountDescPlatform := accountFields[2].Descriptor()
	// account.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	account.PlatformValidator = func() func(string) error {
		validators := accountDescPlatform.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(platform string) error {
			for _, fn := range fns {
				if err := fn(platform); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescType is the schema descriptor for type field.
	accountDescType := accountFields[3].Descriptor()
	// account.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	account.TypeValidator = func() func(string) error {
		validators := accountDescType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_type string) error {
			for _, fn := range fns {
				if err := fn(_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescCredentials is the schema descriptor for credentials field.
	accountDescCredentials := accountFields[4].Descriptor()
	// account.DefaultCredentials holds the default value on creation for the credentials field.
	account.DefaultCredentials = accountDescCredentials.Default.(func() map[string]interface{})
	// accountDescExtra is the schema descriptor for extra field.
	accountDescExtra := accountFields[5].Descriptor()
	// account.DefaultExtra holds the default value on creation for the extra field.
	account.DefaultExtra = accountDescExtra.Default.(func() map[string]interface{})
	// accountDescConcurrency is the schema descriptor for concurrency field.
	accountDescConcurrency := accountFields[8].Descriptor()
	// account.DefaultConcurrency holds the default value on creation for the concurrency field.
	account.DefaultConcurrency = accountDescConcurrency.Default.(int)
	// accountDescPriority is the schema descriptor for priority field.
	accountDescPriority := accountFields[10].Descriptor()
	// account.DefaultPriority holds the default value on creation for the priority field.
	account.DefaultPriority = accountDescPriority.Default.(int)
	// accountDescRateMultiplier is the schema descriptor for rate_multiplier field.
	accountDescRateMultiplier := accountFields[11].Descriptor()
	// account.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	account.DefaultRateMultiplier = accountDescRateMultiplier.Default.(float64)
	// accountDescStatus is the schema descriptor for status field.
	accountDescStatus := accountFields[12].Descriptor()
	// account.DefaultStatus holds the default value on creation for the status field.
	account.DefaultStatus = accountDescStatus.Default.(string)
	// account.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	account.StatusValidator = accountDescStatus.Validators[0].(func(string) error)
	// accountDescAutoPauseOnExpired is the schema descriptor for auto_pause_on_expired field.
	accountDescAutoPauseOnExpired := accountFields[16].Descriptor()
	// account.DefaultAutoPauseOnExpired holds the default value on creation for the auto_pause_on_expired field.
	account.DefaultAutoPauseOnExpired = accountDescAutoPauseOnExpired.Default.(bool)
	// accountDescSchedulable is the schema descriptor for schedulable field.
	accountDescSchedulable := accountFields[17].Descriptor()
	// account.DefaultSchedulable holds the default value on creation for the schedulable field.
	account.DefaultSchedulable = accountDescSchedulable.Default.(bool)
	// accountDescSessionWindowStatus is the schema descriptor for session_window_status field.
	accountDescSessionWindowStatus := accountFields[25].Descriptor()
	// account.SessionWindowStatusValidator is a validator for the "session_window_status" field. It is called by the builders before save.
	account.SessionWindowStatusValidator = accountDescSessionWindowStatus.Validators[0].(func(string) error)
	accountgroupFields := schema.AccountGroup{}.Fields()
	_ = accountgroupFields
	// accountgroupDescPriority is the schema descriptor for priority field.
	accountgroupDescPriority := accountgroupFields[2].Descriptor()
	// accountgroup.DefaultPriority holds the default value on creation for the priority field.
	accountgroup.DefaultPriority = accountgroupDescPriority.Default.(int)
	// accountgroupDescCreatedAt is the schema descriptor for created_at field.
	accountgroupDescCreatedAt := accountgroupFields[3].Descriptor()
	// accountgroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	accountgroup.DefaultCreatedAt = accountgroupDescCreatedAt.Default.(func() time.Time)
	channelmonitorMixin := schema.ChannelMonitor{}.Mixin()
	channelmonitorMixinFields0 := channelmonitorMixin[0].Fields()
	_ = channelmonitorMixinFields0
	channelmonitorFields := schema.ChannelMonitor{}.Fields()
	_ = channelmonitorFields
	// channelmonitorDescCreatedAt is the schema descriptor for created_at field.
	channelmonitorDescCreatedAt := channelmonitorMixinFields0[0].Descriptor()
	// channelmonitor.DefaultCreatedAt holds the default value on creation for the created_at field.
	channelmonitor.DefaultCreatedAt = channelmonitorDescCreatedAt.Default.(func() time.Time)
	// channelmonitorDescUpdatedAt is the schema descriptor for updated_at field.
	channelmonitorDescUpdatedAt := channelmonitorMixinFields0[1].Descriptor()
	// channelmonitor.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	channelmonitor.DefaultUpdatedAt = channelmonitorDescUpdatedAt.Default.(func() time.Time)
	// channelmonitor.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	channelmonitor.UpdateDefaultUpdatedAt = channelmonitorDescUpdatedAt.UpdateDefault.(func() time.Time)
	// channelmonitorDescName is the schema descriptor for name field.
	channelmonitorDescName := channelmonitorFields[0].Descriptor()
	// channelmonitor.NameValidator is a validator for the "name" field. It is called by the builders before save.
	channelmonitor.NameValidator = func() func(string) error {
		validators := channelmonitorDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// channelmonitorDescAPIMode is the schema descriptor for api_mode field.
	channelmonitorDescAPIMode := channelmonitorFields[5].Descriptor()
	// channelmonitor.DefaultAPIMode holds the default value on creation for the api_mode field.
	channelmonitor.DefaultAPIMode = channelmonitorDescAPIMode.Default.(string)
	// channelmonitor.APIModeValidator is a validator for the "api_mode" field. It is called by the builders before save.
	channelmonitor.APIModeValidator = channelmonitorDescAPIMode.Validators[0].(func(string) error)
	// channelmonitorDescEndpoint is the schema descriptor for endpoint field.
	channelmonitorDescEndpoint := channelmonitorFields[6].Descriptor()
	// channelmonitor.EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	channelmonitor.EndpointValidator = channelmonitorDescEndpoint.Validators[0].(func(string) error)
	// channelmonitorDescPrimaryModel is the schema descriptor for primary_model field.
	channelmonitorDescPrimaryModel := channelmonitorFields[8].Descriptor()
	// channelmonitor.PrimaryModelValidator is a validator for the "primary_model" field. It is called by the builders before save.
	channelmonitor.PrimaryModelValidator = func() func(string) error {
		validators := channelmonitorDescPrimaryModel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(primary_model string) error {
			for _, fn := range fns {
				if err := fn(primary_model); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// channelmonitorDescExtraModels is the schema descriptor for extra_models field.
	channelmonitorDescExtraModels := channelmonitorFields[9].Descriptor()
	// channelmonitor.DefaultExtraModels holds the default value on creation for the extra_models field.
	channelmonitor.DefaultExtraModels = channelmonitorDescExtraModels.Default.([]string)
	// channelmonitorDescGroupName is the schema descriptor for group_name field.
	channelmonitorDescGroupName := channelmonitorFields[10].Descriptor()
	// channelmonitor.DefaultGroupName holds the default value on creation for the group_name field.
	channelmonitor.DefaultGroupName = channelmonitorDescGroupName.Default.(string)
	// channelmonitor.GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	channelmonitor.GroupNameValidator = channelmonitorDescGroupName.Validators[0].(func(string) error)
	// channelmonitorDescEnabled is the schema descriptor for enabled field.
	channelmonitorDescEnabled := channelmonitorFields[11].Descriptor()
	// channelmonitor.DefaultEnabled holds the default value on creation for the enabled field.
	channelmonitor.DefaultEnabled = channelmonitorDescEnabled.Default.(bool)
	// channelmonitorDescIntervalSeconds is the schema descriptor for interval_seconds field.
	channelmonitorDescIntervalSeconds := channelmonitorFields[12].Descriptor()
	// channelmonitor.IntervalSecondsValidator is a validator for the "interval_seconds" field. It is called by the builders before save.
	channelmonitor.IntervalSecondsValidator = channelmonitorDescIntervalSeconds.Validators[0].(func(int) error)
	// channelmonitorDescJitterSeconds is the schema descriptor for jitter_seconds field.
	channelmonitorDescJitterSeconds := channelmonitorFields[13].Descriptor()
	// channelmonitor.DefaultJitterSeconds holds the default value on creation for the jitter_seconds field.
	channelmonitor.DefaultJitterSeconds = channelmonitorDescJitterSeconds.Default.(int)
	// channelmonitor.JitterSecondsValidator is a validator for the "jitter_seconds" field. It is called by the builders before save.
	channelmonitor.JitterSecondsValidator = channelmonitorDescJitterSeconds.Validators[0].(func(int) error)
	// channelmonitorDescExtraHeaders is the schema descriptor for extra_headers field.
	channelmonitorDescExtraHeaders := channelmonitorFields[17].Descriptor()
	// channelmonitor.DefaultExtraHeaders holds the default value on creation for the extra_headers field.
	channelmonitor.DefaultExtraHeaders = channelmonitorDescExtraHeaders.Default.(map[string]string)
	// channelmonitorDescBodyOverrideMode is the schema descriptor for body_override_mode field.
	channelmonitorDescBodyOverrideMode := channelmonitorFields[18].Descriptor()
	// channelmonitor.DefaultBodyOverrideMode holds the default value on creation for the body_override_mode field.
	channelmonitor.DefaultBodyOverrideMode = channelmonitorDescBodyOverrideMode.Default.(string)
	// channelmonitor.BodyOverrideModeValidator is a validator for the "body_override_mode" field. It is called by the builders before save.
	channelmonitor.BodyOverrideModeValidator = channelmonitorDescBodyOverrideMode.Validators[0].(func(string) error)
	channelmonitordailyrollupFields := schema.ChannelMonitorDailyRollup{}.Fields()
	_ = channelmonitordailyrollupFields
	// channelmonitordailyrollupDescModel is the schema descriptor for model field.
	channelmonitordailyrollupDescModel := channelmonitordailyrollupFields[1].Descriptor()
	// channelmonitordailyrollup.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	channelmonitordailyrollup.ModelValidator = func() func(string) error {
		validators := channelmonitordailyrollupDescModel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model string) error {
			for _, fn := range fns {
				if err := fn(model); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// channelmonitordailyrollupDescTotalChecks is the schema descriptor for total_checks field.
	channelmonitordailyrollupDescTotalChecks := channelmonitordailyrollupFields[3].Descriptor()
	// channelmonitordailyrollup.DefaultTotalChecks holds the default value on creation for the total_checks field.
	channelmonitordailyrollup.DefaultTotalChecks = channelmonitordailyrollupDescTotalChecks.Default.(int)
	// channelmonitordailyrollupDescOkCount is the schema descriptor for ok_count field.
	channelmonitordailyrollupDescOkCount := channelmonitordailyrollupFields[4].Descriptor()
	// channelmonitordailyrollup.DefaultOkCount holds the default value on creation for the ok_count field.
	channelmonitordailyrollup.DefaultOkCount = channelmonitordailyrollupDescOkCount.Default.(int)
	// channelmonitordailyrollupDescOperationalCount is the schema descriptor for operational_count field.
	channelmonitordailyrollupDescOperationalCount := channelmonitordailyrollupFields[5].Descriptor()
	// channelmonitordailyrollup.DefaultOperationalCount holds the default value on creation for the operational_count field.
	channelmonitordailyrollup.DefaultOperationalCount = channelmonitordailyrollupDescOperationalCount.Default.(int)
	// channelmonitordailyrollupDescDegradedCount is the schema descriptor for degraded_count field.
	channelmonitordailyrollupDescDegradedCount := channelmonitordailyrollupFields[6].Descriptor()
	// channelmonitordailyrollup.DefaultDegradedCount holds the default value on creation for the degraded_count field.
	channelmonitordailyrollup.DefaultDegradedCount = channelmonitordailyrollupDescDegradedCount.Default.(int)
	// channelmonitordailyrollupDescFailedCount is the schema descriptor for failed_count field.
	channelmonitordailyrollupDescFailedCount := channelmonitordailyrollupFields[7].Descriptor()
	// channelmonitordailyrollup.DefaultFailedCount holds the default value on creation for the failed_count field.
	channelmonitordailyrollup.DefaultFailedCount = channelmonitordailyrollupDescFailedCount.Default.(int)
	// channelmonitordailyrollupDescErrorCount is the schema descriptor for error_count field.
	channelmonitordailyrollupDescErrorCount := channelmonitordailyrollupFields[8].Descriptor()
	// channelmonitordailyrollup.DefaultErrorCount holds the default value on creation for the error_count field.
	channelmonitordailyrollup.DefaultErrorCount = channelmonitordailyrollupDescErrorCount.Default.(int)
	// channelmonitordailyrollupDescSumLatencyMs is the schema descriptor for sum_latency_ms field.
	channelmonitordailyrollupDescSumLatencyMs := channelmonitordailyrollupFields[9].Descriptor()
	// channelmonitordailyrollup.DefaultSumLatencyMs holds the default value on creation for the sum_latency_ms field.
	channelmonitordailyrollup.DefaultSumLatencyMs = channelmonitordailyrollupDescSumLatencyMs.Default.(int64)
	// channelmonitordailyrollupDescCountLatency is the schema descriptor for count_latency field.
	channelmonitordailyrollupDescCountLatency := channelmonitordailyrollupFields[10].Descriptor()
	// channelmonitordailyrollup.DefaultCountLatency holds the default value on creation for the count_latency field.
	channelmonitordailyrollup.DefaultCountLatency = channelmonitordailyrollupDescCountLatency.Default.(int)
	// channelmonitordailyrollupDescSumPingLatencyMs is the schema descriptor for sum_ping_latency_ms field.
	channelmonitordailyrollupDescSumPingLatencyMs := channelmonitordailyrollupFields[11].Descriptor()
	// channelmonitordailyrollup.DefaultSumPingLatencyMs holds the default value on creation for the sum_ping_latency_ms field.
	channelmonitordailyrollup.DefaultSumPingLatencyMs = channelmonitordailyrollupDescSumPingLatencyMs.Default.(int64)
	// channelmonitordailyrollupDescCountPingLatency is the schema descriptor for count_ping_latency field.
	channelmonitordailyrollupDescCountPingLatency := channelmonitordailyrollupFields[12].Descriptor()
	// channelmonitordailyrollup.DefaultCountPingLatency holds the default value on creation for the count_ping_latency field.
	channelmonitordailyrollup.DefaultCountPingLatency = channelmonitordailyrollupDescCountPingLatency.Default.(int)
	// channelmonitordailyrollupDescComputedAt is the schema descriptor for computed_at field.
	channelmonitordailyrollupDescComputedAt := channelmonitordailyrollupFields[13].Descriptor()
	// channelmonitordailyrollup.DefaultComputedAt holds the default value on creation for the computed_at field.
	channelmonitordailyrollup.DefaultComputedAt = channelmonitordailyrollupDescComputedAt.Default.(func() time.Time)
	// channelmonitordailyrollup.UpdateDefaultComputedAt holds the default value on update for the computed_at field.
	channelmonitordailyrollup.UpdateDefaultComputedAt = channelmonitordailyrollupDescComputedAt.UpdateDefault.(func() time.Time)
	channelmonitorhistoryFields := schema.ChannelMonitorHistory{}.Fields()
	_ = channelmonitorhistoryFields
	// channelmonitorhistoryDescModel is the schema descriptor for model field.
	channelmonitorhistoryDescModel := channelmonitorhistoryFields[1].Descriptor()
	// channelmonitorhistory.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	channelmonitorhistory.ModelValidator = func() func(string) error {
		validators := channelmonitorhistoryDescModel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model string) error {
			for _, fn := range fns {
				if err := fn(model); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// channelmonitorhistoryDescMessage is the schema descriptor for message field.
	channelmonitorhistoryDescMessage := channelmonitorhistoryFields[5].Descriptor()
	// channelmonitorhistory.DefaultMessage holds the default value on creation for the message field.
	channelmonitorhistory.DefaultMessage = channelmonitorhistoryDescMessage.Default.(string)
	// channelmonitorhistory.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	channelmonitorhistory.MessageValidator = channelmonitorhistoryDescMessage.Validators[0].(func(string) error)
	// channelmonitorhistoryDescCheckedAt is the schema descriptor for checked_at field.
	channelmonitorhistoryDescCheckedAt := channelmonitorhistoryFields[6].Descriptor()
	// channelmonitorhistory.DefaultCheckedAt holds the default value on creation for the checked_at field.
	channelmonitorhistory.DefaultCheckedAt = channelmonitorhistoryDescCheckedAt.Default.(func() time.Time)
	channelmonitorrequesttemplateMixin := schema.ChannelMonitorRequestTemplate{}.Mixin()
	channelmonitorrequesttemplateMixinFields0 := channelmonitorrequesttemplateMixin[0].Fields()
	_ = channelmonitorrequesttemplateMixinFields0
	channelmonitorrequesttemplateFields := schema.ChannelMonitorRequestTemplate{}.Fields()
	_ = channelmonitorrequesttemplateFields
	// channelmonitorrequesttemplateDescCreatedAt is the schema descriptor for created_at field.
	channelmonitorrequesttemplateDescCreatedAt := channelmonitorrequesttemplateMixinFields0[0].Descriptor()
	// channelmonitorrequesttemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	channelmonitorrequesttemplate.DefaultCreatedAt = channelmonitorrequesttemplateDescCreatedAt.Default.(func() time.Time)
	// channelmonitorrequesttemplateDescUpdatedAt is the schema descriptor for updated_at field.
	channelmonitorrequesttemplateDescUpdatedAt := channelmonitorrequesttemplateMixinFields0[1].Descriptor()
	// channelmonitorrequesttemplate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	channelmonitorrequesttemplate.DefaultUpdatedAt = channelmonitorrequesttemplateDescUpdatedAt.Default.(func() time.Time)
	// channelmonitorrequesttemplate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	channelmonitorrequesttemplate.UpdateDefaultUpdatedAt = channelmonitorrequesttemplateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// channelmonitorrequesttemplateDescName is the schema descriptor for name field.
	channelmonitorrequesttemplateDescName := channelmonitorrequesttemplateFields[0].Descriptor()
	// channelmonitorrequesttemplate.NameValidator is a validator for the "name" field. It is called by the builders before save.
	channelmonitorrequesttemplate.NameValidator = func() func(string) error {
		validators := channelmonitorrequesttemplateDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// channelmonitorrequesttemplateDescAPIMode is the schema descriptor for api_mode field.
	channelmonitorrequesttemplateDescAPIMode := channelmonitorrequesttemplateFields[2].Descriptor()
	// channelmonitorrequesttemplate.DefaultAPIMode holds the default value on creation for the api_mode field.
	channelmonitorrequesttemplate.DefaultAPIMode = channelmonitorrequesttemplateDescAPIMode.Default.(string)
	// channelmonitorrequesttemplate.APIModeValidator is a validator for the "api_mode" field. It is called by the builders before save.
	channelmonitorrequesttemplate.APIModeValidator = channelmonitorrequesttemplateDescAPIMode.Validators[0].(func(string) error)
	// channelmonitorrequesttemplateDescDescription is the schema descriptor for description field.
	channelmonitorrequesttemplateDescDescription := channelmonitorrequesttemplateFields[3].Descriptor()
	// channelmonitorrequesttemplate.DefaultDescription holds the default value on creation for the description field.
	channelmonitorrequesttemplate.DefaultDescription = channelmonitorrequesttemplateDescDescription.Default.(string)
	// channelmonitorrequesttemplate.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	channelmonitorrequesttemplate.DescriptionValidator = channelmonitorrequesttemplateDescDescription.Validators[0].(func(string) error)
	// channelmonitorrequesttemplateDescExtraHeaders is the schema descriptor for extra_headers field.
	channelmonitorrequesttemplateDescExtraHeaders := channelmonitorrequesttemplateFields[4].Descriptor()
	// channelmonitorrequesttemplate.DefaultExtraHeaders holds the default value on creation for the extra_headers field.
	channelmonitorrequesttemplate.DefaultExtraHeaders = channelmonitorrequesttemplateDescExtraHeaders.Default.(map[string]string)
	// channelmonitorrequesttemplateDescBodyOverrideMode is the schema descriptor for body_override_mode field.
	channelmonitorrequesttemplateDescBodyOverrideMode := channelmonitorrequesttemplateFields[5].Descriptor()
	// channelmonitorrequesttemplate.DefaultBodyOverrideMode holds the default value on creation for the body_override_mode field.
	channelmonitorrequesttemplate.DefaultBodyOverrideMode = channelmonitorrequesttemplateDescBodyOverrideMode.Default.(string)
	// channelmonitorrequesttemplate.BodyOverrideModeValidator is a validator for the "body_override_mode" field. It is called by the builders before save.
	channelmonitorrequesttemplate.BodyOverrideModeValidator = channelmonitorrequesttemplateDescBodyOverrideMode.Validators[0].(func(string) error)
	compositemodelrouteMixin := schema.CompositeModelRoute{}.Mixin()
	compositemodelrouteMixinHooks1 := compositemodelrouteMixin[1].Hooks()
	compositemodelroute.Hooks[0] = compositemodelrouteMixinHooks1[0]
	compositemodelrouteMixinInters1 := compositemodelrouteMixin[1].Interceptors()
	compositemodelroute.Interceptors[0] = compositemodelrouteMixinInters1[0]
	compositemodelrouteMixinFields0 := compositemodelrouteMixin[0].Fields()
	_ = compositemodelrouteMixinFields0
	compositemodelrouteFields := schema.CompositeModelRoute{}.Fields()
	_ = compositemodelrouteFields
	// compositemodelrouteDescCreatedAt is the schema descriptor for created_at field.
	compositemodelrouteDescCreatedAt := compositemodelrouteMixinFields0[0].Descriptor()
	// compositemodelroute.DefaultCreatedAt holds the default value on creation for the created_at field.
	compositemodelroute.DefaultCreatedAt = compositemodelrouteDescCreatedAt.Default.(func() time.Time)
	// compositemodelrouteDescUpdatedAt is the schema descriptor for updated_at field.
	compositemodelrouteDescUpdatedAt := compositemodelrouteMixinFields0[1].Descriptor()
	// compositemodelroute.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	compositemodelroute.DefaultUpdatedAt = compositemodelrouteDescUpdatedAt.Default.(func() time.Time)
	// compositemodelroute.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	compositemodelroute.UpdateDefaultUpdatedAt = compositemodelrouteDescUpdatedAt.UpdateDefault.(func() time.Time)
	// compositemodelrouteDescPublicModel is the schema descriptor for public_model field.
	compositemodelrouteDescPublicModel := compositemodelrouteFields[1].Descriptor()
	// compositemodelroute.PublicModelValidator is a validator for the "public_model" field. It is called by the builders before save.
	compositemodelroute.PublicModelValidator = func() func(string) error {
		validators := compositemodelrouteDescPublicModel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(public_model string) error {
			for _, fn := range fns {
				if err := fn(public_model); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// compositemodelrouteDescMatchType is the schema descriptor for match_type field.
	compositemodelrouteDescMatchType := compositemodelrouteFields[2].Descriptor()
	// compositemodelroute.DefaultMatchType holds the default value on creation for the match_type field.
	compositemodelroute.DefaultMatchType = compositemodelrouteDescMatchType.Default.(string)
	// compositemodelroute.MatchTypeValidator is a validator for the "match_type" field. It is called by the builders before save.
	compositemodelroute.MatchTypeValidator = compositemodelrouteDescMatchType.Validators[0].(func(string) error)
	// compositemodelrouteDescTargetPlatform is the schema descriptor for target_platform field.
	compositemodelrouteDescTargetPlatform := compositemodelrouteFields[3].Descriptor()
	// compositemodelroute.DefaultTargetPlatform holds the default value on creation for the target_platform field.
	compositemodelroute.DefaultTargetPlatform = compositemodelrouteDescTargetPlatform.Default.(string)
	// compositemodelroute.TargetPlatformValidator is a validator for the "target_platform" field. It is called by the builders before save.
	compositemodelroute.TargetPlatformValidator = compositemodelrouteDescTargetPlatform.Validators[0].(func(string) error)
	// compositemodelrouteDescUpstreamModel is the schema descriptor for upstream_model field.
	compositemodelrouteDescUpstreamModel := compositemodelrouteFields[4].Descriptor()
	// compositemodelroute.DefaultUpstreamModel holds the default value on creation for the upstream_model field.
	compositemodelroute.DefaultUpstreamModel = compositemodelrouteDescUpstreamModel.Default.(string)
	// compositemodelroute.UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	compositemodelroute.UpstreamModelValidator = compositemodelrouteDescUpstreamModel.Validators[0].(func(string) error)
	// compositemodelrouteDescEndpoint is the schema descriptor for endpoint field.
	compositemodelrouteDescEndpoint := compositemodelrouteFields[5].Descriptor()
	// compositemodelroute.DefaultEndpoint holds the default value on creation for the endpoint field.
	compositemodelroute.DefaultEndpoint = compositemodelrouteDescEndpoint.Default.(string)
	// compositemodelroute.EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	compositemodelroute.EndpointValidator = compositemodelrouteDescEndpoint.Validators[0].(func(string) error)
	// compositemodelrouteDescPriority is the schema descriptor for priority field.
	compositemodelrouteDescPriority := compositemodelrouteFields[6].Descriptor()
	// compositemodelroute.DefaultPriority holds the default value on creation for the priority field.
	compositemodelroute.DefaultPriority = compositemodelrouteDescPriority.Default.(int)
	// compositemodelrouteDescEnabled is the schema descriptor for enabled field.
	compositemodelrouteDescEnabled := compositemodelrouteFields[7].Descriptor()
	// compositemodelroute.DefaultEnabled holds the default value on creation for the enabled field.
	compositemodelroute.DefaultEnabled = compositemodelrouteDescEnabled.Default.(bool)
	errorpassthroughruleMixin := schema.ErrorPassthroughRule{}.Mixin()
	errorpassthroughruleMixinFields0 := errorpassthroughruleMixin[0].Fields()
	_ = errorpassthroughruleMixinFields0
	errorpassthroughruleFields := schema.ErrorPassthroughRule{}.Fields()
	_ = errorpassthroughruleFields
	// errorpassthroughruleDescCreatedAt is the schema descriptor for created_at field.
	errorpassthroughruleDescCreatedAt := errorpassthroughruleMixinFields0[0].Descriptor()
	// errorpassthroughrule.DefaultCreatedAt holds the default value on creation for the created_at field.
	errorpassthroughrule.DefaultCreatedAt = errorpassthroughruleDescCreatedAt.Default.(func() time.Time)
	// errorpassthroughruleDescUpdatedAt is the schema descriptor for updated_at field.
	errorpassthroughruleDescUpdatedAt := errorpassthroughruleMixinFields0[1].Descriptor()
	// errorpassthroughrule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	errorpassthroughrule.DefaultUpdatedAt = errorpassthroughruleDescUpdatedAt.Default.(func() time.Time)
	// errorpassthroughrule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	errorpassthroughrule.UpdateDefaultUpdatedAt = errorpassthroughruleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// errorpassthroughruleDescName is the schema descriptor for name field.
	errorpassthroughruleDescName := errorpassthroughruleFields[0].Descriptor()
	// errorpassthroughrule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	errorpassthroughrule.NameValidator = func() func(string) error {
		validators := errorpassthroughruleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// errorpassthroughruleDescEnabled is the schema descriptor for enabled field.
	errorpassthroughruleDescEnabled := errorpassthroughruleFields[1].Descriptor()
	// errorpassthroughrule.DefaultEnabled holds the default value on creation for the enabled field.
	errorpassthroughrule.DefaultEnabled = errorpassthroughruleDescEnabled.Default.(bool)
	// errorpassthroughruleDescPriority is the schema descriptor for priority field.
	errorpassthroughruleDescPriority := errorpassthroughruleFields[2].Descriptor()
	// errorpassthroughrule.DefaultPriority holds the default value on creation for the priority field.
	errorpassthroughrule.DefaultPriority = errorpassthroughruleDescPriority.Default.(int)
	// errorpassthroughruleDescMatchMode is the schema descriptor for match_mode field.
	errorpassthroughruleDescMatchMode := errorpassthroughruleFields[5].Descriptor()
	// errorpassthroughrule.DefaultMatchMode holds the default value on creation for the match_mode field.
	errorpassthroughrule.DefaultMatchMode = errorpassthroughruleDescMatchMode.Default.(string)
	// errorpassthroughrule.MatchModeValidator is a validator for the "match_mode" field. It is called by the builders before save.
	errorpassthroughrule.MatchModeValidator = errorpassthroughruleDescMatchMode.Validators[0].(func(string) error)
	// errorpassthroughruleDescPassthroughCode is the schema descriptor for passthrough_code field.
	errorpassthroughruleDescPassthroughCode := errorpassthroughruleFields[7].Descriptor()
	// errorpassthroughrule.DefaultPassthroughCode holds the default value on creation for the passthrough_code field.
	errorpassthroughrule.DefaultPassthroughCode = errorpassthroughruleDescPassthroughCode.Default.(bool)
	// errorpassthroughruleDescPassthroughBody is the schema descriptor for passthrough_body field.
	errorpassthroughruleDescPassthroughBody := errorpassthroughruleFields[9].Descriptor()
	// errorpassthroughrule.DefaultPassthroughBody holds the default value on creation for the passthrough_body field.
	errorpassthroughrule.DefaultPassthroughBody = errorpassthroughruleDescPassthroughBody.Default.(bool)
	// errorpassthroughruleDescSkipMonitoring is the schema descriptor for skip_monitoring field.
	errorpassthroughruleDescSkipMonitoring := errorpassthroughruleFields[11].Descriptor()
	// errorpassthroughrule.DefaultSkipMonitoring holds the default value on creation for the skip_monitoring field.
	errorpassthroughrule.DefaultSkipMonitoring = errorpassthroughruleDescSkipMonitoring.Default.(bool)
	groupMixin := schema.Group{}.Mixin()
	groupMixinHooks1 := groupMixin[1].Hooks()
	group.Hooks[0] = groupMixinHooks1[0]
	groupMixinInters1 := groupMixin[1].Interceptors()
	group.Interceptors[0] = groupMixinInters1[0]
	groupMixinFields0 := groupMixin[0].Fields()
	_ = groupMixinFields0
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupMixinFields0[0].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupMixinFields0[1].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = func() func(string) error {
		validators := groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescRateMultiplier is the schema descriptor for rate_multiplier field.
	groupDescRateMultiplier := groupFields[2].Descriptor()
	// group.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	group.DefaultRateMultiplier = groupDescRateMultiplier.Default.(float64)
	// groupDescStatus is the schema descriptor for status field.
	groupDescStatus := groupFields[3].Descriptor()
	// group.DefaultStatus holds the default value on creation for the status field.
	group.DefaultStatus = groupDescStatus.Default.(string)
	// group.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	group.StatusValidator = groupDescStatus.Validators[0].(func(string) error)
	// groupDescDuplicateOperationID is the schema descriptor for duplicate_operation_id field.
	groupDescDuplicateOperationID := groupFields[4].Descriptor()
	// group.DuplicateOperationIDValidator is a validator for the "duplicate_operation_id" field. It is called by the builders before save.
	group.DuplicateOperationIDValidator = groupDescDuplicateOperationID.Validators[0].(func(string) error)
	// groupDescPlatform is the schema descriptor for platform field.
	groupDescPlatform := groupFields[5].Descriptor()
	// group.DefaultPlatform holds the default value on creation for the platform field.
	group.DefaultPlatform = groupDescPlatform.Default.(string)
	// group.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	group.PlatformValidator = groupDescPlatform.Validators[0].(func(string) error)
	// groupDescAllowImageGeneration is the schema descriptor for allow_image_generation field.
	groupDescAllowImageGeneration := groupFields[6].Descriptor()
	// group.DefaultAllowImageGeneration holds the default value on creation for the allow_image_generation field.
	group.DefaultAllowImageGeneration = groupDescAllowImageGeneration.Default.(bool)
	// groupDescOpenaiForceImageTool is the schema descriptor for openai_force_image_tool field.
	groupDescOpenaiForceImageTool := groupFields[7].Descriptor()
	// group.DefaultOpenaiForceImageTool holds the default value on creation for the openai_force_image_tool field.
	group.DefaultOpenaiForceImageTool = groupDescOpenaiForceImageTool.Default.(bool)
	// groupDescImageRateIndependent is the schema descriptor for image_rate_independent field.
	groupDescImageRateIndependent := groupFields[8].Descriptor()
	// group.DefaultImageRateIndependent holds the default value on creation for the image_rate_independent field.
	group.DefaultImageRateIndependent = groupDescImageRateIndependent.Default.(bool)
	// groupDescImageRateMultiplier is the schema descriptor for image_rate_multiplier field.
	groupDescImageRateMultiplier := groupFields[9].Descriptor()
	// group.DefaultImageRateMultiplier holds the default value on creation for the image_rate_multiplier field.
	group.DefaultImageRateMultiplier = groupDescImageRateMultiplier.Default.(float64)
	// groupDescVideoRateIndependent is the schema descriptor for video_rate_independent field.
	groupDescVideoRateIndependent := groupFields[13].Descriptor()
	// group.DefaultVideoRateIndependent holds the default value on creation for the video_rate_independent field.
	group.DefaultVideoRateIndependent = groupDescVideoRateIndependent.Default.(bool)
	// groupDescVideoRateMultiplier is the schema descriptor for video_rate_multiplier field.
	groupDescVideoRateMultiplier := groupFields[14].Descriptor()
	// group.DefaultVideoRateMultiplier holds the default value on creation for the video_rate_multiplier field.
	group.DefaultVideoRateMultiplier = groupDescVideoRateMultiplier.Default.(float64)
	// groupDescClaudeCodeOnly is the schema descriptor for claude_code_only field.
	groupDescClaudeCodeOnly := groupFields[19].Descriptor()
	// group.DefaultClaudeCodeOnly holds the default value on creation for the claude_code_only field.
	group.DefaultClaudeCodeOnly = groupDescClaudeCodeOnly.Default.(bool)
	// groupDescModelRoutingEnabled is the schema descriptor for model_routing_enabled field.
	groupDescModelRoutingEnabled := groupFields[23].Descriptor()
	// group.DefaultModelRoutingEnabled holds the default value on creation for the model_routing_enabled field.
	group.DefaultModelRoutingEnabled = groupDescModelRoutingEnabled.Default.(bool)
	// groupDescMcpXMLInject is the schema descriptor for mcp_xml_inject field.
	groupDescMcpXMLInject := groupFields[24].Descriptor()
	// group.DefaultMcpXMLInject holds the default value on creation for the mcp_xml_inject field.
	group.DefaultMcpXMLInject = groupDescMcpXMLInject.Default.(bool)
	// groupDescSupportedModelScopes is the schema descriptor for supported_model_scopes field.
	groupDescSupportedModelScopes := groupFields[25].Descriptor()
	// group.DefaultSupportedModelScopes holds the default value on creation for the supported_model_scopes field.
	group.DefaultSupportedModelScopes = groupDescSupportedModelScopes.Default.([]string)
	// groupDescSortOrder is the schema descriptor for sort_order field.
	groupDescSortOrder := groupFields[26].Descriptor()
	// group.DefaultSortOrder holds the default value on creation for the sort_order field.
	group.DefaultSortOrder = groupDescSortOrder.Default.(int)
	// groupDescAllowMessagesDispatch is the schema descriptor for allow_messages_dispatch field.
	groupDescAllowMessagesDispatch := groupFields[27].Descriptor()
	// group.DefaultAllowMessagesDispatch holds the default value on creation for the allow_messages_dispatch field.
	group.DefaultAllowMessagesDispatch = groupDescAllowMessagesDispatch.Default.(bool)
	// groupDescAllowLive is the schema descriptor for allow_live field.
	groupDescAllowLive := groupFields[28].Descriptor()
	// group.DefaultAllowLive holds the default value on creation for the allow_live field.
	group.DefaultAllowLive = groupDescAllowLive.Default.(bool)
	// groupDescRequireOauthOnly is the schema descriptor for require_oauth_only field.
	groupDescRequireOauthOnly := groupFields[29].Descriptor()
	// group.DefaultRequireOauthOnly holds the default value on creation for the require_oauth_only field.
	group.DefaultRequireOauthOnly = groupDescRequireOauthOnly.Default.(bool)
	// groupDescRequirePrivacySet is the schema descriptor for require_privacy_set field.
	groupDescRequirePrivacySet := groupFields[30].Descriptor()
	// group.DefaultRequirePrivacySet holds the default value on creation for the require_privacy_set field.
	group.DefaultRequirePrivacySet = groupDescRequirePrivacySet.Default.(bool)
	// groupDescDefaultMappedModel is the schema descriptor for default_mapped_model field.
	groupDescDefaultMappedModel := groupFields[31].Descriptor()
	// group.DefaultDefaultMappedModel holds the default value on creation for the default_mapped_model field.
	group.DefaultDefaultMappedModel = groupDescDefaultMappedModel.Default.(string)
	// group.DefaultMappedModelValidator is a validator for the "default_mapped_model" field. It is called by the builders before save.
	group.DefaultMappedModelValidator = groupDescDefaultMappedModel.Validators[0].(func(string) error)
	// groupDescMessagesDispatchModelConfig is the schema descriptor for messages_dispatch_model_config field.
	groupDescMessagesDispatchModelConfig := groupFields[32].Descriptor()
	// group.DefaultMessagesDispatchModelConfig holds the default value on creation for the messages_dispatch_model_config field.
	group.DefaultMessagesDispatchModelConfig = groupDescMessagesDispatchModelConfig.Default.(domain.OpenAIMessagesDispatchModelConfig)
	// groupDescModelsListConfig is the schema descriptor for models_list_config field.
	groupDescModelsListConfig := groupFields[33].Descriptor()
	// group.DefaultModelsListConfig holds the default value on creation for the models_list_config field.
	group.DefaultModelsListConfig = groupDescModelsListConfig.Default.(domain.GroupModelsListConfig)
	// groupDescRpmLimit is the schema descriptor for rpm_limit field.
	groupDescRpmLimit := groupFields[34].Descriptor()
	// group.DefaultRpmLimit holds the default value on creation for the rpm_limit field.
	group.DefaultRpmLimit = groupDescRpmLimit.Default.(int)
	// groupDescMaxReasoningEffort is the schema descriptor for max_reasoning_effort field.
	groupDescMaxReasoningEffort := groupFields[35].Descriptor()
	// group.DefaultMaxReasoningEffort holds the default value on creation for the max_reasoning_effort field.
	group.DefaultMaxReasoningEffort = groupDescMaxReasoningEffort.Default.(string)
	// group.MaxReasoningEffortValidator is a validator for the "max_reasoning_effort" field. It is called by the builders before save.
	group.MaxReasoningEffortValidator = groupDescMaxReasoningEffort.Validators[0].(func(string) error)
	// groupDescReasoningEffortMappings is the schema descriptor for reasoning_effort_mappings field.
	groupDescReasoningEffortMappings := groupFields[36].Descriptor()
	// group.DefaultReasoningEffortMappings holds the default value on creation for the reasoning_effort_mappings field.
	group.DefaultReasoningEffortMappings = groupDescReasoningEffortMappings.Default.([]domain.ReasoningEffortMapping)
	// groupDescProfitControlEnabled is the schema descriptor for profit_control_enabled field.
	groupDescProfitControlEnabled := groupFields[37].Descriptor()
	// group.DefaultProfitControlEnabled holds the default value on creation for the profit_control_enabled field.
	group.DefaultProfitControlEnabled = groupDescProfitControlEnabled.Default.(bool)
	// groupDescProfitMinMargin is the schema descriptor for profit_min_margin field.
	groupDescProfitMinMargin := groupFields[38].Descriptor()
	// group.DefaultProfitMinMargin holds the default value on creation for the profit_min_margin field.
	group.DefaultProfitMinMargin = groupDescProfitMinMargin.Default.(float64)
	// groupDescProfitSafetyBuffer is the schema descriptor for profit_safety_buffer field.
	groupDescProfitSafetyBuffer := groupFields[39].Descriptor()
	// group.DefaultProfitSafetyBuffer holds the default value on creation for the profit_safety_buffer field.
	group.DefaultProfitSafetyBuffer = groupDescProfitSafetyBuffer.Default.(float64)
	idempotencyrecordMixin := schema.IdempotencyRecord{}.Mixin()
	idempotencyrecordMixinFields0 := idempotencyrecordMixin[0].Fields()
	_ = idempotencyrecordMixinFields0
	idempotencyrecordFields := schema.IdempotencyRecord{}.Fields()
	_ = idempotencyrecordFields
	// idempotencyrecordDescCreatedAt is the schema descriptor for created_at field.
	idempotencyrecordDescCreatedAt := idempotencyrecordMixinFields0[0].Descriptor()
	// idempotencyrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	idempotencyrecord.DefaultCreatedAt = idempotencyrecordDescCreatedAt.Default.(func() time.Time)
	// idempotencyrecordDescUpdatedAt is the schema descriptor for updated_at field.
	idempotencyrecordDescUpdatedAt := idempotencyrecordMixinFields0[1].Descriptor()
	// idempotencyrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	idempotencyrecord.DefaultUpdatedAt = idempotencyrecordDescUpdatedAt.Default.(func() time.Time)
	// idempotencyrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	idempotencyrecord.UpdateDefaultUpdatedAt = idempotencyrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// idempotencyrecordDescScope is the schema descriptor for scope field.
	idempotencyrecordDescScope := idempotencyrecordFields[0].Descriptor()
	// idempotencyrecord.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	idempotencyrecord.ScopeValidator = idempotencyrecordDescScope.Validators[0].(func(string) error)
	// idempotencyrecordDescIdempotencyKeyHash is the schema descriptor for idempotency_key_hash field.
	idempotencyrecordDescIdempotencyKeyHash := idempotencyrecordFields[1].Descriptor()
	// idempotencyrecord.IdempotencyKeyHashValidator is a validator for the "idempotency_key_hash" field. It is called by the builders before save.
	idempotencyrecord.IdempotencyKeyHashValidator = idempotencyrecordDescIdempotencyKeyHash.Validators[0].(func(string) error)
	// idempotencyrecordDescRequestFingerprint is the schema descriptor for request_fingerprint field.
	idempotencyrecordDescRequestFingerprint := idempotencyrecordFields[2].Descriptor()
	// idempotencyrecord.RequestFingerprintValidator is a validator for the "request_fingerprint" field. It is called by the builders before save.
	idempotencyrecord.RequestFingerprintValidator = idempotencyrecordDescRequestFingerprint.Validators[0].(func(string) error)
	// idempotencyrecordDescStatus is the schema descriptor for status field.
	idempotencyrecordDescStatus := idempotencyrecordFields[3].Descriptor()
	// idempotencyrecord.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	idempotencyrecord.StatusValidator = idempotencyrecordDescStatus.Validators[0].(func(string) error)
	// idempotencyrecordDescErrorReason is the schema descriptor for error_reason field.
	idempotencyrecordDescErrorReason := idempotencyrecordFields[6].Descriptor()
	// idempotencyrecord.ErrorReasonValidator is a validator for the "error_reason" field. It is called by the builders before save.
	idempotencyrecord.ErrorReasonValidator = idempotencyrecordDescErrorReason.Validators[0].(func(string) error)
	proxyMixin := schema.Proxy{}.Mixin()
	proxyMixinHooks1 := proxyMixin[1].Hooks()
	proxy.Hooks[0] = proxyMixinHooks1[0]
	proxyMixinInters1 := proxyMixin[1].Interceptors()
	proxy.Interceptors[0] = proxyMixinInters1[0]
	proxyMixinFields0 := proxyMixin[0].Fields()
	_ = proxyMixinFields0
	proxyFields := schema.Proxy{}.Fields()
	_ = proxyFields
	// proxyDescCreatedAt is the schema descriptor for created_at field.
	proxyDescCreatedAt := proxyMixinFields0[0].Descriptor()
	// proxy.DefaultCreatedAt holds the default value on creation for the created_at field.
	proxy.DefaultCreatedAt = proxyDescCreatedAt.Default.(func() time.Time)
	// proxyDescUpdatedAt is the schema descriptor for updated_at field.
	proxyDescUpdatedAt := proxyMixinFields0[1].Descriptor()
	// proxy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	proxy.DefaultUpdatedAt = proxyDescUpdatedAt.Default.(func() time.Time)
	// proxy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	proxy.UpdateDefaultUpdatedAt = proxyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// proxyDescName is the schema descriptor for name field.
	proxyDescName := proxyFields[0].Descriptor()
	// proxy.NameValidator is a validator for the "name" field. It is called by the builders before save.
	proxy.NameValidator = func() func(string) error {
		validators := proxyDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// proxyDescProtocol is the schema descriptor for protocol field.
	proxyDescProtocol := proxyFields[1].Descriptor()
	// proxy.ProtocolValidator is a validator for the "protocol" field. It is called by the builders before save.
	proxy.ProtocolValidator = func() func(string) error {
		validators := proxyDescProtocol.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(protocol string) error {
			for _, fn := range fns {
				if err := fn(protocol); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// proxyDescHost is the schema descriptor for host field.
	proxyDescHost := proxyFields[2].Descriptor()
	// proxy.HostValidator is a validator for the "host" field. It is called by the builders before save.
	proxy.HostValidator = func() func(string) error {
		validators := proxyDescHost.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(host string) error {
			for _, fn := range fns {
				if err := fn(host); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// proxyDescUsername is the schema descriptor for username field.
	proxyDescUsername := proxyFields[4].Descriptor()
	// proxy.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	proxy.UsernameValidator = proxyDescUsername.Validators[0].(func(string) error)
	// proxyDescPassword is the schema descriptor for password field.
	proxyDescPassword := proxyFields[5].Descriptor()
	// proxy.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	proxy.PasswordValidator = proxyDescPassword.Validators[0].(func(string) error)
	// proxyDescStatus is the schema descriptor for status field.
	proxyDescStatus := proxyFields[6].Descriptor()
	// proxy.DefaultStatus holds the default value on creation for the status field.
	proxy.DefaultStatus = proxyDescStatus.Default.(string)
	// proxy.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	proxy.StatusValidator = proxyDescStatus.Validators[0].(func(string) error)
	// proxyDescFallbackMode is the schema descriptor for fallback_mode field.
	proxyDescFallbackMode := proxyFields[8].Descriptor()
	// proxy.DefaultFallbackMode holds the default value on creation for the fallback_mode field.
	proxy.DefaultFallbackMode = proxyDescFallbackMode.Default.(string)
	// proxy.FallbackModeValidator is a validator for the "fallback_mode" field. It is called by the builders before save.
	proxy.FallbackModeValidator = proxyDescFallbackMode.Validators[0].(func(string) error)
	// proxyDescExpiryWarnDays is the schema descriptor for expiry_warn_days field.
	proxyDescExpiryWarnDays := proxyFields[10].Descriptor()
	// proxy.DefaultExpiryWarnDays holds the default value on creation for the expiry_warn_days field.
	proxy.DefaultExpiryWarnDays = proxyDescExpiryWarnDays.Default.(int)
	securitysecretMixin := schema.SecuritySecret{}.Mixin()
	securitysecretMixinFields0 := securitysecretMixin[0].Fields()
	_ = securitysecretMixinFields0
	securitysecretFields := schema.SecuritySecret{}.Fields()
	_ = securitysecretFields
	// securitysecretDescCreatedAt is the schema descriptor for created_at field.
	securitysecretDescCreatedAt := securitysecretMixinFields0[0].Descriptor()
	// securitysecret.DefaultCreatedAt holds the default value on creation for the created_at field.
	securitysecret.DefaultCreatedAt = securitysecretDescCreatedAt.Default.(func() time.Time)
	// securitysecretDescUpdatedAt is the schema descriptor for updated_at field.
	securitysecretDescUpdatedAt := securitysecretMixinFields0[1].Descriptor()
	// securitysecret.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	securitysecret.DefaultUpdatedAt = securitysecretDescUpdatedAt.Default.(func() time.Time)
	// securitysecret.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	securitysecret.UpdateDefaultUpdatedAt = securitysecretDescUpdatedAt.UpdateDefault.(func() time.Time)
	// securitysecretDescKey is the schema descriptor for key field.
	securitysecretDescKey := securitysecretFields[0].Descriptor()
	// securitysecret.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	securitysecret.KeyValidator = func() func(string) error {
		validators := securitysecretDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// securitysecretDescValue is the schema descriptor for value field.
	securitysecretDescValue := securitysecretFields[1].Descriptor()
	// securitysecret.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	securitysecret.ValueValidator = securitysecretDescValue.Validators[0].(func(string) error)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = func() func(string) error {
		validators := settingDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingFields[2].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	tlsfingerprintprofileMixin := schema.TLSFingerprintProfile{}.Mixin()
	tlsfingerprintprofileMixinFields0 := tlsfingerprintprofileMixin[0].Fields()
	_ = tlsfingerprintprofileMixinFields0
	tlsfingerprintprofileFields := schema.TLSFingerprintProfile{}.Fields()
	_ = tlsfingerprintprofileFields
	// tlsfingerprintprofileDescCreatedAt is the schema descriptor for created_at field.
	tlsfingerprintprofileDescCreatedAt := tlsfingerprintprofileMixinFields0[0].Descriptor()
	// tlsfingerprintprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	tlsfingerprintprofile.DefaultCreatedAt = tlsfingerprintprofileDescCreatedAt.Default.(func() time.Time)
	// tlsfingerprintprofileDescUpdatedAt is the schema descriptor for updated_at field.
	tlsfingerprintprofileDescUpdatedAt := tlsfingerprintprofileMixinFields0[1].Descriptor()
	// tlsfingerprintprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tlsfingerprintprofile.DefaultUpdatedAt = tlsfingerprintprofileDescUpdatedAt.Default.(func() time.Time)
	// tlsfingerprintprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tlsfingerprintprofile.UpdateDefaultUpdatedAt = tlsfingerprintprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tlsfingerprintprofileDescName is the schema descriptor for name field.
	tlsfingerprintprofileDescName := tlsfingerprintprofileFields[0].Descriptor()
	// tlsfingerprintprofile.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tlsfingerprintprofile.NameValidator = func() func(string) error {
		validators := tlsfingerprintprofileDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tlsfingerprintprofileDescEnableGrease is the schema descriptor for enable_grease field.
	tlsfingerprintprofileDescEnableGrease := tlsfingerprintprofileFields[2].Descriptor()
	// tlsfingerprintprofile.DefaultEnableGrease holds the default value on creation for the enable_grease field.
	tlsfingerprintprofile.DefaultEnableGrease = tlsfingerprintprofileDescEnableGrease.Default.(bool)
	usagelogFields := schema.UsageLog{}.Fields()
	_ = usagelogFields
	// usagelogDescRequestID is the schema descriptor for request_id field.
	usagelogDescRequestID := usagelogFields[3].Descriptor()
	// usagelog.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	usagelog.RequestIDValidator = func() func(string) error {
		validators := usagelogDescRequestID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(request_id string) error {
			for _, fn := range fns {
				if err := fn(request_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usagelogDescModel is the schema descriptor for model field.
	usagelogDescModel := usagelogFields[4].Descriptor()
	// usagelog.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	usagelog.ModelValidator = func() func(string) error {
		validators := usagelogDescModel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model string) error {
			for _, fn := range fns {
				if err := fn(model); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usagelogDescRequestedModel is the schema descriptor for requested_model field.
	usagelogDescRequestedModel := usagelogFields[5].Descriptor()
	// usagelog.RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	usagelog.RequestedModelValidator = usagelogDescRequestedModel.Validators[0].(func(string) error)
	// usagelogDescUpstreamModel is the schema descriptor for upstream_model field.
	usagelogDescUpstreamModel := usagelogFields[6].Descriptor()
	// usagelog.UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	usagelog.UpstreamModelValidator = usagelogDescUpstreamModel.Validators[0].(func(string) error)
	// usagelogDescModelMappingChain is the schema descriptor for model_mapping_chain field.
	usagelogDescModelMappingChain := usagelogFields[8].Descriptor()
	// usagelog.ModelMappingChainValidator is a validator for the "model_mapping_chain" field. It is called by the builders before save.
	usagelog.ModelMappingChainValidator = usagelogDescModelMappingChain.Validators[0].(func(string) error)
	// usagelogDescBillingTier is the schema descriptor for billing_tier field.
	usagelogDescBillingTier := usagelogFields[9].Descriptor()
	// usagelog.BillingTierValidator is a validator for the "billing_tier" field. It is called by the builders before save.
	usagelog.BillingTierValidator = usagelogDescBillingTier.Validators[0].(func(string) error)
	// usagelogDescBillingMode is the schema descriptor for billing_mode field.
	usagelogDescBillingMode := usagelogFields[10].Descriptor()
	// usagelog.BillingModeValidator is a validator for the "billing_mode" field. It is called by the builders before save.
	usagelog.BillingModeValidator = usagelogDescBillingMode.Validators[0].(func(string) error)
	// usagelogDescInputTokens is the schema descriptor for input_tokens field.
	usagelogDescInputTokens := usagelogFields[12].Descriptor()
	// usagelog.DefaultInputTokens holds the default value on creation for the input_tokens field.
	usagelog.DefaultInputTokens = usagelogDescInputTokens.Default.(int)
	// usagelogDescOutputTokens is the schema descriptor for output_tokens field.
	usagelogDescOutputTokens := usagelogFields[13].Descriptor()
	// usagelog.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	usagelog.DefaultOutputTokens = usagelogDescOutputTokens.Default.(int)
	// usagelogDescCacheCreationTokens is the schema descriptor for cache_creation_tokens field.
	usagelogDescCacheCreationTokens := usagelogFields[14].Descriptor()
	// usagelog.DefaultCacheCreationTokens holds the default value on creation for the cache_creation_tokens field.
	usagelog.DefaultCacheCreationTokens = usagelogDescCacheCreationTokens.Default.(int)
	// usagelogDescCacheReadTokens is the schema descriptor for cache_read_tokens field.
	usagelogDescCacheReadTokens := usagelogFields[15].Descriptor()
	// usagelog.DefaultCacheReadTokens holds the default value on creation for the cache_read_tokens field.
	usagelog.DefaultCacheReadTokens = usagelogDescCacheReadTokens.Default.(int)
	// usagelogDescCacheCreation5mTokens is the schema descriptor for cache_creation_5m_tokens field.
	usagelogDescCacheCreation5mTokens := usagelogFields[16].Descriptor()
	// usagelog.DefaultCacheCreation5mTokens holds the default value on creation for the cache_creation_5m_tokens field.
	usagelog.DefaultCacheCreation5mTokens = usagelogDescCacheCreation5mTokens.Default.(int)
	// usagelogDescCacheCreation1hTokens is the schema descriptor for cache_creation_1h_tokens field.
	usagelogDescCacheCreation1hTokens := usagelogFields[17].Descriptor()
	// usagelog.DefaultCacheCreation1hTokens holds the default value on creation for the cache_creation_1h_tokens field.
	usagelog.DefaultCacheCreation1hTokens = usagelogDescCacheCreation1hTokens.Default.(int)
	// usagelogDescInputCost is the schema descriptor for input_cost field.
	usagelogDescInputCost := usagelogFields[18].Descriptor()
	// usagelog.DefaultInputCost holds the default value on creation for the input_cost field.
	usagelog.DefaultInputCost = usagelogDescInputCost.Default.(float64)
	// usagelogDescOutputCost is the schema descriptor for output_cost field.
	usagelogDescOutputCost := usagelogFields[19].Descriptor()
	// usagelog.DefaultOutputCost holds the default value on creation for the output_cost field.
	usagelog.DefaultOutputCost = usagelogDescOutputCost.Default.(float64)
	// usagelogDescCacheCreationCost is the schema descriptor for cache_creation_cost field.
	usagelogDescCacheCreationCost := usagelogFields[20].Descriptor()
	// usagelog.DefaultCacheCreationCost holds the default value on creation for the cache_creation_cost field.
	usagelog.DefaultCacheCreationCost = usagelogDescCacheCreationCost.Default.(float64)
	// usagelogDescCacheReadCost is the schema descriptor for cache_read_cost field.
	usagelogDescCacheReadCost := usagelogFields[21].Descriptor()
	// usagelog.DefaultCacheReadCost holds the default value on creation for the cache_read_cost field.
	usagelog.DefaultCacheReadCost = usagelogDescCacheReadCost.Default.(float64)
	// usagelogDescTotalCost is the schema descriptor for total_cost field.
	usagelogDescTotalCost := usagelogFields[22].Descriptor()
	// usagelog.DefaultTotalCost holds the default value on creation for the total_cost field.
	usagelog.DefaultTotalCost = usagelogDescTotalCost.Default.(float64)
	// usagelogDescActualCost is the schema descriptor for actual_cost field.
	usagelogDescActualCost := usagelogFields[23].Descriptor()
	// usagelog.DefaultActualCost holds the default value on creation for the actual_cost field.
	usagelog.DefaultActualCost = usagelogDescActualCost.Default.(float64)
	// usagelogDescRateMultiplier is the schema descriptor for rate_multiplier field.
	usagelogDescRateMultiplier := usagelogFields[24].Descriptor()
	// usagelog.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	usagelog.DefaultRateMultiplier = usagelogDescRateMultiplier.Default.(float64)
	// usagelogDescLongContextBillingApplied is the schema descriptor for long_context_billing_applied field.
	usagelogDescLongContextBillingApplied := usagelogFields[25].Descriptor()
	// usagelog.DefaultLongContextBillingApplied holds the default value on creation for the long_context_billing_applied field.
	usagelog.DefaultLongContextBillingApplied = usagelogDescLongContextBillingApplied.Default.(bool)
	// usagelogDescStream is the schema descriptor for stream field.
	usagelogDescStream := usagelogFields[27].Descriptor()
	// usagelog.DefaultStream holds the default value on creation for the stream field.
	usagelog.DefaultStream = usagelogDescStream.Default.(bool)
	// usagelogDescUserAgent is the schema descriptor for user_agent field.
	usagelogDescUserAgent := usagelogFields[30].Descriptor()
	// usagelog.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	usagelog.UserAgentValidator = usagelogDescUserAgent.Validators[0].(func(string) error)
	// usagelogDescIPAddress is the schema descriptor for ip_address field.
	usagelogDescIPAddress := usagelogFields[31].Descriptor()
	// usagelog.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	usagelog.IPAddressValidator = usagelogDescIPAddress.Validators[0].(func(string) error)
	// usagelogDescImageCount is the schema descriptor for image_count field.
	usagelogDescImageCount := usagelogFields[32].Descriptor()
	// usagelog.DefaultImageCount holds the default value on creation for the image_count field.
	usagelog.DefaultImageCount = usagelogDescImageCount.Default.(int)
	// usagelogDescImageSize is the schema descriptor for image_size field.
	usagelogDescImageSize := usagelogFields[33].Descriptor()
	// usagelog.ImageSizeValidator is a validator for the "image_size" field. It is called by the builders before save.
	usagelog.ImageSizeValidator = usagelogDescImageSize.Validators[0].(func(string) error)
	// usagelogDescImageInputSize is the schema descriptor for image_input_size field.
	usagelogDescImageInputSize := usagelogFields[34].Descriptor()
	// usagelog.ImageInputSizeValidator is a validator for the "image_input_size" field. It is called by the builders before save.
	usagelog.ImageInputSizeValidator = usagelogDescImageInputSize.Validators[0].(func(string) error)
	// usagelogDescImageOutputSize is the schema descriptor for image_output_size field.
	usagelogDescImageOutputSize := usagelogFields[35].Descriptor()
	// usagelog.ImageOutputSizeValidator is a validator for the "image_output_size" field. It is called by the builders before save.
	usagelog.ImageOutputSizeValidator = usagelogDescImageOutputSize.Validators[0].(func(string) error)
	// usagelogDescImageSizeSource is the schema descriptor for image_size_source field.
	usagelogDescImageSizeSource := usagelogFields[36].Descriptor()
	// usagelog.ImageSizeSourceValidator is a validator for the "image_size_source" field. It is called by the builders before save.
	usagelog.ImageSizeSourceValidator = usagelogDescImageSizeSource.Validators[0].(func(string) error)
	// usagelogDescVideoCount is the schema descriptor for video_count field.
	usagelogDescVideoCount := usagelogFields[38].Descriptor()
	// usagelog.DefaultVideoCount holds the default value on creation for the video_count field.
	usagelog.DefaultVideoCount = usagelogDescVideoCount.Default.(int)
	// usagelogDescVideoResolution is the schema descriptor for video_resolution field.
	usagelogDescVideoResolution := usagelogFields[39].Descriptor()
	// usagelog.VideoResolutionValidator is a validator for the "video_resolution" field. It is called by the builders before save.
	usagelog.VideoResolutionValidator = usagelogDescVideoResolution.Validators[0].(func(string) error)
	// usagelogDescCacheTTLOverridden is the schema descriptor for cache_ttl_overridden field.
	usagelogDescCacheTTLOverridden := usagelogFields[41].Descriptor()
	// usagelog.DefaultCacheTTLOverridden holds the default value on creation for the cache_ttl_overridden field.
	usagelog.DefaultCacheTTLOverridden = usagelogDescCacheTTLOverridden.Default.(bool)
	// usagelogDescCreatedAt is the schema descriptor for created_at field.
	usagelogDescCreatedAt := usagelogFields[42].Descriptor()
	// usagelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	usagelog.DefaultCreatedAt = usagelogDescCreatedAt.Default.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinHooks1 := userMixin[1].Hooks()
	user.Hooks[0] = userMixinHooks1[0]
	userMixinInters1 := userMixin[1].Interceptors()
	user.Interceptors[0] = userMixinInters1[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[2].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescConcurrency is the schema descriptor for concurrency field.
	userDescConcurrency := userFields[3].Descriptor()
	// user.DefaultConcurrency holds the default value on creation for the concurrency field.
	user.DefaultConcurrency = userDescConcurrency.Default.(int)
	// userDescRequestSchedulingTier is the schema descriptor for request_scheduling_tier field.
	userDescRequestSchedulingTier := userFields[4].Descriptor()
	// user.DefaultRequestSchedulingTier holds the default value on creation for the request_scheduling_tier field.
	user.DefaultRequestSchedulingTier = userDescRequestSchedulingTier.Default.(int16)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[5].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[6].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescNotes is the schema descriptor for notes field.
	userDescNotes := userFields[7].Descriptor()
	// user.DefaultNotes holds the default value on creation for the notes field.
	user.DefaultNotes = userDescNotes.Default.(string)
	// userDescTotpEnabled is the schema descriptor for totp_enabled field.
	userDescTotpEnabled := userFields[9].Descriptor()
	// user.DefaultTotpEnabled holds the default value on creation for the totp_enabled field.
	user.DefaultTotpEnabled = userDescTotpEnabled.Default.(bool)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
