/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAnnouncements — thin orchestrator composable for Announcements.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAnnouncementsQueryStore } from '@/features/announcements/presentation/stores/announcementsQueryStore'
import { useAnnouncementsActionStore } from '@/features/announcements/presentation/stores/announcementsActionStore'

export function useAnnouncements() {
  const q_announcementsQueryStore = useAnnouncementsQueryStore()
  const a_announcementsActionStore = useAnnouncementsActionStore()
  return {
    ...q_announcementsQueryStore,
    ...a_announcementsActionStore,
  }
}
