/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminAccounts — thin orchestrator composable for AdminAccounts.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminAccountsQueryStore } from '@/features/admin-accounts/presentation/stores/adminAccountsQueryStore'
import { useAdminAccountsActionStore } from '@/features/admin-accounts/presentation/stores/adminAccountsActionStore'

export function useAdminAccounts() {
  const q_adminAccountsQueryStore = useAdminAccountsQueryStore()
  const a_adminAccountsActionStore = useAdminAccountsActionStore()
  return {
    ...q_adminAccountsQueryStore,
    ...a_adminAccountsActionStore,
  }
}
