/**
 * BillingQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createBillingQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { RedeemRepository } from '@/features/billing/domain/repositories/redeemRepository'
import { redeemRepository as default_redeem_repo } from '@/features/billing/data/repositories/redeemRepositoryImpl'

export function createBillingQueryStore(redeemRepo: RedeemRepository = default_redeem_repo) {
  return defineStore('billing/query', () => {
    const loading = reactive<Record<string, boolean>>({ getHistory: false })
    const errors = reactive<Record<string, unknown>>({ getHistory: null as unknown })

  const getHistory: RedeemRepository['getHistory'] = ((...args: unknown[]) => {
    loading.getHistory = true
    errors.getHistory = null
    return Promise.resolve()
      .then(() => (redeemRepo.getHistory as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getHistory = error; throw error })
      .finally(() => { loading.getHistory = false })
  }) as RedeemRepository['getHistory']

    return { loading, errors, getHistory }
  })
}

export const useBillingQueryStore = createBillingQueryStore()
