/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */
export { default as RiskControlPage } from './presentation/pages/RiskControlPage.vue'


// Route fragment — import in core/routes/index.ts

// export const adminRiskControlRoutes: RouteRecordRaw[] = [{ path: '/todo', component: RiskControlPage }]
