/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useKeys — thin orchestrator composable for Keys.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useKeysQueryStore } from '@/features/keys/presentation/stores/keysQueryStore'
import { useKeysActionStore } from '@/features/keys/presentation/stores/keysActionStore'

export function useKeys() {
  const q_keysQueryStore = useKeysQueryStore()
  const a_keysActionStore = useKeysActionStore()
  return {
    ...q_keysQueryStore,
    ...a_keysActionStore,
  }
}
