import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const billingRoutes: RouteRecordRaw[] = [
  {
    path: '/redeem',
    name: 'Redeem',
    component: () => import('@/features/billing/presentation/pages/RedeemPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: false, title: 'Redeem Code', titleKey: 'redeem.title', descriptionKey: 'redeem.description', simpleModeRestricted: true },
  },
  {
    path: '/purchase',
    name: 'PurchaseSubscription',
    component: () => import('@/features/billing/presentation/pages/PaymentPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: false, title: 'Purchase Subscription', titleKey: 'nav.buySubscription', descriptionKey: 'purchase.description', requiresPayment: true },
  },
  {
    path: '/orders',
    name: 'OrderList',
    component: () => import('@/features/billing/presentation/pages/UserOrdersPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: false, title: 'My Orders', titleKey: 'nav.myOrders', requiresPayment: true },
  },
  {
    path: '/payment/qrcode',
    name: 'PaymentQRCode',
    component: () => import('@/features/billing/presentation/pages/PaymentQRCodePage.vue'),
    meta: { requiresAuth: true, requiresAdmin: false, title: 'Payment', titleKey: 'payment.qr.scanToPay', requiresPayment: true },
  },
  {
    path: '/payment/result',
    name: 'PaymentResult',
    component: () => import('@/features/billing/presentation/pages/PaymentResultPage.vue'),
    meta: { requiresAuth: false, requiresAdmin: false, title: 'Payment Result', titleKey: 'payment.result.success', requiresPayment: false, backendModePublic: true },
  },
  {
    path: '/payment/stripe',
    name: 'StripePayment',
    component: () => import('@/features/billing/presentation/pages/StripePaymentPage.vue'),
    meta: { requiresAuth: false, requiresAdmin: false, title: 'Stripe Payment', titleKey: 'payment.stripePay', requiresPayment: false },
  },
  {
    path: '/payment/airwallex',
    name: 'AirwallexPayment',
    component: () => import('@/features/billing/presentation/pages/AirwallexPaymentPage.vue'),
    meta: { requiresAuth: false, requiresAdmin: false, title: 'Airwallex Payment', titleKey: 'payment.airwallexPay', requiresPayment: false, backendModePublic: true },
  },
  {
    path: '/payment/stripe-popup',
    name: 'StripePopup',
    component: () => import('@/features/billing/presentation/pages/StripePopupPage.vue'),
    meta: { requiresAuth: false, requiresAdmin: false, title: 'Payment', requiresPayment: false },
  },
]
