/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */
export { default as AirwallexPaymentPage } from './presentation/pages/AirwallexPaymentPage.vue'
export { default as PaymentPage } from './presentation/pages/PaymentPage.vue'
export { default as PaymentQRCodePage } from './presentation/pages/PaymentQRCodePage.vue'
export { default as PaymentResultPage } from './presentation/pages/PaymentResultPage.vue'
export { default as RedeemPage } from './presentation/pages/RedeemPage.vue'
export { default as StripePaymentPage } from './presentation/pages/StripePaymentPage.vue'
export { default as StripePopupPage } from './presentation/pages/StripePopupPage.vue'
export { default as UserOrdersPage } from './presentation/pages/UserOrdersPage.vue'
export { default as WechatPaymentCallbackPage } from './presentation/pages/WechatPaymentCallbackPage.vue'


// Route fragment — import in core/routes/index.ts

// export const billingRoutes: RouteRecordRaw[] = [{ path: '/todo', component: AirwallexPaymentPage }]
// export const billingRoutes: RouteRecordRaw[] = [{ path: '/todo', component: PaymentPage }]
// export const billingRoutes: RouteRecordRaw[] = [{ path: '/todo', component: PaymentQRCodePage }]
// export const billingRoutes: RouteRecordRaw[] = [{ path: '/todo', component: PaymentResultPage }]
// export const billingRoutes: RouteRecordRaw[] = [{ path: '/todo', component: RedeemPage }]
// export const billingRoutes: RouteRecordRaw[] = [{ path: '/todo', component: StripePaymentPage }]
// export const billingRoutes: RouteRecordRaw[] = [{ path: '/todo', component: StripePopupPage }]
// export const billingRoutes: RouteRecordRaw[] = [{ path: '/todo', component: UserOrdersPage }]
// export const billingRoutes: RouteRecordRaw[] = [{ path: '/todo', component: WechatPaymentCallbackPage }]
