import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const adminGroupsRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/groups',
    name: 'AdminGroups',
    component: () => import('@/features/admin-groups/presentation/pages/GroupsPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: true, title: 'Group Management', titleKey: 'admin.groups.title', descriptionKey: 'admin.groups.description', simpleModeRestricted: true },
  },
]
