/**
 * UsageQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createUsageQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { UsageRepository } from '@/features/usage/domain/repositories/usageRepository'
import { usageRepository as default_usage_repo } from '@/features/usage/data/repositories/usageRepositoryImpl'

export function createUsageQueryStore(usageRepo: UsageRepository = default_usage_repo) {
  return defineStore('usage/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, query: false, getStats: false, getStatsByDateRange: false, getByDateRange: false, getById: false, getDashboardStats: false, getDashboardTrend: false, getDashboardModels: false, getMyApiKeyDailyUsage: false, getDashboardSnapshotV2: false, getDashboardApiKeysUsage: false, listMyErrorRequests: false, getMyErrorDetail: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, query: null as unknown, getStats: null as unknown, getStatsByDateRange: null as unknown, getByDateRange: null as unknown, getById: null as unknown, getDashboardStats: null as unknown, getDashboardTrend: null as unknown, getDashboardModels: null as unknown, getMyApiKeyDailyUsage: null as unknown, getDashboardSnapshotV2: null as unknown, getDashboardApiKeysUsage: null as unknown, listMyErrorRequests: null as unknown, getMyErrorDetail: null as unknown })

  const list: UsageRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (usageRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as UsageRepository['list']

  const query: UsageRepository['query'] = ((...args: unknown[]) => {
    loading.query = true
    errors.query = null
    return Promise.resolve()
      .then(() => (usageRepo.query as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.query = error; throw error })
      .finally(() => { loading.query = false })
  }) as UsageRepository['query']

  const getStats: UsageRepository['getStats'] = ((...args: unknown[]) => {
    loading.getStats = true
    errors.getStats = null
    return Promise.resolve()
      .then(() => (usageRepo.getStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getStats = error; throw error })
      .finally(() => { loading.getStats = false })
  }) as UsageRepository['getStats']

  const getStatsByDateRange: UsageRepository['getStatsByDateRange'] = ((...args: unknown[]) => {
    loading.getStatsByDateRange = true
    errors.getStatsByDateRange = null
    return Promise.resolve()
      .then(() => (usageRepo.getStatsByDateRange as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getStatsByDateRange = error; throw error })
      .finally(() => { loading.getStatsByDateRange = false })
  }) as UsageRepository['getStatsByDateRange']

  const getByDateRange: UsageRepository['getByDateRange'] = ((...args: unknown[]) => {
    loading.getByDateRange = true
    errors.getByDateRange = null
    return Promise.resolve()
      .then(() => (usageRepo.getByDateRange as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getByDateRange = error; throw error })
      .finally(() => { loading.getByDateRange = false })
  }) as UsageRepository['getByDateRange']

  const getById: UsageRepository['getById'] = ((...args: unknown[]) => {
    loading.getById = true
    errors.getById = null
    return Promise.resolve()
      .then(() => (usageRepo.getById as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getById = error; throw error })
      .finally(() => { loading.getById = false })
  }) as UsageRepository['getById']

  const getDashboardStats: UsageRepository['getDashboardStats'] = ((...args: unknown[]) => {
    loading.getDashboardStats = true
    errors.getDashboardStats = null
    return Promise.resolve()
      .then(() => (usageRepo.getDashboardStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getDashboardStats = error; throw error })
      .finally(() => { loading.getDashboardStats = false })
  }) as UsageRepository['getDashboardStats']

  const getDashboardTrend: UsageRepository['getDashboardTrend'] = ((...args: unknown[]) => {
    loading.getDashboardTrend = true
    errors.getDashboardTrend = null
    return Promise.resolve()
      .then(() => (usageRepo.getDashboardTrend as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getDashboardTrend = error; throw error })
      .finally(() => { loading.getDashboardTrend = false })
  }) as UsageRepository['getDashboardTrend']

  const getDashboardModels: UsageRepository['getDashboardModels'] = ((...args: unknown[]) => {
    loading.getDashboardModels = true
    errors.getDashboardModels = null
    return Promise.resolve()
      .then(() => (usageRepo.getDashboardModels as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getDashboardModels = error; throw error })
      .finally(() => { loading.getDashboardModels = false })
  }) as UsageRepository['getDashboardModels']

  const getMyApiKeyDailyUsage: UsageRepository['getMyApiKeyDailyUsage'] = ((...args: unknown[]) => {
    loading.getMyApiKeyDailyUsage = true
    errors.getMyApiKeyDailyUsage = null
    return Promise.resolve()
      .then(() => (usageRepo.getMyApiKeyDailyUsage as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getMyApiKeyDailyUsage = error; throw error })
      .finally(() => { loading.getMyApiKeyDailyUsage = false })
  }) as UsageRepository['getMyApiKeyDailyUsage']

  const getDashboardSnapshotV2: UsageRepository['getDashboardSnapshotV2'] = ((...args: unknown[]) => {
    loading.getDashboardSnapshotV2 = true
    errors.getDashboardSnapshotV2 = null
    return Promise.resolve()
      .then(() => (usageRepo.getDashboardSnapshotV2 as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getDashboardSnapshotV2 = error; throw error })
      .finally(() => { loading.getDashboardSnapshotV2 = false })
  }) as UsageRepository['getDashboardSnapshotV2']

  const getDashboardApiKeysUsage: UsageRepository['getDashboardApiKeysUsage'] = ((...args: unknown[]) => {
    loading.getDashboardApiKeysUsage = true
    errors.getDashboardApiKeysUsage = null
    return Promise.resolve()
      .then(() => (usageRepo.getDashboardApiKeysUsage as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getDashboardApiKeysUsage = error; throw error })
      .finally(() => { loading.getDashboardApiKeysUsage = false })
  }) as UsageRepository['getDashboardApiKeysUsage']

  const listMyErrorRequests: UsageRepository['listMyErrorRequests'] = ((...args: unknown[]) => {
    loading.listMyErrorRequests = true
    errors.listMyErrorRequests = null
    return Promise.resolve()
      .then(() => (usageRepo.listMyErrorRequests as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listMyErrorRequests = error; throw error })
      .finally(() => { loading.listMyErrorRequests = false })
  }) as UsageRepository['listMyErrorRequests']

  const getMyErrorDetail: UsageRepository['getMyErrorDetail'] = ((...args: unknown[]) => {
    loading.getMyErrorDetail = true
    errors.getMyErrorDetail = null
    return Promise.resolve()
      .then(() => (usageRepo.getMyErrorDetail as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getMyErrorDetail = error; throw error })
      .finally(() => { loading.getMyErrorDetail = false })
  }) as UsageRepository['getMyErrorDetail']

    return { loading, errors, list, query, getStats, getStatsByDateRange, getByDateRange, getById, getDashboardStats, getDashboardTrend, getDashboardModels, getMyApiKeyDailyUsage, getDashboardSnapshotV2, getDashboardApiKeysUsage, listMyErrorRequests, getMyErrorDetail }
  })
}

export const useUsageQueryStore = createUsageQueryStore()
