import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const adminOpsRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/ops',
    name: 'AdminOps',
    component: () => import('@/features/admin-ops/presentation/pages/OpsDashboardPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: true, title: 'Ops Monitoring', titleKey: 'admin.ops.title', descriptionKey: 'admin.ops.description' },
  },
]
