/**
 * AuthQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAuthQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AuthRepository } from '@/features/auth/domain/repositories/authRepository'
import { authRepository as default_auth_repo } from '@/features/auth/data/repositories/authRepositoryImpl'

export function createAuthQueryStore(authRepo: AuthRepository = default_auth_repo) {
  return defineStore('auth/query', () => {
    const loading = reactive<Record<string, boolean>>({ getCurrentUser: false, getPublicSettings: false, getLocalCaptcha: false })
    const errors = reactive<Record<string, unknown>>({ getCurrentUser: null as unknown, getPublicSettings: null as unknown, getLocalCaptcha: null as unknown })

  const getCurrentUser: AuthRepository['getCurrentUser'] = ((...args: unknown[]) => {
    loading.getCurrentUser = true
    errors.getCurrentUser = null
    return Promise.resolve()
      .then(() => (authRepo.getCurrentUser as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getCurrentUser = error; throw error })
      .finally(() => { loading.getCurrentUser = false })
  }) as AuthRepository['getCurrentUser']

  const getPublicSettings: AuthRepository['getPublicSettings'] = ((...args: unknown[]) => {
    loading.getPublicSettings = true
    errors.getPublicSettings = null
    return Promise.resolve()
      .then(() => (authRepo.getPublicSettings as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getPublicSettings = error; throw error })
      .finally(() => { loading.getPublicSettings = false })
  }) as AuthRepository['getPublicSettings']

  const getLocalCaptcha: AuthRepository['getLocalCaptcha'] = ((...args: unknown[]) => {
    loading.getLocalCaptcha = true
    errors.getLocalCaptcha = null
    return Promise.resolve()
      .then(() => (authRepo.getLocalCaptcha as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getLocalCaptcha = error; throw error })
      .finally(() => { loading.getLocalCaptcha = false })
  }) as AuthRepository['getLocalCaptcha']

    return { loading, errors, getCurrentUser, getPublicSettings, getLocalCaptcha }
  })
}

export const useAuthQueryStore = createAuthQueryStore()
