/**
 * AuthActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAuthActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AuthRepository } from '@/features/auth/domain/repositories/authRepository'
import { authRepository as default_auth_repo } from '@/features/auth/data/repositories/authRepositoryImpl'

export function createAuthActionStore(authRepo: AuthRepository = default_auth_repo) {
  return defineStore('auth/action', () => {
    const loading = reactive<Record<string, boolean>>({ login: false, login2FA: false, register: false, logout: false, prepareOAuthBindAccessTokenCookie: false, refreshToken: false, revokeAllSessions: false, sendVerifyCode: false, sendPendingOAuthVerifyCode: false, validatePromoCode: false, validateInvitationCode: false, forgotPassword: false, resetPassword: false, completeLinuxDoOAuthRegistration: false, completeOIDCOAuthRegistration: false, completeWeChatOAuthRegistration: false, createPendingLinuxDoOAuthAccount: false, createPendingOIDCOAuthAccount: false, createPendingWeChatOAuthAccount: false, createPendingDingTalkOAuthAccount: false, completePendingOAuthBindLogin: false, exchangePendingOAuthCompletion: false })
    const errors = reactive<Record<string, unknown>>({ login: null as unknown, login2FA: null as unknown, register: null as unknown, logout: null as unknown, prepareOAuthBindAccessTokenCookie: null as unknown, refreshToken: null as unknown, revokeAllSessions: null as unknown, sendVerifyCode: null as unknown, sendPendingOAuthVerifyCode: null as unknown, validatePromoCode: null as unknown, validateInvitationCode: null as unknown, forgotPassword: null as unknown, resetPassword: null as unknown, completeLinuxDoOAuthRegistration: null as unknown, completeOIDCOAuthRegistration: null as unknown, completeWeChatOAuthRegistration: null as unknown, createPendingLinuxDoOAuthAccount: null as unknown, createPendingOIDCOAuthAccount: null as unknown, createPendingWeChatOAuthAccount: null as unknown, createPendingDingTalkOAuthAccount: null as unknown, completePendingOAuthBindLogin: null as unknown, exchangePendingOAuthCompletion: null as unknown })

  const login: AuthRepository['login'] = ((...args: unknown[]) => {
    loading.login = true
    errors.login = null
    return Promise.resolve()
      .then(() => (authRepo.login as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.login = error; throw error })
      .finally(() => { loading.login = false })
  }) as AuthRepository['login']

  const login2FA: AuthRepository['login2FA'] = ((...args: unknown[]) => {
    loading.login2FA = true
    errors.login2FA = null
    return Promise.resolve()
      .then(() => (authRepo.login2FA as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.login2FA = error; throw error })
      .finally(() => { loading.login2FA = false })
  }) as AuthRepository['login2FA']

  const register: AuthRepository['register'] = ((...args: unknown[]) => {
    loading.register = true
    errors.register = null
    return Promise.resolve()
      .then(() => (authRepo.register as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.register = error; throw error })
      .finally(() => { loading.register = false })
  }) as AuthRepository['register']

  const logout: AuthRepository['logout'] = ((...args: unknown[]) => {
    loading.logout = true
    errors.logout = null
    return Promise.resolve()
      .then(() => (authRepo.logout as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.logout = error; throw error })
      .finally(() => { loading.logout = false })
  }) as AuthRepository['logout']

  const prepareOAuthBindAccessTokenCookie: AuthRepository['prepareOAuthBindAccessTokenCookie'] = ((...args: unknown[]) => {
    loading.prepareOAuthBindAccessTokenCookie = true
    errors.prepareOAuthBindAccessTokenCookie = null
    return Promise.resolve()
      .then(() => (authRepo.prepareOAuthBindAccessTokenCookie as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.prepareOAuthBindAccessTokenCookie = error; throw error })
      .finally(() => { loading.prepareOAuthBindAccessTokenCookie = false })
  }) as AuthRepository['prepareOAuthBindAccessTokenCookie']

  const refreshToken: AuthRepository['refreshToken'] = ((...args: unknown[]) => {
    loading.refreshToken = true
    errors.refreshToken = null
    return Promise.resolve()
      .then(() => (authRepo.refreshToken as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.refreshToken = error; throw error })
      .finally(() => { loading.refreshToken = false })
  }) as AuthRepository['refreshToken']

  const revokeAllSessions: AuthRepository['revokeAllSessions'] = ((...args: unknown[]) => {
    loading.revokeAllSessions = true
    errors.revokeAllSessions = null
    return Promise.resolve()
      .then(() => (authRepo.revokeAllSessions as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.revokeAllSessions = error; throw error })
      .finally(() => { loading.revokeAllSessions = false })
  }) as AuthRepository['revokeAllSessions']

  const sendVerifyCode: AuthRepository['sendVerifyCode'] = ((...args: unknown[]) => {
    loading.sendVerifyCode = true
    errors.sendVerifyCode = null
    return Promise.resolve()
      .then(() => (authRepo.sendVerifyCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.sendVerifyCode = error; throw error })
      .finally(() => { loading.sendVerifyCode = false })
  }) as AuthRepository['sendVerifyCode']

  const sendPendingOAuthVerifyCode: AuthRepository['sendPendingOAuthVerifyCode'] = ((...args: unknown[]) => {
    loading.sendPendingOAuthVerifyCode = true
    errors.sendPendingOAuthVerifyCode = null
    return Promise.resolve()
      .then(() => (authRepo.sendPendingOAuthVerifyCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.sendPendingOAuthVerifyCode = error; throw error })
      .finally(() => { loading.sendPendingOAuthVerifyCode = false })
  }) as AuthRepository['sendPendingOAuthVerifyCode']

  const validatePromoCode: AuthRepository['validatePromoCode'] = ((...args: unknown[]) => {
    loading.validatePromoCode = true
    errors.validatePromoCode = null
    return Promise.resolve()
      .then(() => (authRepo.validatePromoCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.validatePromoCode = error; throw error })
      .finally(() => { loading.validatePromoCode = false })
  }) as AuthRepository['validatePromoCode']

  const validateInvitationCode: AuthRepository['validateInvitationCode'] = ((...args: unknown[]) => {
    loading.validateInvitationCode = true
    errors.validateInvitationCode = null
    return Promise.resolve()
      .then(() => (authRepo.validateInvitationCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.validateInvitationCode = error; throw error })
      .finally(() => { loading.validateInvitationCode = false })
  }) as AuthRepository['validateInvitationCode']

  const forgotPassword: AuthRepository['forgotPassword'] = ((...args: unknown[]) => {
    loading.forgotPassword = true
    errors.forgotPassword = null
    return Promise.resolve()
      .then(() => (authRepo.forgotPassword as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.forgotPassword = error; throw error })
      .finally(() => { loading.forgotPassword = false })
  }) as AuthRepository['forgotPassword']

  const resetPassword: AuthRepository['resetPassword'] = ((...args: unknown[]) => {
    loading.resetPassword = true
    errors.resetPassword = null
    return Promise.resolve()
      .then(() => (authRepo.resetPassword as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.resetPassword = error; throw error })
      .finally(() => { loading.resetPassword = false })
  }) as AuthRepository['resetPassword']

  const completeLinuxDoOAuthRegistration: AuthRepository['completeLinuxDoOAuthRegistration'] = ((...args: unknown[]) => {
    loading.completeLinuxDoOAuthRegistration = true
    errors.completeLinuxDoOAuthRegistration = null
    return Promise.resolve()
      .then(() => (authRepo.completeLinuxDoOAuthRegistration as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.completeLinuxDoOAuthRegistration = error; throw error })
      .finally(() => { loading.completeLinuxDoOAuthRegistration = false })
  }) as AuthRepository['completeLinuxDoOAuthRegistration']

  const completeOIDCOAuthRegistration: AuthRepository['completeOIDCOAuthRegistration'] = ((...args: unknown[]) => {
    loading.completeOIDCOAuthRegistration = true
    errors.completeOIDCOAuthRegistration = null
    return Promise.resolve()
      .then(() => (authRepo.completeOIDCOAuthRegistration as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.completeOIDCOAuthRegistration = error; throw error })
      .finally(() => { loading.completeOIDCOAuthRegistration = false })
  }) as AuthRepository['completeOIDCOAuthRegistration']

  const completeWeChatOAuthRegistration: AuthRepository['completeWeChatOAuthRegistration'] = ((...args: unknown[]) => {
    loading.completeWeChatOAuthRegistration = true
    errors.completeWeChatOAuthRegistration = null
    return Promise.resolve()
      .then(() => (authRepo.completeWeChatOAuthRegistration as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.completeWeChatOAuthRegistration = error; throw error })
      .finally(() => { loading.completeWeChatOAuthRegistration = false })
  }) as AuthRepository['completeWeChatOAuthRegistration']

  const createPendingLinuxDoOAuthAccount: AuthRepository['createPendingLinuxDoOAuthAccount'] = ((...args: unknown[]) => {
    loading.createPendingLinuxDoOAuthAccount = true
    errors.createPendingLinuxDoOAuthAccount = null
    return Promise.resolve()
      .then(() => (authRepo.createPendingLinuxDoOAuthAccount as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createPendingLinuxDoOAuthAccount = error; throw error })
      .finally(() => { loading.createPendingLinuxDoOAuthAccount = false })
  }) as AuthRepository['createPendingLinuxDoOAuthAccount']

  const createPendingOIDCOAuthAccount: AuthRepository['createPendingOIDCOAuthAccount'] = ((...args: unknown[]) => {
    loading.createPendingOIDCOAuthAccount = true
    errors.createPendingOIDCOAuthAccount = null
    return Promise.resolve()
      .then(() => (authRepo.createPendingOIDCOAuthAccount as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createPendingOIDCOAuthAccount = error; throw error })
      .finally(() => { loading.createPendingOIDCOAuthAccount = false })
  }) as AuthRepository['createPendingOIDCOAuthAccount']

  const createPendingWeChatOAuthAccount: AuthRepository['createPendingWeChatOAuthAccount'] = ((...args: unknown[]) => {
    loading.createPendingWeChatOAuthAccount = true
    errors.createPendingWeChatOAuthAccount = null
    return Promise.resolve()
      .then(() => (authRepo.createPendingWeChatOAuthAccount as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createPendingWeChatOAuthAccount = error; throw error })
      .finally(() => { loading.createPendingWeChatOAuthAccount = false })
  }) as AuthRepository['createPendingWeChatOAuthAccount']

  const createPendingDingTalkOAuthAccount: AuthRepository['createPendingDingTalkOAuthAccount'] = ((...args: unknown[]) => {
    loading.createPendingDingTalkOAuthAccount = true
    errors.createPendingDingTalkOAuthAccount = null
    return Promise.resolve()
      .then(() => (authRepo.createPendingDingTalkOAuthAccount as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createPendingDingTalkOAuthAccount = error; throw error })
      .finally(() => { loading.createPendingDingTalkOAuthAccount = false })
  }) as AuthRepository['createPendingDingTalkOAuthAccount']

  const completePendingOAuthBindLogin: AuthRepository['completePendingOAuthBindLogin'] = ((...args: unknown[]) => {
    loading.completePendingOAuthBindLogin = true
    errors.completePendingOAuthBindLogin = null
    return Promise.resolve()
      .then(() => (authRepo.completePendingOAuthBindLogin as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.completePendingOAuthBindLogin = error; throw error })
      .finally(() => { loading.completePendingOAuthBindLogin = false })
  }) as AuthRepository['completePendingOAuthBindLogin']

  const exchangePendingOAuthCompletion: AuthRepository['exchangePendingOAuthCompletion'] = ((...args: unknown[]) => {
    loading.exchangePendingOAuthCompletion = true
    errors.exchangePendingOAuthCompletion = null
    return Promise.resolve()
      .then(() => (authRepo.exchangePendingOAuthCompletion as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.exchangePendingOAuthCompletion = error; throw error })
      .finally(() => { loading.exchangePendingOAuthCompletion = false })
  }) as AuthRepository['exchangePendingOAuthCompletion']

    return { loading, errors, login, login2FA, register, logout, prepareOAuthBindAccessTokenCookie, refreshToken, revokeAllSessions, sendVerifyCode, sendPendingOAuthVerifyCode, validatePromoCode, validateInvitationCode, forgotPassword, resetPassword, completeLinuxDoOAuthRegistration, completeOIDCOAuthRegistration, completeWeChatOAuthRegistration, createPendingLinuxDoOAuthAccount, createPendingOIDCOAuthAccount, createPendingWeChatOAuthAccount, createPendingDingTalkOAuthAccount, completePendingOAuthBindLogin, exchangePendingOAuthCompletion }
  })
}

export const useAuthActionStore = createAuthActionStore()
