/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { list, getById, create, update, deleteKey, toggleStatus, keysAPI } from '@/features/keys/data/datasources/keysDatasource'
export { default } from '@/features/keys/data/datasources/keysDatasource'
