/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminOps — thin orchestrator composable for AdminOps.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminOpsQueryStore } from '@/features/admin-ops/presentation/stores/adminOpsQueryStore'
import { useAdminOpsActionStore } from '@/features/admin-ops/presentation/stores/adminOpsActionStore'

export function useAdminOps() {
  const q_adminOpsQueryStore = useAdminOpsQueryStore()
  const a_adminOpsActionStore = useAdminOpsActionStore()
  return {
    ...q_adminOpsQueryStore,
    ...a_adminOpsActionStore,
  }
}
