/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useBatchImage — thin orchestrator composable for BatchImage.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useBatchImageQueryStore } from '@/features/batch-image/presentation/stores/batchImageQueryStore'
import { useBatchImageActionStore } from '@/features/batch-image/presentation/stores/batchImageActionStore'

export function useBatchImage() {
  const q_batchImageQueryStore = useBatchImageQueryStore()
  const a_batchImageActionStore = useBatchImageActionStore()
  return {
    ...q_batchImageQueryStore,
    ...a_batchImageActionStore,
  }
}
