/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { listUsers, lookupUsers, updateUserSettings, clearUserSettings, batchSetRate, listInviteRecords, listRebateRecords, listTransferRecords, getUserOverview, affiliatesAPI } from '@/features/affiliate/data/datasources/adminAffiliatesDatasource'
export type { AffiliateAdminEntry, ListAffiliateUsersParams, ListAffiliateRecordsParams, AffiliateInviteRecord, AffiliateRebateRecord, AffiliateTransferRecord, AffiliateUserOverview, UpdateAffiliateUserRequest, BatchSetRateRequest, SimpleUser } from '@/features/affiliate/data/datasources/adminAffiliatesDatasource'
export { default } from '@/features/affiliate/data/datasources/adminAffiliatesDatasource'
