/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 */
export * from '@/features/affiliate/data/datasources/adminAffiliatesDatasource'
export { default } from '@/features/affiliate/data/datasources/adminAffiliatesDatasource'
