/**
 * ChannelsUserQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createChannelsUserQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { ChannelsUserRepository } from '@/features/channels-user/domain/repositories/channelsUserRepository'
import { channelsUserRepository as default_channelsUser_repo } from '@/features/channels-user/data/repositories/channelsUserRepositoryImpl'

export function createChannelsUserQueryStore(channelsUserRepo: ChannelsUserRepository = default_channelsUser_repo) {
  return defineStore('channelsUser/query', () => {
    const loading = reactive<Record<string, boolean>>({ getAvailable: false })
    const errors = reactive<Record<string, unknown>>({ getAvailable: null as unknown })

  const getAvailable: ChannelsUserRepository['getAvailable'] = ((...args: unknown[]) => {
    loading.getAvailable = true
    errors.getAvailable = null
    return Promise.resolve()
      .then(() => (channelsUserRepo.getAvailable as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAvailable = error; throw error })
      .finally(() => { loading.getAvailable = false })
  }) as ChannelsUserRepository['getAvailable']

    return { loading, errors, getAvailable }
  })
}

export const useChannelsUserQueryStore = createChannelsUserQueryStore()
