/**
 * AdminUsersQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminUsersQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminUsersRepository } from '@/features/admin-users/domain/repositories/adminUsersRepository'
import type { UserAttributesRepository } from '@/features/admin-users/domain/repositories/userAttributesRepository'
import { adminUsersRepository as default_adminUsers_repo } from '@/features/admin-users/data/repositories/adminUsersRepositoryImpl'
import { userAttributesRepository as default_userAttributes_repo } from '@/features/admin-users/data/repositories/userAttributesRepositoryImpl'

export function createAdminUsersQueryStore(adminUsersRepo: AdminUsersRepository = default_adminUsers_repo, userAttributesRepo: UserAttributesRepository = default_userAttributes_repo) {
  return defineStore('adminUsers/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, getById: false, getUserApiKeys: false, getUserUsageStats: false, getUserBalanceHistory: false, getPlatformQuotas: false, getBatchPlatformQuotas: false, listDefinitions: false, listEnabledDefinitions: false, getUserAttributeValues: false, getBatchUserAttributes: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, getById: null as unknown, getUserApiKeys: null as unknown, getUserUsageStats: null as unknown, getUserBalanceHistory: null as unknown, getPlatformQuotas: null as unknown, getBatchPlatformQuotas: null as unknown, listDefinitions: null as unknown, listEnabledDefinitions: null as unknown, getUserAttributeValues: null as unknown, getBatchUserAttributes: null as unknown })

  const list: AdminUsersRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (adminUsersRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as AdminUsersRepository['list']

  const getById: AdminUsersRepository['getById'] = ((...args: unknown[]) => {
    loading.getById = true
    errors.getById = null
    return Promise.resolve()
      .then(() => (adminUsersRepo.getById as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getById = error; throw error })
      .finally(() => { loading.getById = false })
  }) as AdminUsersRepository['getById']

  const getUserApiKeys: AdminUsersRepository['getUserApiKeys'] = ((...args: unknown[]) => {
    loading.getUserApiKeys = true
    errors.getUserApiKeys = null
    return Promise.resolve()
      .then(() => (adminUsersRepo.getUserApiKeys as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserApiKeys = error; throw error })
      .finally(() => { loading.getUserApiKeys = false })
  }) as AdminUsersRepository['getUserApiKeys']

  const getUserUsageStats: AdminUsersRepository['getUserUsageStats'] = ((...args: unknown[]) => {
    loading.getUserUsageStats = true
    errors.getUserUsageStats = null
    return Promise.resolve()
      .then(() => (adminUsersRepo.getUserUsageStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserUsageStats = error; throw error })
      .finally(() => { loading.getUserUsageStats = false })
  }) as AdminUsersRepository['getUserUsageStats']

  const getUserBalanceHistory: AdminUsersRepository['getUserBalanceHistory'] = ((...args: unknown[]) => {
    loading.getUserBalanceHistory = true
    errors.getUserBalanceHistory = null
    return Promise.resolve()
      .then(() => (adminUsersRepo.getUserBalanceHistory as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserBalanceHistory = error; throw error })
      .finally(() => { loading.getUserBalanceHistory = false })
  }) as AdminUsersRepository['getUserBalanceHistory']

  const getPlatformQuotas: AdminUsersRepository['getPlatformQuotas'] = ((...args: unknown[]) => {
    loading.getPlatformQuotas = true
    errors.getPlatformQuotas = null
    return Promise.resolve()
      .then(() => (adminUsersRepo.getPlatformQuotas as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getPlatformQuotas = error; throw error })
      .finally(() => { loading.getPlatformQuotas = false })
  }) as AdminUsersRepository['getPlatformQuotas']

  const getBatchPlatformQuotas: AdminUsersRepository['getBatchPlatformQuotas'] = ((...args: unknown[]) => {
    loading.getBatchPlatformQuotas = true
    errors.getBatchPlatformQuotas = null
    return Promise.resolve()
      .then(() => (adminUsersRepo.getBatchPlatformQuotas as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getBatchPlatformQuotas = error; throw error })
      .finally(() => { loading.getBatchPlatformQuotas = false })
  }) as AdminUsersRepository['getBatchPlatformQuotas']

  const listDefinitions: UserAttributesRepository['listDefinitions'] = ((...args: unknown[]) => {
    loading.listDefinitions = true
    errors.listDefinitions = null
    return Promise.resolve()
      .then(() => (userAttributesRepo.listDefinitions as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listDefinitions = error; throw error })
      .finally(() => { loading.listDefinitions = false })
  }) as UserAttributesRepository['listDefinitions']

  const listEnabledDefinitions: UserAttributesRepository['listEnabledDefinitions'] = ((...args: unknown[]) => {
    loading.listEnabledDefinitions = true
    errors.listEnabledDefinitions = null
    return Promise.resolve()
      .then(() => (userAttributesRepo.listEnabledDefinitions as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listEnabledDefinitions = error; throw error })
      .finally(() => { loading.listEnabledDefinitions = false })
  }) as UserAttributesRepository['listEnabledDefinitions']

  const getUserAttributeValues: UserAttributesRepository['getUserAttributeValues'] = ((...args: unknown[]) => {
    loading.getUserAttributeValues = true
    errors.getUserAttributeValues = null
    return Promise.resolve()
      .then(() => (userAttributesRepo.getUserAttributeValues as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserAttributeValues = error; throw error })
      .finally(() => { loading.getUserAttributeValues = false })
  }) as UserAttributesRepository['getUserAttributeValues']

  const getBatchUserAttributes: UserAttributesRepository['getBatchUserAttributes'] = ((...args: unknown[]) => {
    loading.getBatchUserAttributes = true
    errors.getBatchUserAttributes = null
    return Promise.resolve()
      .then(() => (userAttributesRepo.getBatchUserAttributes as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getBatchUserAttributes = error; throw error })
      .finally(() => { loading.getBatchUserAttributes = false })
  }) as UserAttributesRepository['getBatchUserAttributes']

    return { loading, errors, list, getById, getUserApiKeys, getUserUsageStats, getUserBalanceHistory, getPlatformQuotas, getBatchPlatformQuotas, listDefinitions, listEnabledDefinitions, getUserAttributeValues, getBatchUserAttributes }
  })
}

export const useAdminUsersQueryStore = createAdminUsersQueryStore()
