/**
 * AdminGroupsActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminGroupsActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminGroupsRepository } from '@/features/admin-groups/domain/repositories/adminGroupsRepository'
import { adminGroupsRepository as default_adminGroups_repo } from '@/features/admin-groups/data/repositories/adminGroupsRepositoryImpl'

export function createAdminGroupsActionStore(adminGroupsRepo: AdminGroupsRepository = default_adminGroups_repo) {
  return defineStore('adminGroups/action', () => {
    const loading = reactive<Record<string, boolean>>({ create: false, duplicate: false, update: false, deleteGroup: false, toggleStatus: false, createCompositeRoute: false, updateCompositeRoute: false, deleteCompositeRoute: false, updateSortOrder: false, clearGroupRateMultipliers: false, batchSetGroupRateMultipliers: false, batchSetGroupRPMOverrides: false, clearGroupRPMOverrides: false })
    const errors = reactive<Record<string, unknown>>({ create: null as unknown, duplicate: null as unknown, update: null as unknown, deleteGroup: null as unknown, toggleStatus: null as unknown, createCompositeRoute: null as unknown, updateCompositeRoute: null as unknown, deleteCompositeRoute: null as unknown, updateSortOrder: null as unknown, clearGroupRateMultipliers: null as unknown, batchSetGroupRateMultipliers: null as unknown, batchSetGroupRPMOverrides: null as unknown, clearGroupRPMOverrides: null as unknown })

  const create: AdminGroupsRepository['create'] = ((...args: unknown[]) => {
    loading.create = true
    errors.create = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.create as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.create = error; throw error })
      .finally(() => { loading.create = false })
  }) as AdminGroupsRepository['create']

  const duplicate: AdminGroupsRepository['duplicate'] = ((...args: unknown[]) => {
    loading.duplicate = true
    errors.duplicate = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.duplicate as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.duplicate = error; throw error })
      .finally(() => { loading.duplicate = false })
  }) as AdminGroupsRepository['duplicate']

  const update: AdminGroupsRepository['update'] = ((...args: unknown[]) => {
    loading.update = true
    errors.update = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.update as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.update = error; throw error })
      .finally(() => { loading.update = false })
  }) as AdminGroupsRepository['update']

  const deleteGroup: AdminGroupsRepository['deleteGroup'] = ((...args: unknown[]) => {
    loading.deleteGroup = true
    errors.deleteGroup = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.deleteGroup as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteGroup = error; throw error })
      .finally(() => { loading.deleteGroup = false })
  }) as AdminGroupsRepository['deleteGroup']

  const toggleStatus: AdminGroupsRepository['toggleStatus'] = ((...args: unknown[]) => {
    loading.toggleStatus = true
    errors.toggleStatus = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.toggleStatus as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.toggleStatus = error; throw error })
      .finally(() => { loading.toggleStatus = false })
  }) as AdminGroupsRepository['toggleStatus']

  const createCompositeRoute: AdminGroupsRepository['createCompositeRoute'] = ((...args: unknown[]) => {
    loading.createCompositeRoute = true
    errors.createCompositeRoute = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.createCompositeRoute as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createCompositeRoute = error; throw error })
      .finally(() => { loading.createCompositeRoute = false })
  }) as AdminGroupsRepository['createCompositeRoute']

  const updateCompositeRoute: AdminGroupsRepository['updateCompositeRoute'] = ((...args: unknown[]) => {
    loading.updateCompositeRoute = true
    errors.updateCompositeRoute = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.updateCompositeRoute as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateCompositeRoute = error; throw error })
      .finally(() => { loading.updateCompositeRoute = false })
  }) as AdminGroupsRepository['updateCompositeRoute']

  const deleteCompositeRoute: AdminGroupsRepository['deleteCompositeRoute'] = ((...args: unknown[]) => {
    loading.deleteCompositeRoute = true
    errors.deleteCompositeRoute = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.deleteCompositeRoute as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteCompositeRoute = error; throw error })
      .finally(() => { loading.deleteCompositeRoute = false })
  }) as AdminGroupsRepository['deleteCompositeRoute']

  const updateSortOrder: AdminGroupsRepository['updateSortOrder'] = ((...args: unknown[]) => {
    loading.updateSortOrder = true
    errors.updateSortOrder = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.updateSortOrder as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateSortOrder = error; throw error })
      .finally(() => { loading.updateSortOrder = false })
  }) as AdminGroupsRepository['updateSortOrder']

  const clearGroupRateMultipliers: AdminGroupsRepository['clearGroupRateMultipliers'] = ((...args: unknown[]) => {
    loading.clearGroupRateMultipliers = true
    errors.clearGroupRateMultipliers = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.clearGroupRateMultipliers as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.clearGroupRateMultipliers = error; throw error })
      .finally(() => { loading.clearGroupRateMultipliers = false })
  }) as AdminGroupsRepository['clearGroupRateMultipliers']

  const batchSetGroupRateMultipliers: AdminGroupsRepository['batchSetGroupRateMultipliers'] = ((...args: unknown[]) => {
    loading.batchSetGroupRateMultipliers = true
    errors.batchSetGroupRateMultipliers = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.batchSetGroupRateMultipliers as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchSetGroupRateMultipliers = error; throw error })
      .finally(() => { loading.batchSetGroupRateMultipliers = false })
  }) as AdminGroupsRepository['batchSetGroupRateMultipliers']

  const batchSetGroupRPMOverrides: AdminGroupsRepository['batchSetGroupRPMOverrides'] = ((...args: unknown[]) => {
    loading.batchSetGroupRPMOverrides = true
    errors.batchSetGroupRPMOverrides = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.batchSetGroupRPMOverrides as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchSetGroupRPMOverrides = error; throw error })
      .finally(() => { loading.batchSetGroupRPMOverrides = false })
  }) as AdminGroupsRepository['batchSetGroupRPMOverrides']

  const clearGroupRPMOverrides: AdminGroupsRepository['clearGroupRPMOverrides'] = ((...args: unknown[]) => {
    loading.clearGroupRPMOverrides = true
    errors.clearGroupRPMOverrides = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.clearGroupRPMOverrides as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.clearGroupRPMOverrides = error; throw error })
      .finally(() => { loading.clearGroupRPMOverrides = false })
  }) as AdminGroupsRepository['clearGroupRPMOverrides']

    return { loading, errors, create, duplicate, update, deleteGroup, toggleStatus, createCompositeRoute, updateCompositeRoute, deleteCompositeRoute, updateSortOrder, clearGroupRateMultipliers, batchSetGroupRateMultipliers, batchSetGroupRPMOverrides, clearGroupRPMOverrides }
  })
}

export const useAdminGroupsActionStore = createAdminGroupsActionStore()
