/**
 * AdminGroupsQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminGroupsQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminGroupsRepository } from '@/features/admin-groups/domain/repositories/adminGroupsRepository'
import { adminGroupsRepository as default_adminGroups_repo } from '@/features/admin-groups/data/repositories/adminGroupsRepositoryImpl'

export function createAdminGroupsQueryStore(adminGroupsRepo: AdminGroupsRepository = default_adminGroups_repo) {
  return defineStore('adminGroups/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, getAll: false, getAllIncludingInactive: false, getByPlatform: false, getById: false, getModelsListCandidates: false, getStats: false, getGroupApiKeys: false, listCompositeRoutes: false, previewCompositeRoute: false, getGroupRateMultipliers: false, getGroupRPMOverrides: false, getUsageSummary: false, getCapacitySummary: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, getAll: null as unknown, getAllIncludingInactive: null as unknown, getByPlatform: null as unknown, getById: null as unknown, getModelsListCandidates: null as unknown, getStats: null as unknown, getGroupApiKeys: null as unknown, listCompositeRoutes: null as unknown, previewCompositeRoute: null as unknown, getGroupRateMultipliers: null as unknown, getGroupRPMOverrides: null as unknown, getUsageSummary: null as unknown, getCapacitySummary: null as unknown })

  const list: AdminGroupsRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as AdminGroupsRepository['list']

  const getAll: AdminGroupsRepository['getAll'] = ((...args: unknown[]) => {
    loading.getAll = true
    errors.getAll = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getAll as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAll = error; throw error })
      .finally(() => { loading.getAll = false })
  }) as AdminGroupsRepository['getAll']

  const getAllIncludingInactive: AdminGroupsRepository['getAllIncludingInactive'] = ((...args: unknown[]) => {
    loading.getAllIncludingInactive = true
    errors.getAllIncludingInactive = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getAllIncludingInactive as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAllIncludingInactive = error; throw error })
      .finally(() => { loading.getAllIncludingInactive = false })
  }) as AdminGroupsRepository['getAllIncludingInactive']

  const getByPlatform: AdminGroupsRepository['getByPlatform'] = ((...args: unknown[]) => {
    loading.getByPlatform = true
    errors.getByPlatform = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getByPlatform as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getByPlatform = error; throw error })
      .finally(() => { loading.getByPlatform = false })
  }) as AdminGroupsRepository['getByPlatform']

  const getById: AdminGroupsRepository['getById'] = ((...args: unknown[]) => {
    loading.getById = true
    errors.getById = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getById as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getById = error; throw error })
      .finally(() => { loading.getById = false })
  }) as AdminGroupsRepository['getById']

  const getModelsListCandidates: AdminGroupsRepository['getModelsListCandidates'] = ((...args: unknown[]) => {
    loading.getModelsListCandidates = true
    errors.getModelsListCandidates = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getModelsListCandidates as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getModelsListCandidates = error; throw error })
      .finally(() => { loading.getModelsListCandidates = false })
  }) as AdminGroupsRepository['getModelsListCandidates']

  const getStats: AdminGroupsRepository['getStats'] = ((...args: unknown[]) => {
    loading.getStats = true
    errors.getStats = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getStats = error; throw error })
      .finally(() => { loading.getStats = false })
  }) as AdminGroupsRepository['getStats']

  const getGroupApiKeys: AdminGroupsRepository['getGroupApiKeys'] = ((...args: unknown[]) => {
    loading.getGroupApiKeys = true
    errors.getGroupApiKeys = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getGroupApiKeys as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getGroupApiKeys = error; throw error })
      .finally(() => { loading.getGroupApiKeys = false })
  }) as AdminGroupsRepository['getGroupApiKeys']

  const listCompositeRoutes: AdminGroupsRepository['listCompositeRoutes'] = ((...args: unknown[]) => {
    loading.listCompositeRoutes = true
    errors.listCompositeRoutes = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.listCompositeRoutes as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listCompositeRoutes = error; throw error })
      .finally(() => { loading.listCompositeRoutes = false })
  }) as AdminGroupsRepository['listCompositeRoutes']

  const previewCompositeRoute: AdminGroupsRepository['previewCompositeRoute'] = ((...args: unknown[]) => {
    loading.previewCompositeRoute = true
    errors.previewCompositeRoute = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.previewCompositeRoute as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.previewCompositeRoute = error; throw error })
      .finally(() => { loading.previewCompositeRoute = false })
  }) as AdminGroupsRepository['previewCompositeRoute']

  const getGroupRateMultipliers: AdminGroupsRepository['getGroupRateMultipliers'] = ((...args: unknown[]) => {
    loading.getGroupRateMultipliers = true
    errors.getGroupRateMultipliers = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getGroupRateMultipliers as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getGroupRateMultipliers = error; throw error })
      .finally(() => { loading.getGroupRateMultipliers = false })
  }) as AdminGroupsRepository['getGroupRateMultipliers']

  const getGroupRPMOverrides: AdminGroupsRepository['getGroupRPMOverrides'] = ((...args: unknown[]) => {
    loading.getGroupRPMOverrides = true
    errors.getGroupRPMOverrides = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getGroupRPMOverrides as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getGroupRPMOverrides = error; throw error })
      .finally(() => { loading.getGroupRPMOverrides = false })
  }) as AdminGroupsRepository['getGroupRPMOverrides']

  const getUsageSummary: AdminGroupsRepository['getUsageSummary'] = ((...args: unknown[]) => {
    loading.getUsageSummary = true
    errors.getUsageSummary = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getUsageSummary as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUsageSummary = error; throw error })
      .finally(() => { loading.getUsageSummary = false })
  }) as AdminGroupsRepository['getUsageSummary']

  const getCapacitySummary: AdminGroupsRepository['getCapacitySummary'] = ((...args: unknown[]) => {
    loading.getCapacitySummary = true
    errors.getCapacitySummary = null
    return Promise.resolve()
      .then(() => (adminGroupsRepo.getCapacitySummary as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getCapacitySummary = error; throw error })
      .finally(() => { loading.getCapacitySummary = false })
  }) as AdminGroupsRepository['getCapacitySummary']

    return { loading, errors, list, getAll, getAllIncludingInactive, getByPlatform, getById, getModelsListCandidates, getStats, getGroupApiKeys, listCompositeRoutes, previewCompositeRoute, getGroupRateMultipliers, getGroupRPMOverrides, getUsageSummary, getCapacitySummary }
  })
}

export const useAdminGroupsQueryStore = createAdminGroupsQueryStore()
