/**
 * AdminPromoQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminPromoQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminPromoRepository } from '@/features/admin-promo/domain/repositories/adminPromoRepository'
import { adminPromoRepository as default_adminPromo_repo } from '@/features/admin-promo/data/repositories/adminPromoRepositoryImpl'

export function createAdminPromoQueryStore(adminPromoRepo: AdminPromoRepository = default_adminPromo_repo) {
  return defineStore('adminPromo/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, getById: false, getUsages: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, getById: null as unknown, getUsages: null as unknown })

  const list: AdminPromoRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (adminPromoRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as AdminPromoRepository['list']

  const getById: AdminPromoRepository['getById'] = ((...args: unknown[]) => {
    loading.getById = true
    errors.getById = null
    return Promise.resolve()
      .then(() => (adminPromoRepo.getById as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getById = error; throw error })
      .finally(() => { loading.getById = false })
  }) as AdminPromoRepository['getById']

  const getUsages: AdminPromoRepository['getUsages'] = ((...args: unknown[]) => {
    loading.getUsages = true
    errors.getUsages = null
    return Promise.resolve()
      .then(() => (adminPromoRepo.getUsages as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUsages = error; throw error })
      .finally(() => { loading.getUsages = false })
  }) as AdminPromoRepository['getUsages']

    return { loading, errors, list, getById, getUsages }
  })
}

export const useAdminPromoQueryStore = createAdminPromoQueryStore()
