/**
 * AdminPromoActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminPromoActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminPromoRepository } from '@/features/admin-promo/domain/repositories/adminPromoRepository'
import { adminPromoRepository as default_adminPromo_repo } from '@/features/admin-promo/data/repositories/adminPromoRepositoryImpl'

export function createAdminPromoActionStore(adminPromoRepo: AdminPromoRepository = default_adminPromo_repo) {
  return defineStore('adminPromo/action', () => {
    const loading = reactive<Record<string, boolean>>({ create: false, update: false, deleteCode: false })
    const errors = reactive<Record<string, unknown>>({ create: null as unknown, update: null as unknown, deleteCode: null as unknown })

  const create: AdminPromoRepository['create'] = ((...args: unknown[]) => {
    loading.create = true
    errors.create = null
    return Promise.resolve()
      .then(() => (adminPromoRepo.create as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.create = error; throw error })
      .finally(() => { loading.create = false })
  }) as AdminPromoRepository['create']

  const update: AdminPromoRepository['update'] = ((...args: unknown[]) => {
    loading.update = true
    errors.update = null
    return Promise.resolve()
      .then(() => (adminPromoRepo.update as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.update = error; throw error })
      .finally(() => { loading.update = false })
  }) as AdminPromoRepository['update']

  const deleteCode: AdminPromoRepository['deleteCode'] = ((...args: unknown[]) => {
    loading.deleteCode = true
    errors.deleteCode = null
    return Promise.resolve()
      .then(() => (adminPromoRepo.deleteCode as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteCode = error; throw error })
      .finally(() => { loading.deleteCode = false })
  }) as AdminPromoRepository['deleteCode']

    return { loading, errors, create, update, deleteCode }
  })
}

export const useAdminPromoActionStore = createAdminPromoActionStore()
