/**
 * AdminRiskControlQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminRiskControlQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminRiskControlRepository } from '@/features/admin-risk-control/domain/repositories/adminRiskControlRepository'
import { adminRiskControlRepository as default_adminRiskControl_repo } from '@/features/admin-risk-control/data/repositories/adminRiskControlRepositoryImpl'

export function createAdminRiskControlQueryStore(adminRiskControlRepo: AdminRiskControlRepository = default_adminRiskControl_repo) {
  return defineStore('adminRiskControl/query', () => {
    const loading = reactive<Record<string, boolean>>({ getConfig: false, getStatus: false, listLogs: false })
    const errors = reactive<Record<string, unknown>>({ getConfig: null as unknown, getStatus: null as unknown, listLogs: null as unknown })

  const getConfig: AdminRiskControlRepository['getConfig'] = ((...args: unknown[]) => {
    loading.getConfig = true
    errors.getConfig = null
    return Promise.resolve()
      .then(() => (adminRiskControlRepo.getConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getConfig = error; throw error })
      .finally(() => { loading.getConfig = false })
  }) as AdminRiskControlRepository['getConfig']

  const getStatus: AdminRiskControlRepository['getStatus'] = ((...args: unknown[]) => {
    loading.getStatus = true
    errors.getStatus = null
    return Promise.resolve()
      .then(() => (adminRiskControlRepo.getStatus as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getStatus = error; throw error })
      .finally(() => { loading.getStatus = false })
  }) as AdminRiskControlRepository['getStatus']

  const listLogs: AdminRiskControlRepository['listLogs'] = ((...args: unknown[]) => {
    loading.listLogs = true
    errors.listLogs = null
    return Promise.resolve()
      .then(() => (adminRiskControlRepo.listLogs as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listLogs = error; throw error })
      .finally(() => { loading.listLogs = false })
  }) as AdminRiskControlRepository['listLogs']

    return { loading, errors, getConfig, getStatus, listLogs }
  })
}

export const useAdminRiskControlQueryStore = createAdminRiskControlQueryStore()
