/**
 * AdminRiskControlActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminRiskControlActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminRiskControlRepository } from '@/features/admin-risk-control/domain/repositories/adminRiskControlRepository'
import { adminRiskControlRepository as default_adminRiskControl_repo } from '@/features/admin-risk-control/data/repositories/adminRiskControlRepositoryImpl'

export function createAdminRiskControlActionStore(adminRiskControlRepo: AdminRiskControlRepository = default_adminRiskControl_repo) {
  return defineStore('adminRiskControl/action', () => {
    const loading = reactive<Record<string, boolean>>({ updateConfig: false, testAPIKeys: false, unbanUser: false, deleteFlaggedHash: false, clearFlaggedHashes: false })
    const errors = reactive<Record<string, unknown>>({ updateConfig: null as unknown, testAPIKeys: null as unknown, unbanUser: null as unknown, deleteFlaggedHash: null as unknown, clearFlaggedHashes: null as unknown })

  const updateConfig: AdminRiskControlRepository['updateConfig'] = ((...args: unknown[]) => {
    loading.updateConfig = true
    errors.updateConfig = null
    return Promise.resolve()
      .then(() => (adminRiskControlRepo.updateConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateConfig = error; throw error })
      .finally(() => { loading.updateConfig = false })
  }) as AdminRiskControlRepository['updateConfig']

  const testAPIKeys: AdminRiskControlRepository['testAPIKeys'] = ((...args: unknown[]) => {
    loading.testAPIKeys = true
    errors.testAPIKeys = null
    return Promise.resolve()
      .then(() => (adminRiskControlRepo.testAPIKeys as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.testAPIKeys = error; throw error })
      .finally(() => { loading.testAPIKeys = false })
  }) as AdminRiskControlRepository['testAPIKeys']

  const unbanUser: AdminRiskControlRepository['unbanUser'] = ((...args: unknown[]) => {
    loading.unbanUser = true
    errors.unbanUser = null
    return Promise.resolve()
      .then(() => (adminRiskControlRepo.unbanUser as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.unbanUser = error; throw error })
      .finally(() => { loading.unbanUser = false })
  }) as AdminRiskControlRepository['unbanUser']

  const deleteFlaggedHash: AdminRiskControlRepository['deleteFlaggedHash'] = ((...args: unknown[]) => {
    loading.deleteFlaggedHash = true
    errors.deleteFlaggedHash = null
    return Promise.resolve()
      .then(() => (adminRiskControlRepo.deleteFlaggedHash as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteFlaggedHash = error; throw error })
      .finally(() => { loading.deleteFlaggedHash = false })
  }) as AdminRiskControlRepository['deleteFlaggedHash']

  const clearFlaggedHashes: AdminRiskControlRepository['clearFlaggedHashes'] = ((...args: unknown[]) => {
    loading.clearFlaggedHashes = true
    errors.clearFlaggedHashes = null
    return Promise.resolve()
      .then(() => (adminRiskControlRepo.clearFlaggedHashes as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.clearFlaggedHashes = error; throw error })
      .finally(() => { loading.clearFlaggedHashes = false })
  }) as AdminRiskControlRepository['clearFlaggedHashes']

    return { loading, errors, updateConfig, testAPIKeys, unbanUser, deleteFlaggedHash, clearFlaggedHashes }
  })
}

export const useAdminRiskControlActionStore = createAdminRiskControlActionStore()
