/**
 * AdminProxiesActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminProxiesActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminProxiesRepository } from '@/features/admin-proxies/domain/repositories/adminProxiesRepository'
import { adminProxiesRepository as default_adminProxies_repo } from '@/features/admin-proxies/data/repositories/adminProxiesRepositoryImpl'

export function createAdminProxiesActionStore(adminProxiesRepo: AdminProxiesRepository = default_adminProxies_repo) {
  return defineStore('adminProxies/action', () => {
    const loading = reactive<Record<string, boolean>>({ create: false, update: false, deleteProxy: false, toggleStatus: false, testProxy: false, batchCreate: false, batchDelete: false, importData: false })
    const errors = reactive<Record<string, unknown>>({ create: null as unknown, update: null as unknown, deleteProxy: null as unknown, toggleStatus: null as unknown, testProxy: null as unknown, batchCreate: null as unknown, batchDelete: null as unknown, importData: null as unknown })

  const create: AdminProxiesRepository['create'] = ((...args: unknown[]) => {
    loading.create = true
    errors.create = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.create as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.create = error; throw error })
      .finally(() => { loading.create = false })
  }) as AdminProxiesRepository['create']

  const update: AdminProxiesRepository['update'] = ((...args: unknown[]) => {
    loading.update = true
    errors.update = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.update as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.update = error; throw error })
      .finally(() => { loading.update = false })
  }) as AdminProxiesRepository['update']

  const deleteProxy: AdminProxiesRepository['deleteProxy'] = ((...args: unknown[]) => {
    loading.deleteProxy = true
    errors.deleteProxy = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.deleteProxy as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteProxy = error; throw error })
      .finally(() => { loading.deleteProxy = false })
  }) as AdminProxiesRepository['deleteProxy']

  const toggleStatus: AdminProxiesRepository['toggleStatus'] = ((...args: unknown[]) => {
    loading.toggleStatus = true
    errors.toggleStatus = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.toggleStatus as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.toggleStatus = error; throw error })
      .finally(() => { loading.toggleStatus = false })
  }) as AdminProxiesRepository['toggleStatus']

  const testProxy: AdminProxiesRepository['testProxy'] = ((...args: unknown[]) => {
    loading.testProxy = true
    errors.testProxy = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.testProxy as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.testProxy = error; throw error })
      .finally(() => { loading.testProxy = false })
  }) as AdminProxiesRepository['testProxy']

  const batchCreate: AdminProxiesRepository['batchCreate'] = ((...args: unknown[]) => {
    loading.batchCreate = true
    errors.batchCreate = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.batchCreate as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchCreate = error; throw error })
      .finally(() => { loading.batchCreate = false })
  }) as AdminProxiesRepository['batchCreate']

  const batchDelete: AdminProxiesRepository['batchDelete'] = ((...args: unknown[]) => {
    loading.batchDelete = true
    errors.batchDelete = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.batchDelete as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.batchDelete = error; throw error })
      .finally(() => { loading.batchDelete = false })
  }) as AdminProxiesRepository['batchDelete']

  const importData: AdminProxiesRepository['importData'] = ((...args: unknown[]) => {
    loading.importData = true
    errors.importData = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.importData as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.importData = error; throw error })
      .finally(() => { loading.importData = false })
  }) as AdminProxiesRepository['importData']

    return { loading, errors, create, update, deleteProxy, toggleStatus, testProxy, batchCreate, batchDelete, importData }
  })
}

export const useAdminProxiesActionStore = createAdminProxiesActionStore()
