/**
 * AdminProxiesQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminProxiesQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminProxiesRepository } from '@/features/admin-proxies/domain/repositories/adminProxiesRepository'
import { adminProxiesRepository as default_adminProxies_repo } from '@/features/admin-proxies/data/repositories/adminProxiesRepositoryImpl'

export function createAdminProxiesQueryStore(adminProxiesRepo: AdminProxiesRepository = default_adminProxies_repo) {
  return defineStore('adminProxies/query', () => {
    const loading = reactive<Record<string, boolean>>({ list: false, getAll: false, getAllWithCount: false, getById: false, checkProxyQuality: false, getStats: false, getProxyAccounts: false, exportData: false })
    const errors = reactive<Record<string, unknown>>({ list: null as unknown, getAll: null as unknown, getAllWithCount: null as unknown, getById: null as unknown, checkProxyQuality: null as unknown, getStats: null as unknown, getProxyAccounts: null as unknown, exportData: null as unknown })

  const list: AdminProxiesRepository['list'] = ((...args: unknown[]) => {
    loading.list = true
    errors.list = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.list as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.list = error; throw error })
      .finally(() => { loading.list = false })
  }) as AdminProxiesRepository['list']

  const getAll: AdminProxiesRepository['getAll'] = ((...args: unknown[]) => {
    loading.getAll = true
    errors.getAll = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.getAll as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAll = error; throw error })
      .finally(() => { loading.getAll = false })
  }) as AdminProxiesRepository['getAll']

  const getAllWithCount: AdminProxiesRepository['getAllWithCount'] = ((...args: unknown[]) => {
    loading.getAllWithCount = true
    errors.getAllWithCount = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.getAllWithCount as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAllWithCount = error; throw error })
      .finally(() => { loading.getAllWithCount = false })
  }) as AdminProxiesRepository['getAllWithCount']

  const getById: AdminProxiesRepository['getById'] = ((...args: unknown[]) => {
    loading.getById = true
    errors.getById = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.getById as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getById = error; throw error })
      .finally(() => { loading.getById = false })
  }) as AdminProxiesRepository['getById']

  const checkProxyQuality: AdminProxiesRepository['checkProxyQuality'] = ((...args: unknown[]) => {
    loading.checkProxyQuality = true
    errors.checkProxyQuality = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.checkProxyQuality as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.checkProxyQuality = error; throw error })
      .finally(() => { loading.checkProxyQuality = false })
  }) as AdminProxiesRepository['checkProxyQuality']

  const getStats: AdminProxiesRepository['getStats'] = ((...args: unknown[]) => {
    loading.getStats = true
    errors.getStats = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.getStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getStats = error; throw error })
      .finally(() => { loading.getStats = false })
  }) as AdminProxiesRepository['getStats']

  const getProxyAccounts: AdminProxiesRepository['getProxyAccounts'] = ((...args: unknown[]) => {
    loading.getProxyAccounts = true
    errors.getProxyAccounts = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.getProxyAccounts as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getProxyAccounts = error; throw error })
      .finally(() => { loading.getProxyAccounts = false })
  }) as AdminProxiesRepository['getProxyAccounts']

  const exportData: AdminProxiesRepository['exportData'] = ((...args: unknown[]) => {
    loading.exportData = true
    errors.exportData = null
    return Promise.resolve()
      .then(() => (adminProxiesRepo.exportData as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.exportData = error; throw error })
      .finally(() => { loading.exportData = false })
  }) as AdminProxiesRepository['exportData']

    return { loading, errors, list, getAll, getAllWithCount, getById, checkProxyQuality, getStats, getProxyAccounts, exportData }
  })
}

export const useAdminProxiesQueryStore = createAdminProxiesQueryStore()
