/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminProxies — thin orchestrator composable for AdminProxies.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminProxiesQueryStore } from '@/features/admin-proxies/presentation/stores/adminProxiesQueryStore'
import { useAdminProxiesActionStore } from '@/features/admin-proxies/presentation/stores/adminProxiesActionStore'

export function useAdminProxies() {
  const q_adminProxiesQueryStore = useAdminProxiesQueryStore()
  const a_adminProxiesActionStore = useAdminProxiesActionStore()
  return {
    ...q_adminProxiesQueryStore,
    ...a_adminProxiesActionStore,
  }
}
