/* Auto-generated by .tmp_gen_composables.mjs */
/**
 * useAdminPromo — thin orchestrator composable for AdminPromo.
 * Re-exports all Query + Action store state and methods as a flat interface.
 * Per spec §5.5 R6: composable coordinates stores + lifecycle.
 * See usePromptAudit.ts for the hand-crafted reference implementation with
 * full i18n error mapping and UI-local state — this composable is the
 * minimal scaffold for features that do not yet have hand-crafted logic.
 */

import { useAdminPromoQueryStore } from '@/features/admin-promo/presentation/stores/adminPromoQueryStore'
import { useAdminPromoActionStore } from '@/features/admin-promo/presentation/stores/adminPromoActionStore'

export function useAdminPromo() {
  const q_adminPromoQueryStore = useAdminPromoQueryStore()
  const a_adminPromoActionStore = useAdminPromoActionStore()
  return {
    ...q_adminPromoQueryStore,
    ...a_adminPromoActionStore,
  }
}
