import type { RouteRecordRaw } from 'vue-router'
/* Auto-generated by feature barrel script. Per spec §6 R8. */
/* MUST only export: Page components + necessary domain types.           */
/* MUST NOT export: store / composable / repository / datasource / widget */

export const subscriptionsRoutes: RouteRecordRaw[] = [
  {
    path: '/subscriptions',
    name: 'Subscriptions',
    component: () => import('@/features/subscriptions/presentation/pages/SubscriptionsPage.vue'),
    meta: { requiresAuth: true, requiresAdmin: false, title: 'My Subscriptions', titleKey: 'userSubscriptions.title', descriptionKey: 'userSubscriptions.description', simpleModeRestricted: true },
  },
]
