/**
 * AdminOpsQueryStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Query-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminOpsQueryStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminOpsRepository } from '@/features/admin-ops/domain/repositories/adminOpsRepository'
import { adminOpsRepository as default_adminOps_repo } from '@/features/admin-ops/data/repositories/adminOpsRepositoryImpl'

export function createAdminOpsQueryStore(adminOpsRepo: AdminOpsRepository = default_adminOps_repo) {
  return defineStore('adminOps/query', () => {
    const loading = reactive<Record<string, boolean>>({ getConcurrencyStats: false, getUserConcurrencyStats: false, getAccountAvailabilityStats: false, getRealtimeTrafficSummary: false, getDashboardOverview: false, getDashboardSnapshotV2: false, getThroughputTrend: false, getLatencyHistogram: false, getErrorTrend: false, getErrorDistribution: false, getImageGenerationStats: false, getOpenAITokenStats: false, getUserUsageStats: false, listErrorLogs: false, getErrorLogDetail: false, listRequestErrors: false, listUpstreamErrors: false, getRequestErrorDetail: false, getUpstreamErrorDetail: false, listRequestErrorUpstreamErrors: false, listRequestDetails: false, listAlertRules: false, listAlertEvents: false, getAlertEvent: false, getEmailNotificationConfig: false, getSettingsSnapshot: false, getAlertRuntimeSettings: false, getRuntimeLogConfig: false, listSystemLogs: false, getSystemLogSinkHealth: false, getAdvancedSettings: false })
    const errors = reactive<Record<string, unknown>>({ getConcurrencyStats: null as unknown, getUserConcurrencyStats: null as unknown, getAccountAvailabilityStats: null as unknown, getRealtimeTrafficSummary: null as unknown, getDashboardOverview: null as unknown, getDashboardSnapshotV2: null as unknown, getThroughputTrend: null as unknown, getLatencyHistogram: null as unknown, getErrorTrend: null as unknown, getErrorDistribution: null as unknown, getImageGenerationStats: null as unknown, getOpenAITokenStats: null as unknown, getUserUsageStats: null as unknown, listErrorLogs: null as unknown, getErrorLogDetail: null as unknown, listRequestErrors: null as unknown, listUpstreamErrors: null as unknown, getRequestErrorDetail: null as unknown, getUpstreamErrorDetail: null as unknown, listRequestErrorUpstreamErrors: null as unknown, listRequestDetails: null as unknown, listAlertRules: null as unknown, listAlertEvents: null as unknown, getAlertEvent: null as unknown, getEmailNotificationConfig: null as unknown, getSettingsSnapshot: null as unknown, getAlertRuntimeSettings: null as unknown, getRuntimeLogConfig: null as unknown, listSystemLogs: null as unknown, getSystemLogSinkHealth: null as unknown, getAdvancedSettings: null as unknown })

  const getConcurrencyStats: AdminOpsRepository['getConcurrencyStats'] = ((...args: unknown[]) => {
    loading.getConcurrencyStats = true
    errors.getConcurrencyStats = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getConcurrencyStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getConcurrencyStats = error; throw error })
      .finally(() => { loading.getConcurrencyStats = false })
  }) as AdminOpsRepository['getConcurrencyStats']

  const getUserConcurrencyStats: AdminOpsRepository['getUserConcurrencyStats'] = ((...args: unknown[]) => {
    loading.getUserConcurrencyStats = true
    errors.getUserConcurrencyStats = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getUserConcurrencyStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserConcurrencyStats = error; throw error })
      .finally(() => { loading.getUserConcurrencyStats = false })
  }) as AdminOpsRepository['getUserConcurrencyStats']

  const getAccountAvailabilityStats: AdminOpsRepository['getAccountAvailabilityStats'] = ((...args: unknown[]) => {
    loading.getAccountAvailabilityStats = true
    errors.getAccountAvailabilityStats = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getAccountAvailabilityStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAccountAvailabilityStats = error; throw error })
      .finally(() => { loading.getAccountAvailabilityStats = false })
  }) as AdminOpsRepository['getAccountAvailabilityStats']

  const getRealtimeTrafficSummary: AdminOpsRepository['getRealtimeTrafficSummary'] = ((...args: unknown[]) => {
    loading.getRealtimeTrafficSummary = true
    errors.getRealtimeTrafficSummary = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getRealtimeTrafficSummary as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getRealtimeTrafficSummary = error; throw error })
      .finally(() => { loading.getRealtimeTrafficSummary = false })
  }) as AdminOpsRepository['getRealtimeTrafficSummary']

  const getDashboardOverview: AdminOpsRepository['getDashboardOverview'] = ((...args: unknown[]) => {
    loading.getDashboardOverview = true
    errors.getDashboardOverview = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getDashboardOverview as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getDashboardOverview = error; throw error })
      .finally(() => { loading.getDashboardOverview = false })
  }) as AdminOpsRepository['getDashboardOverview']

  const getDashboardSnapshotV2: AdminOpsRepository['getDashboardSnapshotV2'] = ((...args: unknown[]) => {
    loading.getDashboardSnapshotV2 = true
    errors.getDashboardSnapshotV2 = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getDashboardSnapshotV2 as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getDashboardSnapshotV2 = error; throw error })
      .finally(() => { loading.getDashboardSnapshotV2 = false })
  }) as AdminOpsRepository['getDashboardSnapshotV2']

  const getThroughputTrend: AdminOpsRepository['getThroughputTrend'] = ((...args: unknown[]) => {
    loading.getThroughputTrend = true
    errors.getThroughputTrend = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getThroughputTrend as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getThroughputTrend = error; throw error })
      .finally(() => { loading.getThroughputTrend = false })
  }) as AdminOpsRepository['getThroughputTrend']

  const getLatencyHistogram: AdminOpsRepository['getLatencyHistogram'] = ((...args: unknown[]) => {
    loading.getLatencyHistogram = true
    errors.getLatencyHistogram = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getLatencyHistogram as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getLatencyHistogram = error; throw error })
      .finally(() => { loading.getLatencyHistogram = false })
  }) as AdminOpsRepository['getLatencyHistogram']

  const getErrorTrend: AdminOpsRepository['getErrorTrend'] = ((...args: unknown[]) => {
    loading.getErrorTrend = true
    errors.getErrorTrend = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getErrorTrend as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getErrorTrend = error; throw error })
      .finally(() => { loading.getErrorTrend = false })
  }) as AdminOpsRepository['getErrorTrend']

  const getErrorDistribution: AdminOpsRepository['getErrorDistribution'] = ((...args: unknown[]) => {
    loading.getErrorDistribution = true
    errors.getErrorDistribution = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getErrorDistribution as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getErrorDistribution = error; throw error })
      .finally(() => { loading.getErrorDistribution = false })
  }) as AdminOpsRepository['getErrorDistribution']

  const getImageGenerationStats: AdminOpsRepository['getImageGenerationStats'] = ((...args: unknown[]) => {
    loading.getImageGenerationStats = true
    errors.getImageGenerationStats = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getImageGenerationStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getImageGenerationStats = error; throw error })
      .finally(() => { loading.getImageGenerationStats = false })
  }) as AdminOpsRepository['getImageGenerationStats']

  const getOpenAITokenStats: AdminOpsRepository['getOpenAITokenStats'] = ((...args: unknown[]) => {
    loading.getOpenAITokenStats = true
    errors.getOpenAITokenStats = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getOpenAITokenStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getOpenAITokenStats = error; throw error })
      .finally(() => { loading.getOpenAITokenStats = false })
  }) as AdminOpsRepository['getOpenAITokenStats']

  const getUserUsageStats: AdminOpsRepository['getUserUsageStats'] = ((...args: unknown[]) => {
    loading.getUserUsageStats = true
    errors.getUserUsageStats = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getUserUsageStats as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUserUsageStats = error; throw error })
      .finally(() => { loading.getUserUsageStats = false })
  }) as AdminOpsRepository['getUserUsageStats']

  const listErrorLogs: AdminOpsRepository['listErrorLogs'] = ((...args: unknown[]) => {
    loading.listErrorLogs = true
    errors.listErrorLogs = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.listErrorLogs as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listErrorLogs = error; throw error })
      .finally(() => { loading.listErrorLogs = false })
  }) as AdminOpsRepository['listErrorLogs']

  const getErrorLogDetail: AdminOpsRepository['getErrorLogDetail'] = ((...args: unknown[]) => {
    loading.getErrorLogDetail = true
    errors.getErrorLogDetail = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getErrorLogDetail as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getErrorLogDetail = error; throw error })
      .finally(() => { loading.getErrorLogDetail = false })
  }) as AdminOpsRepository['getErrorLogDetail']

  const listRequestErrors: AdminOpsRepository['listRequestErrors'] = ((...args: unknown[]) => {
    loading.listRequestErrors = true
    errors.listRequestErrors = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.listRequestErrors as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listRequestErrors = error; throw error })
      .finally(() => { loading.listRequestErrors = false })
  }) as AdminOpsRepository['listRequestErrors']

  const listUpstreamErrors: AdminOpsRepository['listUpstreamErrors'] = ((...args: unknown[]) => {
    loading.listUpstreamErrors = true
    errors.listUpstreamErrors = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.listUpstreamErrors as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listUpstreamErrors = error; throw error })
      .finally(() => { loading.listUpstreamErrors = false })
  }) as AdminOpsRepository['listUpstreamErrors']

  const getRequestErrorDetail: AdminOpsRepository['getRequestErrorDetail'] = ((...args: unknown[]) => {
    loading.getRequestErrorDetail = true
    errors.getRequestErrorDetail = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getRequestErrorDetail as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getRequestErrorDetail = error; throw error })
      .finally(() => { loading.getRequestErrorDetail = false })
  }) as AdminOpsRepository['getRequestErrorDetail']

  const getUpstreamErrorDetail: AdminOpsRepository['getUpstreamErrorDetail'] = ((...args: unknown[]) => {
    loading.getUpstreamErrorDetail = true
    errors.getUpstreamErrorDetail = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getUpstreamErrorDetail as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getUpstreamErrorDetail = error; throw error })
      .finally(() => { loading.getUpstreamErrorDetail = false })
  }) as AdminOpsRepository['getUpstreamErrorDetail']

  const listRequestErrorUpstreamErrors: AdminOpsRepository['listRequestErrorUpstreamErrors'] = ((...args: unknown[]) => {
    loading.listRequestErrorUpstreamErrors = true
    errors.listRequestErrorUpstreamErrors = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.listRequestErrorUpstreamErrors as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listRequestErrorUpstreamErrors = error; throw error })
      .finally(() => { loading.listRequestErrorUpstreamErrors = false })
  }) as AdminOpsRepository['listRequestErrorUpstreamErrors']

  const listRequestDetails: AdminOpsRepository['listRequestDetails'] = ((...args: unknown[]) => {
    loading.listRequestDetails = true
    errors.listRequestDetails = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.listRequestDetails as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listRequestDetails = error; throw error })
      .finally(() => { loading.listRequestDetails = false })
  }) as AdminOpsRepository['listRequestDetails']

  const listAlertRules: AdminOpsRepository['listAlertRules'] = ((...args: unknown[]) => {
    loading.listAlertRules = true
    errors.listAlertRules = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.listAlertRules as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listAlertRules = error; throw error })
      .finally(() => { loading.listAlertRules = false })
  }) as AdminOpsRepository['listAlertRules']

  const listAlertEvents: AdminOpsRepository['listAlertEvents'] = ((...args: unknown[]) => {
    loading.listAlertEvents = true
    errors.listAlertEvents = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.listAlertEvents as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listAlertEvents = error; throw error })
      .finally(() => { loading.listAlertEvents = false })
  }) as AdminOpsRepository['listAlertEvents']

  const getAlertEvent: AdminOpsRepository['getAlertEvent'] = ((...args: unknown[]) => {
    loading.getAlertEvent = true
    errors.getAlertEvent = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getAlertEvent as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAlertEvent = error; throw error })
      .finally(() => { loading.getAlertEvent = false })
  }) as AdminOpsRepository['getAlertEvent']

  const getEmailNotificationConfig: AdminOpsRepository['getEmailNotificationConfig'] = ((...args: unknown[]) => {
    loading.getEmailNotificationConfig = true
    errors.getEmailNotificationConfig = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getEmailNotificationConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getEmailNotificationConfig = error; throw error })
      .finally(() => { loading.getEmailNotificationConfig = false })
  }) as AdminOpsRepository['getEmailNotificationConfig']

  const getSettingsSnapshot: AdminOpsRepository['getSettingsSnapshot'] = ((...args: unknown[]) => {
    loading.getSettingsSnapshot = true
    errors.getSettingsSnapshot = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getSettingsSnapshot as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getSettingsSnapshot = error; throw error })
      .finally(() => { loading.getSettingsSnapshot = false })
  }) as AdminOpsRepository['getSettingsSnapshot']

  const getAlertRuntimeSettings: AdminOpsRepository['getAlertRuntimeSettings'] = ((...args: unknown[]) => {
    loading.getAlertRuntimeSettings = true
    errors.getAlertRuntimeSettings = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getAlertRuntimeSettings as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAlertRuntimeSettings = error; throw error })
      .finally(() => { loading.getAlertRuntimeSettings = false })
  }) as AdminOpsRepository['getAlertRuntimeSettings']

  const getRuntimeLogConfig: AdminOpsRepository['getRuntimeLogConfig'] = ((...args: unknown[]) => {
    loading.getRuntimeLogConfig = true
    errors.getRuntimeLogConfig = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getRuntimeLogConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getRuntimeLogConfig = error; throw error })
      .finally(() => { loading.getRuntimeLogConfig = false })
  }) as AdminOpsRepository['getRuntimeLogConfig']

  const listSystemLogs: AdminOpsRepository['listSystemLogs'] = ((...args: unknown[]) => {
    loading.listSystemLogs = true
    errors.listSystemLogs = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.listSystemLogs as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.listSystemLogs = error; throw error })
      .finally(() => { loading.listSystemLogs = false })
  }) as AdminOpsRepository['listSystemLogs']

  const getSystemLogSinkHealth: AdminOpsRepository['getSystemLogSinkHealth'] = ((...args: unknown[]) => {
    loading.getSystemLogSinkHealth = true
    errors.getSystemLogSinkHealth = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getSystemLogSinkHealth as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getSystemLogSinkHealth = error; throw error })
      .finally(() => { loading.getSystemLogSinkHealth = false })
  }) as AdminOpsRepository['getSystemLogSinkHealth']

  const getAdvancedSettings: AdminOpsRepository['getAdvancedSettings'] = ((...args: unknown[]) => {
    loading.getAdvancedSettings = true
    errors.getAdvancedSettings = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.getAdvancedSettings as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.getAdvancedSettings = error; throw error })
      .finally(() => { loading.getAdvancedSettings = false })
  }) as AdminOpsRepository['getAdvancedSettings']

    return { loading, errors, getConcurrencyStats, getUserConcurrencyStats, getAccountAvailabilityStats, getRealtimeTrafficSummary, getDashboardOverview, getDashboardSnapshotV2, getThroughputTrend, getLatencyHistogram, getErrorTrend, getErrorDistribution, getImageGenerationStats, getOpenAITokenStats, getUserUsageStats, listErrorLogs, getErrorLogDetail, listRequestErrors, listUpstreamErrors, getRequestErrorDetail, getUpstreamErrorDetail, listRequestErrorUpstreamErrors, listRequestDetails, listAlertRules, listAlertEvents, getAlertEvent, getEmailNotificationConfig, getSettingsSnapshot, getAlertRuntimeSettings, getRuntimeLogConfig, listSystemLogs, getSystemLogSinkHealth, getAdvancedSettings }
  })
}

export const useAdminOpsQueryStore = createAdminOpsQueryStore()
