/**
 * AdminOpsActionStore — auto-generated by .tmp_gen_stores.mjs.
 *
 * Thin store wrapping the Action-side Repository singletons for this feature.
 * Every action delegates to `repo.<method>(...)` inside a try/finally that
 * toggles per-method loading/error state. Follows the §5.4 R5.1 double-export
 * pattern so tests can inject a mock repo via `createAdminOpsActionStore(mock)`.
 *
 * When a feature needs custom orchestration (multi-repo transactions,
 * derived state, cache invalidation) — replace this generated file with a
 * hand-written store; the generator will skip files it did not create.
 */

import { defineStore } from 'pinia'
import { reactive } from 'vue'
import type { AdminOpsRepository } from '@/features/admin-ops/domain/repositories/adminOpsRepository'
import { adminOpsRepository as default_adminOps_repo } from '@/features/admin-ops/data/repositories/adminOpsRepositoryImpl'

export function createAdminOpsActionStore(adminOpsRepo: AdminOpsRepository = default_adminOps_repo) {
  return defineStore('adminOps/action', () => {
    const loading = reactive<Record<string, boolean>>({ updateErrorResolved: false, updateRequestErrorResolved: false, updateUpstreamErrorResolved: false, createAlertRule: false, updateAlertRule: false, deleteAlertRule: false, updateAlertEventStatus: false, createAlertSilence: false, updateEmailNotificationConfig: false, updateAlertRuntimeSettings: false, updateRuntimeLogConfig: false, resetRuntimeLogConfig: false, cleanupSystemLogs: false, updateAdvancedSettings: false })
    const errors = reactive<Record<string, unknown>>({ updateErrorResolved: null as unknown, updateRequestErrorResolved: null as unknown, updateUpstreamErrorResolved: null as unknown, createAlertRule: null as unknown, updateAlertRule: null as unknown, deleteAlertRule: null as unknown, updateAlertEventStatus: null as unknown, createAlertSilence: null as unknown, updateEmailNotificationConfig: null as unknown, updateAlertRuntimeSettings: null as unknown, updateRuntimeLogConfig: null as unknown, resetRuntimeLogConfig: null as unknown, cleanupSystemLogs: null as unknown, updateAdvancedSettings: null as unknown })

  const updateErrorResolved: AdminOpsRepository['updateErrorResolved'] = ((...args: unknown[]) => {
    loading.updateErrorResolved = true
    errors.updateErrorResolved = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.updateErrorResolved as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateErrorResolved = error; throw error })
      .finally(() => { loading.updateErrorResolved = false })
  }) as AdminOpsRepository['updateErrorResolved']

  const updateRequestErrorResolved: AdminOpsRepository['updateRequestErrorResolved'] = ((...args: unknown[]) => {
    loading.updateRequestErrorResolved = true
    errors.updateRequestErrorResolved = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.updateRequestErrorResolved as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateRequestErrorResolved = error; throw error })
      .finally(() => { loading.updateRequestErrorResolved = false })
  }) as AdminOpsRepository['updateRequestErrorResolved']

  const updateUpstreamErrorResolved: AdminOpsRepository['updateUpstreamErrorResolved'] = ((...args: unknown[]) => {
    loading.updateUpstreamErrorResolved = true
    errors.updateUpstreamErrorResolved = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.updateUpstreamErrorResolved as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateUpstreamErrorResolved = error; throw error })
      .finally(() => { loading.updateUpstreamErrorResolved = false })
  }) as AdminOpsRepository['updateUpstreamErrorResolved']

  const createAlertRule: AdminOpsRepository['createAlertRule'] = ((...args: unknown[]) => {
    loading.createAlertRule = true
    errors.createAlertRule = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.createAlertRule as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createAlertRule = error; throw error })
      .finally(() => { loading.createAlertRule = false })
  }) as AdminOpsRepository['createAlertRule']

  const updateAlertRule: AdminOpsRepository['updateAlertRule'] = ((...args: unknown[]) => {
    loading.updateAlertRule = true
    errors.updateAlertRule = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.updateAlertRule as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateAlertRule = error; throw error })
      .finally(() => { loading.updateAlertRule = false })
  }) as AdminOpsRepository['updateAlertRule']

  const deleteAlertRule: AdminOpsRepository['deleteAlertRule'] = ((...args: unknown[]) => {
    loading.deleteAlertRule = true
    errors.deleteAlertRule = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.deleteAlertRule as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.deleteAlertRule = error; throw error })
      .finally(() => { loading.deleteAlertRule = false })
  }) as AdminOpsRepository['deleteAlertRule']

  const updateAlertEventStatus: AdminOpsRepository['updateAlertEventStatus'] = ((...args: unknown[]) => {
    loading.updateAlertEventStatus = true
    errors.updateAlertEventStatus = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.updateAlertEventStatus as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateAlertEventStatus = error; throw error })
      .finally(() => { loading.updateAlertEventStatus = false })
  }) as AdminOpsRepository['updateAlertEventStatus']

  const createAlertSilence: AdminOpsRepository['createAlertSilence'] = ((...args: unknown[]) => {
    loading.createAlertSilence = true
    errors.createAlertSilence = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.createAlertSilence as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.createAlertSilence = error; throw error })
      .finally(() => { loading.createAlertSilence = false })
  }) as AdminOpsRepository['createAlertSilence']

  const updateEmailNotificationConfig: AdminOpsRepository['updateEmailNotificationConfig'] = ((...args: unknown[]) => {
    loading.updateEmailNotificationConfig = true
    errors.updateEmailNotificationConfig = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.updateEmailNotificationConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateEmailNotificationConfig = error; throw error })
      .finally(() => { loading.updateEmailNotificationConfig = false })
  }) as AdminOpsRepository['updateEmailNotificationConfig']

  const updateAlertRuntimeSettings: AdminOpsRepository['updateAlertRuntimeSettings'] = ((...args: unknown[]) => {
    loading.updateAlertRuntimeSettings = true
    errors.updateAlertRuntimeSettings = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.updateAlertRuntimeSettings as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateAlertRuntimeSettings = error; throw error })
      .finally(() => { loading.updateAlertRuntimeSettings = false })
  }) as AdminOpsRepository['updateAlertRuntimeSettings']

  const updateRuntimeLogConfig: AdminOpsRepository['updateRuntimeLogConfig'] = ((...args: unknown[]) => {
    loading.updateRuntimeLogConfig = true
    errors.updateRuntimeLogConfig = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.updateRuntimeLogConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateRuntimeLogConfig = error; throw error })
      .finally(() => { loading.updateRuntimeLogConfig = false })
  }) as AdminOpsRepository['updateRuntimeLogConfig']

  const resetRuntimeLogConfig: AdminOpsRepository['resetRuntimeLogConfig'] = ((...args: unknown[]) => {
    loading.resetRuntimeLogConfig = true
    errors.resetRuntimeLogConfig = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.resetRuntimeLogConfig as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.resetRuntimeLogConfig = error; throw error })
      .finally(() => { loading.resetRuntimeLogConfig = false })
  }) as AdminOpsRepository['resetRuntimeLogConfig']

  const cleanupSystemLogs: AdminOpsRepository['cleanupSystemLogs'] = ((...args: unknown[]) => {
    loading.cleanupSystemLogs = true
    errors.cleanupSystemLogs = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.cleanupSystemLogs as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.cleanupSystemLogs = error; throw error })
      .finally(() => { loading.cleanupSystemLogs = false })
  }) as AdminOpsRepository['cleanupSystemLogs']

  const updateAdvancedSettings: AdminOpsRepository['updateAdvancedSettings'] = ((...args: unknown[]) => {
    loading.updateAdvancedSettings = true
    errors.updateAdvancedSettings = null
    return Promise.resolve()
      .then(() => (adminOpsRepo.updateAdvancedSettings as (...a: unknown[]) => unknown)(...args))
      .catch((error: unknown) => { errors.updateAdvancedSettings = error; throw error })
      .finally(() => { loading.updateAdvancedSettings = false })
  }) as AdminOpsRepository['updateAdvancedSettings']

    return { loading, errors, updateErrorResolved, updateRequestErrorResolved, updateUpstreamErrorResolved, createAlertRule, updateAlertRule, deleteAlertRule, updateAlertEventStatus, createAlertSilence, updateEmailNotificationConfig, updateAlertRuntimeSettings, updateRuntimeLogConfig, resetRuntimeLogConfig, cleanupSystemLogs, updateAdvancedSettings }
  })
}

export const useAdminOpsActionStore = createAdminOpsActionStore()
