/**
 * Presentation-layer API surface for this feature.
 * Auto-generated by .tmp_gen_bridge.mjs.
 *
 * Re-exports data/datasources/* so Pages can consume feature data via
 *   `import { xxxAPI } from '@/features/<feature>/presentation/api'`
 * without violating R7 ("Page MUST NOT import data/**").
 */
export { updateConfig, probeEndpoint, deleteEvent, batchDeleteEvents, deleteEventsByFilter, promptAuditActionAPI } from '@/features/prompt-audit/data/datasources/promptAuditActionDatasource'
export { getConfig, getRuntime, listEvents, getEvent, previewDelete, listGroups, promptAuditQueryAPI } from '@/features/prompt-audit/data/datasources/promptAuditQueryDatasource'
export * as promptAuditAction from '@/features/prompt-audit/data/datasources/promptAuditActionDatasource'
export * as promptAuditQuery from '@/features/prompt-audit/data/datasources/promptAuditQueryDatasource'
