package config

import "github.com/spf13/viper"

func setStorageDefaults() {
	// Database
	viper.SetDefault("database.host", "localhost")
	viper.SetDefault("database.port", 5432)
	viper.SetDefault("database.user", "postgres")
	viper.SetDefault("database.password", "postgres")
	viper.SetDefault("database.dbname", "sub2api")
	viper.SetDefault("database.sslmode", "prefer")
	viper.SetDefault("database.max_open_conns", 256)
	viper.SetDefault("database.max_idle_conns", 128)
	viper.SetDefault("database.conn_max_lifetime_minutes", 30)
	viper.SetDefault("database.conn_max_idle_time_minutes", 5)
	viper.SetDefault("database.user_platform_quota_flusher_enabled", true)
	viper.SetDefault("database.user_platform_quota_flush_interval_ms", 2000)
	viper.SetDefault("database.user_platform_quota_flush_batch_size", 1000)

	// Redis
	viper.SetDefault("redis.host", "localhost")
	viper.SetDefault("redis.port", 6379)
	viper.SetDefault("redis.username", "")
	viper.SetDefault("redis.password", "")
	viper.SetDefault("redis.db", 0)
	viper.SetDefault("redis.dial_timeout_seconds", 5)
	viper.SetDefault("redis.read_timeout_seconds", 3)
	viper.SetDefault("redis.write_timeout_seconds", 3)
	viper.SetDefault("redis.pool_size", 1024)
	viper.SetDefault("redis.min_idle_conns", 128)
	viper.SetDefault("redis.max_idle_conns", 0)
	viper.SetDefault("redis.enable_tls", false)

	// Batch Image queue
	viper.SetDefault("batch_image.enabled", false)
	viper.SetDefault("batch_image.max_items_per_job_default", 200)
	viper.SetDefault("batch_image.max_items_per_job_trial", 50)
	viper.SetDefault("batch_image.max_output_images_per_job", 200)
	viper.SetDefault("batch_image.max_output_images_per_item", 4)
	viper.SetDefault("batch_image.max_prompt_chars_per_item", 8000)
	viper.SetDefault("batch_image.max_reference_images_per_job", 1000)
	viper.SetDefault("batch_image.max_reference_inline_bytes_per_job", 134217728)
	viper.SetDefault("batch_image.default_response_mime_type", "image/png")
	viper.SetDefault("batch_image.default_image_size", "1K")
	viper.SetDefault("batch_image.max_download_items_zip", 200)
	viper.SetDefault("batch_image.max_download_bytes_per_request", 536870912)
	viper.SetDefault("batch_image.max_download_duration_seconds", 600)
	viper.SetDefault("batch_image.max_download_concurrency_per_user", 1)
	viper.SetDefault("batch_image.input_retention_after_terminal_hours", 24)
	viper.SetDefault("batch_image.output_retention_after_terminal_hours", 72)
	viper.SetDefault("batch_image.output_retention_max_days", 7)
	viper.SetDefault("batch_image.cleanup_interval_minutes", 30)
	viper.SetDefault("batch_image.cleanup_batch_size", 100)
	viper.SetDefault("batch_image.queue_enabled", false)
	viper.SetDefault("batch_image.queue_ready_key", "batch_image:queue:ready")
	viper.SetDefault("batch_image.queue_delayed_key", "batch_image:queue:delayed")
	viper.SetDefault("batch_image.queue_active_key", "batch_image:queue:active")
	viper.SetDefault("batch_image.inflight_key_prefix", "batch_image:queue:inflight:")
	viper.SetDefault("batch_image.lock_key_prefix", "batch_image:queue:lock:")
	viper.SetDefault("batch_image.idempotency_key_prefix", "batch_image:queue:idem:")
	viper.SetDefault("batch_image.inflight_ttl_seconds", 604800)
	viper.SetDefault("batch_image.job_lock_ttl_seconds", 300)
	viper.SetDefault("batch_image.default_requeue_delay_seconds", 30)
	viper.SetDefault("batch_image.error_retry_delay_seconds", 60)
	viper.SetDefault("batch_image.lock_conflict_delay_seconds", 5)
	viper.SetDefault("batch_image.stale_active_after_seconds", 600)
	viper.SetDefault("batch_image.delayed_mover_interval_seconds", 5)
	viper.SetDefault("batch_image.recovery_interval_seconds", 300)
	viper.SetDefault("batch_image.delayed_move_limit", 100)
	viper.SetDefault("batch_image.recover_limit", 100)
	viper.SetDefault("batch_image.vertex_enabled", false)
	viper.SetDefault("batch_image.vertex_project_id", "")
	viper.SetDefault("batch_image.vertex_location", "global")
	viper.SetDefault("batch_image.vertex_managed_gcs_bucket", "")
	viper.SetDefault("batch_image.vertex_managed_gcs_prefix", "batch-image/{env}/{batch_id}")
	viper.SetDefault("batch_image.vertex_input_retention_hours", 24)
	viper.SetDefault("batch_image.vertex_output_retention_hours", 72)
	viper.SetDefault("batch_image.vertex_batch_prediction_base_url", "")
	viper.SetDefault("batch_image.vertex_gcs_base_url", "")

	// Image storage (async image task result offload to S3-compatible object storage)
	viper.SetDefault("image_storage.enabled", false)
	viper.SetDefault("image_storage.region", "auto")
	viper.SetDefault("image_storage.prefix", "images/")
	viper.SetDefault("image_storage.force_path_style", false)
	viper.SetDefault("image_storage.presign_expiry_hours", 24)
	viper.SetDefault("image_storage.max_download_bytes", 33554432)
	viper.SetDefault("image_storage.max_in_flight", 8)
	// Registered with empty defaults so AutomaticEnv can reach them: viper only
	// decodes keys present in AllKeys(), so a credential that is supplied purely
	// via IMAGE_STORAGE_* and never appears in config.yaml would be dropped and
	// silently disable the whole async image feature.
	viper.SetDefault("image_storage.endpoint", "")
	viper.SetDefault("image_storage.bucket", "")
	viper.SetDefault("image_storage.access_key_id", "")
	viper.SetDefault("image_storage.secret_access_key", "")
	viper.SetDefault("image_storage.public_base_url", "")
}
